### ISSUE TITLE
Duplicate Service VIP appearing on multiple nodes

### ISSUE THREAD

**Issue by zimmerry** [kube-vip/kube-vip#1005]
**Describe the bug**
With ARP and Service Election enabled, service VIPs will intermittently appear on 2 or more nodes. This leads to dropped packets and renders the service(s) effectively unreachable.

Restarting the daemonset with `kubectl rollout restart daemonset kube-vip-ds` will fix it, but it's been re-occuring every few days.

**To Reproduce**
1. Deploy kube-vip
2. Deploy LoadBalancer services
3. Wait...
4. When connections to services start dropping, check for duplicated VIPs with `ip a` on each node.

**Expected behavior**

**Screenshots**
In this instance, 139.181.89.11 appears on dvt-kube4 & dvt-kube9, and 139.181.89.8 appears on dvt-kube4 & dvt-kube7.
![image](https://github.com/user-attachments/assets/1ae88cd0-2633-434b-8ffc-f3fb14480dce)

**Environment (please complete the following information):**
 - OS/Distro: Rocky Linux 9.4
 - Kubernetes Version: v1.30.6
 - Kube-vip Version: v0.8.7

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.7
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.7
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_servicesinterface
          value: bond0
        - name: dns_mode
          value: first
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: enable_node_labeling
          value: "true"
        - name: svc_election
          value: "true"
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip-iptables:v0.8.7
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      nodeSelector:
        virtual: 'false'


  updateStrategy: {}
```

**Additional context**
I can set up automation to detect duplicates and restart the daemonset, but I feel like this isn't the intended functionality.

Possibly related, the service VIP is also duplicated if I create multiple services with the same LoadBalancerIP but different ports.
