### ISSUE TITLE
kube-vip stops watching services because of kubernetes service "watch" failure

### ISSUE THREAD

**Issue by souravl** [kube-vip/kube-vip#1033]
**Describe the bug**

Running 3 node k8s cluster - all control-plane roles with pod scheduling enabled on all.

kube-vip stops watching services because of kubernetes service "watch" failure:

```
I0110 09:36:29.671437       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-svcs-lock
time="2025-01-10T09:36:29Z" level=info msg="(svcs) starting services watcher for all namespaces"
time="2025-01-10T09:36:29Z" level=error msg="Error attempting to watch Kubernetes services"
time="2025-01-10T09:36:29Z" level=error msg="services -> {{ } {   <nil>} Failure too old resource version: 1 (132730) Expired nil 410}"
time="2025-01-10T09:36:29Z" level=warning msg="Stopping watching services for type: LoadBalancer in all namespaces"
time="2025-01-10T09:41:28Z" level=info msg="[UPNP] Refreshing 0 Instances"
```

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04.5 LTS
 - Kubernetes Version: v1.32.0
 - Kube-vip Version: v0.8.8

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: enp1s0
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 10.106.138.219
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.8
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 10.106.138.216
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}

```
