### ISSUE TITLE
Panic when trying to assign external IPv4 on dual stack cluster (v0.8.9)

### ISSUE THREAD

**Issue by mishun** [kube-vip/kube-vip#1052]
**Describe the bug**
Hi!
Basically, I've set up single node dual stack RKE2 cluster, and when I'm trying to expose IPv4 service (like in yaml example below) kube-vip's DaemonSet crashes. It's quite possible that I've configured something wrong, but it isn't supposed to crash with panic.

I did small regression tests and found that:
Works ok: v0.7.2, v0.8.0, v0.8.2, v0.8.3, v0.8.4
Crashes: v0.8.5, v0.8.9

Apologies if this is wrong repo to post this issue (since it kinda looks like that external library fails), but I've never programmed in Go and can't say for sure.

**To Reproduce**

Crash happens after applying something like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-ipv4
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  ipFamilies: [IPv4]
  loadBalancerIP: 10.155.30.242
  ports:
    - protocol: TCP
      name: http
      port: 80
    - protocol: TCP
      name: https
      port: 443
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
```

kube-vip's DaemonSet pod log:
```
$ kubectl logs kube-vip-ds-9phx7 --namespace kube-system
time="2025-01-24T14:11:31Z" level=info msg="Starting kube-vip.io [v0.8.9]"
time="2025-01-24T14:11:31Z" level=info msg="Build kube-vip.io [19e660d4a692fab29f407214b452f48d9a65425e]"
time="2025-01-24T14:11:31Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2025-01-24T14:11:31Z" level=info msg="Using node name [rke2-master-01-8e4cfc47]"
time="2025-01-24T14:11:31Z" level=info msg="prometheus HTTP server started"
time="2025-01-24T14:11:31Z" level=debug msg="Using external Kubernetes configuration from incluster config."
time="2025-01-24T14:11:31Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2025-01-24T14:11:31Z" level=info msg="Starting UPNP Port Refresher"
time="2025-01-24T14:11:31Z" level=debug msg="init enable service security: false"
time="2025-01-24T14:11:31Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [plndr-svcs-locky], id [rke2-master-01-8e4cfc47]"
I0124 14:11:31.238364       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-svcs-locky...
time="2025-01-24T14:11:31Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [rke2-master-01-8e4cfc47]"
I0124 14:11:31.238741       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
I0124 14:11:31.249998       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-svcs-locky
time="2025-01-24T14:11:31Z" level=debug msg="skip starting traffic mirroring since it's not enabled."
time="2025-01-24T14:11:31Z" level=info msg="(svcs) starting services watcher for all namespaces"
time="2025-01-24T14:11:31Z" level=debug msg="(svcs) [traefik-ipv4] has been added/modified with addresses [[10.155.30.242]]"
time="2025-01-24T14:11:31Z" level=debug msg="[STARTING] Service Sync"
time="2025-01-24T14:11:31Z" level=debug msg="init enable service security: false"
time="2025-01-24T14:11:31Z" level=info msg="(svcs) adding VIP [10.155.30.242] via eth0 for [default/traefik-ipv4]"
time="2025-01-24T14:11:31Z" level=debug msg="skip stopping traffic mirroring since it's not enabled."
panic: runtime error: index out of range [0] with length 0

goroutine 83 [running]:
github.com/vishvananda/netlink.(*Handle).addrHandle(0x3b11900, {0x27758a8, 0xc000570900}, 0xc000181080, 0xc000533618)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.3.0/addr_linux.go:139 +0xe1b
github.com/vishvananda/netlink.(*Handle).AddrReplace(0x3?, {0x27758a8?, 0xc000570900?}, 0xf21e9b0affff0000?)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.3.0/addr_linux.go:53 +0xc9
github.com/vishvananda/netlink.AddrReplace(...)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.3.0/addr_linux.go:42
github.com/kube-vip/kube-vip/pkg/vip.(*network).AddIP(0xc0005bc140, 0x69?)
	/src/pkg/vip/address.go:292 +0x50
github.com/kube-vip/kube-vip/pkg/cluster.(*Cluster).StartLoadBalancerService(0xc00016cc80, 0xc000443508, 0x0)
	/src/pkg/cluster/service.go:342 +0x484
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).addService(0xc0003ca380, {0x27942e8, 0xc000174230}, 0xc0003d2a08)
	/src/pkg/manager/services.go:96 +0xc8
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).syncServices(0xc0003ca380, {0x27942e8, 0xc000174230}, 0xc0003d2a08, 0xc00029e5a0?)
	/src/pkg/manager/services.go:66 +0x2a5
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).servicesWatcher(0xc0003ca380, {0x27942e8, 0xc0000f40f0}, 0xc000328000)
	/src/pkg/manager/watch_services.go:261 +0x1712
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).startARP.func3({0x27942e8, 0xc0000f40f0})
	/src/pkg/manager/manager_arp.go:126 +0x7a
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run in goroutine 1
	/go/pkg/mod/k8s.io/client-go@v0.32.0/tools/leaderelection/leaderelection.go:220 +0xe6
```

Configmap:
```
$ kubectl describe configmap kubevip --namespace kube-system
Name:         kubevip
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
cidr-global:
----
fd83:6c1c:2c33:ec65:85ad:30ff:13cf::/112,10.155.30.240/28

BinaryData
====

Events:  <none>
```

**Expected behavior**
To correctly assign external IPv4 to service. If fact, it worked with some earlier versions.

**Environment (please complete the following information):**
 - OS/Distro: openSUSE Leap Micro 6.1 / kernel 6.4.0-21-default
 - Kubernetes Version: v1.31.4+rke2r1
 - Kube-vip Version: v0.8.9

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.9
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.9
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_loglevel
          value: "5"
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "128"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-locky
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: fd83:6c1c:2c33:ec65:a4c8:4343:ee49:bf45
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.8.9
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```
