### ISSUE TITLE
kube-vip assigned an IP that is not in its pool

### ISSUE THREAD

**Issue by martialblog** [kube-vip/kube-vip#1058]
Hi,

Not sure if this is expected behavior or a bug, but: while testing kube-vip I noticed that kube-vip did assign an IP that is not in its pool.

My kubevip ConfigMap is:

```
apiVersion: v1
data:
  range-global: 172.16.98.5-172.16.98.6
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-vip
```

When I create a Service Type Loadbalancer with an explicit `loadBalancerIP: 172.16.98.111`, then kube-vip will start to anounce it.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.16.98.111"],"port":89,"protocol":"TCP","serviceName":"test:nginx","allNodes":false}]
    kube-vip.io/loadbalancerIPs: 172.16.98.111
    kube-vip.io/vipHost: mynode
  name: nginx
  namespace: test
spec:
  allocateLoadBalancerNodePorts: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 172.16.98.111
  ports:
    - name: nginx
      port: 89
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 172.16.98.111
        ipMode: VIP
        ports:
          - port: 89
            protocol: TCP
```

From the kube-vip logs:

```
time="2025-01-30T14:20:21Z" level=info msg="(svcs) adding VIP [172.16.98.111] via eth0 for [test/nginx]"
time="2025-01-30T14:20:24Z" level=warning msg="Re-applying the VIP configuration [172.16.98.111] to the interface [eth0]"
```

And the service is now available on the IP:

```
curl http://172.16.98.111:89
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
```

I used the Helm Chart to install kube-vip (in a dedicated kube-vip namespace) with the following values:

```
containers:
 - args:
     - manager
   env:
     - name: vip_address
       value: 172.16.98.4
     - name: cp_enable
       value: 'true'
     - name: enable_service_security
       value: 'false'
     - name: lb_enable
       value: 'true'
     - name: lb_port
       value: '6443'
     - name: svc_election
       value: 'false'
     - name: svc_enable
       value: 'true'
     - name: vip_arp
       value: 'true'
     - name: vip_cidr
       value: '32'
     - name: vip_interface
     - name: vip_leaderelection
       value: 'false'
   image: ghcr.io/kube-vip/kube-vip:v0.8.9
```

---

Is this excepted behavior or am I doing anything wrong?
I would have expected the IP not to be applied by kube-vip and the Service Type Loadbalancer to remain pending.

I saw this in the docs:

> We can also expose a specific address by specifying it imperatively on the command line:
> kubectl expose deployment nginx-deployment --port=80 --type=LoadBalancer --name=nginx --load-balancer-ip=1.1.1.1

But 1.1.1.1 is only an example right? 1.1.1.1 would still need to be in the kubevip ConfigMap?

Thanks
Markus
