### ISSUE TITLE
Connectivity error (connections dropped and reset)

### ISSUE THREAD

**Issue by chrisarnott86** [kube-vip/kube-vip#1061]
**Describe the bug**
After installing kube-vip with egress facility despite initial testing showing everything was working properly I found that there were connectivity issues to services running in the cluster. (these services are exposed via traefik ingress controller, and loadbalancer type services in conjunction with metallb) This manifested as failed requests in browsers (strangely this seemed worse in Firefox than chrome derivatives). Also connections dropped or reset for external services (e.g. jenkins connection to artifactory running in the cluster). It was a couple of days after kube-vip installation that this seemed to become a problem. Immediately after removing kube-vip the connectivity issues were resolved.

**To Reproduce**
Install kube-vip with egress enabled (in k3s), existing services then had connectivity issues with browser sessions dropping or page elements not loading properly, and service connectivity dropping/being reset.

**Expected behavior**
Connections to services behind traefik ingress and other loadbalanced services remain secure and reliable after installation of kube-vip

**Environment (please complete the following information):**
 - OS/Distro: Debian 12
 - Kubernetes Version: v1.31.4+k3s1 (k3s)
 - Kube-vip Version: v0.8.9 (iptables)

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.9
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.9
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: ens3
        - name: vip_cidr
          value: "24"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: svc_election
          value: "true"            
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: X.X.X.X
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip-iptables:v0.8.9
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```

**Comment by thebsdbox** [comment]
>these services are exposed via traefik ingress controller, and loadbalancer type services in conjunction with metallb 

You're using kube-vip and metallb at the same time?

**Comment by thebsdbox** [comment]
kube-vip will watch for all services of type load-balancer:

```
        - name: svc_enable
          value: "true"
```

It's quite likely that kube-vip and metallb are both trying to expose LoadBalancer addresses.

**Comment by chrisarnott86** [comment]
Thanks @thebsdbox. I hadn't realised that kube-vip would attempt to expose an address without kube-vip-cloud-controller being installed? Here are a couple of different people installing kube-vip and metallb together https://gist.github.com/rosswf/e5c4c85efb54a9f8d6e19a21cf09aa63 and https://blog.chkpwd.com/posts/k3s-ha-installation-kube-vip-and-metallb/ Would you say this is not a valid approach? If I were to remove metallb and install the kube-vip-cloud-controller instead should that work?

**Comment by chrisarnott86** [comment]
Thanks, I specifically do need the egress function, that's the new feature I'm trying to introduce to the cluster using kube-vip. If service watching is enabled (as I have) then is the use of metallb definitely a problem? Should I switch to using kube-vip-cloud-controller instead for assigning addresses?

**Comment by Cellebyte** [comment]
@chrisarnott86 you can use it with metallb.

Just watch the status of the service kube-vip and metallb will fight there.

Just disable status update on kube-vip should solve your problem.

**Comment by chrisarnott86** [comment]
@Cellebyte, thanks very much for your input. How do I disable status update for kube-vip? I can't find that in the documentation.

**Comment by Cellebyte** [comment]
```yaml
        - name: disable_service_updates
          value: "true"

```

**Comment by chrisarnott86** [comment]
Thanks @Cellebyte, I'll do some testing with that flag set and see how it goes.

**Comment by Cellebyte** [comment]
Just inform here if it solved your issue.

**Comment by chrisarnott86** [comment]
@thebsdbox @Cellebyte. I've been able to add the parameter now in our production cluster. Initial signs are that the connectivity errors I saw previously are not occurring, having said that the problems I saw before didn't seem to occur immedeiately after installing kube-vip. I am however seeing new warnings logged by k3s. On two of the master nodes I'm seeing errors like:

```
2025-03-05T14:20:34.234986+00:00 master1 k3s[762]: {"level":"warn","ts":"2025-03-05T14:20:34.234259Z","caller":"embed/config_logging.go:161","msg":"rejected connection on peer endpoint","remote-addr":"X.X.12.134:42430","server-name":"","ip-addresses":["X.X.12.130","127.0.0.1","::1","X.X.12.128","10.43.0.1"],"dns-names":["kine.sock","localhost","master3"],"error":"tls: \"X.X.12.134\" does not match any of DNSNames [\"kine.sock\" \"localhost\" \"master3\"] (lookup kine.sock: no such host)"}
```

The three nodes have the addresses:

master1 - X.X.12.124
master2 - X.X.12.116
master3 - X.X.12.128

Kube-vip address for api access: X.X.12.130


Where the remote-addr can change but is always the IP of one of the loadbalancer services (a pre-existing service from prior to kube-vip installation, which hasn't been changed to make it an egress)

On the third node I'm seeing

```
2025-03-05T14:20:33.866821+00:00 master3 k3s[4172501]: {"level":"warn","ts":"2025-03-05T14:20:33.866739Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"<randomstring>","rtt":"5.416917ms","error":"EOF"}
```

Any thoughts on exactly what these errors are would be appreciated. Definitely those errors only appeared after adding kube-vip.

**Comment by chrisarnott86** [comment]
@Cellebyte, @thebsdbox I've done more testing on a new test cluster to try and eliminate as many variables as possible. Using a barebones debian (not configured with our org's standard ansible config) I recreated the same error messages, so it's definitely not being introduced through any of our config process. I've also found that with version 0.8.4 I get all the functionality working as it should but version 0.8.5 and above introduce the errors I saw above. I'll leave my new test cluster running with version 0.8.4 to see that it's stable in the long run. You can let me know how best to proceed with debugging version 0.8.5 and above now that it seems pretty certain that the error lies with kube-vip and not any external software or environment details.

**Comment by chrisarnott86** [comment]
@Cellebyte and @thebsdbox, I recently installed version 0.9.1 in our production cluster, I had to remove it after I was seeing similar connection dropping issues to previously with earlier versions. In this instance I wasn't seeing any of the kine/raft type errors that were previously there, simply connections to services having drops/resets. The drops were not constant, so for example connections to our gitea service would work sometimes and drop others. Hopefully there is some way we can further diagnose this. 

For clarity I tested adding/removing the kube-vip manifest and it was an immediate difference in terms of observing the connection issues or not, so I know with certainty that it's related to kube-vip.

Here's the manifest I'm using

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.9.1
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.9.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.9.1
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.9.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: ens3
        - name: vip_cidr
          value: "24"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: svc_election
          value: "true"
        - name: disable_service_updates
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: X.Y.12.130
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip-iptables:v0.9.1
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```
