### ISSUE TITLE
Kubevip crash when enabling setting lb_fwdmethod method to masquerade

### ISSUE THREAD

**Issue by Jonaprince** [kube-vip/kube-vip#1065]
**Describe the bug**

I want to expose the Kubernetes API server through port 443 on a VIP. However, when deploying using these options:

```yaml
- name: lb_port
   value: "443"
- name: lb_fwdmethod
   value: masquerade
 - name: lb_enable
    value: "true"
```

kubevip crash with following message: 

```
time="2025-02-06T11:45:11Z" level=fatal msg="could not configure IPTables: could not add iptables rules for masquerade: could not get iptables version: run cmd 'iptables --version' wtith error: exec: \"iptables\": excutable file not found in $PATH"
```

It seems that this problem is related to this issue https://github.com/kube-vip/kube-vip/issues/610
I don't fully understand why iptables is being called, since it should only configure IPVS entries. I may be missing something, though.

**To reproduce**

Deploy kube-vip with following configuration:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens192
        - name: lb_fwdmethod
          value: masquerade
        - name: lb_enable
          value: "true"
        - name: lb_port
          value: "443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.1.101
        image: ghcr.io/kube-vip/kube-vip:v0.8.9
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

```

**Expected behavior**

Kube vip should not crash and forwarding ipvs rules must be created.

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 2204]
 - Kubernetes Version: v1.31.5
 - Kube-vip Version: 0.8.9
