### ISSUE TITLE
service VIP is not accessible from pods hosted on same node

### ISSUE THREAD

**Issue by KonstantinNosov** [kube-vip/kube-vip#1086]
**Describe the bug**
I have vip for load balancing services on k3s cluster. nginx ingress has vip assigned and works fine when accessed from outside cluster or nodes not hosting the VIP. But when accessed from node hosting the VIP (pods or node itself) VIP can not be reached

**To Reproduce**
1. Setup vip
2. Setup nginx ingress with vip assigned for service
3. ssh to node hosting the vip 
4. telnet VIP 443

**Expected behavior**
telnet can access the port

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 2404
 - Kubernetes Version: v1.32.1+k3s1
 - Kube-vip Version: 0.8.9

**`Kube-vip.yaml`:**
``` yaml
     containers:
        - args:
            - manager
            - '--prometheusHTTPServer='
          env:
            - name: cp_enable
              value: 'false'
            - name: cp_namespace
              value: kube-system
            - name: enable_service_security
              value: 'true'
            - name: lb_class_legacy_handling
              value: 'true'
            - name: lb_class_name
              value: kube-vip.io/kubevip-internal
            - name: lb_class_only
              value: 'true'
            - name: lb_enable
              value: 'true'
            - name: lb_port
              value: '6443'
            - name: svc_election
              value: 'true'
            - name: svc_enable
              value: 'true'
            - name: vip_arp
              value: 'true'
            - name: vip_cidr
              value: '32'
            - name: vip_ddns
              value: 'false'
            - name: vip_interface
              value: eth0
            - name: vip_leaderelection
              value: 'true'
            - name: vip_leaseduration
              value: '15'
            - name: vip_renewdeadline
              value: '10'
            - name: vip_retryperiod
              value: '2'
            - name: vip_servicesinterface
              value: vip_internal
```

**Additional context**
nginx ingress service manifest
``` yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    exordis/subsystemDescription: infrastructure subsystem
    kube-vip.io/loadbalancerIPs: 192.168.113.51
    kube-vip.io/vipHost: k3s-worker03
  name: ingress-nginx-internal-controller
  namespace: ingress-nginx
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.128.25
  clusterIPs:
    - 10.43.128.25
  externalTrafficPolicy: Local
  healthCheckNodePort: 30513
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: kube-vip.io/kubevip-internal
  ports:
    - appProtocol: http
      name: http
      nodePort: 32156
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      nodePort: 31944
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-internal
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.113.51
        ipMode: VIP
        ports:
          - port: 80
            protocol: TCP
          - port: 443
            protocol: TCP
```

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @KonstantinNosov , I heave created simple k3s setup with 3 VM nodes today to test this. However, I am unable to reproduce this behavior you've mentioned, as I am always able to connect to the VIP (192.168.113.51) form each node and each pod regardless of which node it is running on.

My service definition I tested with:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.113.51
    kube-vip.io/vipHost: k3s-1
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.170.89
  clusterIPs:
  - 10.43.170.89
  externalTrafficPolicy: Local
  healthCheckNodePort: 32233
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: kube-vip.io/kubevip-internal
  ports:
  - name: http
    nodePort: 32156
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31944
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: my-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.113.51
      ipMode: VIP
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TC
```

As for env I only changed 
```
- name: vip_interface
  value: enp1s0
- name: vip_servicesinterface
  value: enp1s0
```

I am just wondering, what is your `vip_internal` interface?
