### ISSUE TITLE
UPnP error on router without IPv6

### ISSUE THREAD

**Issue by richardr1126** [kube-vip/kube-vip#1127]
**Describe the bug**
I have installed kube-vip for k3s with the kube-vip cloud provider. I have a router with UPnP enabled in the admin client settings, however the router does not have an IPv6 address assigned or enabled. When I try to annotate an ingress nginx service with UPnP forwarding I get an error.

```
kube-vip-ds-2mxdf kube-vip
time="2025-04-13T03:35:50Z"
level=warning
msg="[UPNP] Unable to find WANIPv6FirewallControl1Clients for Gateway http://192.168.0.1:5431/dyndev/uuid:<redacted> [goupnp: service \"urn:schemas-upnp-org:service:WANIPv6FirewallControl:1\" not found within device \"Broadcom ADSL Router\" (UDN=\"uuid:<redacted>\")]"
```

**To Reproduce**
1. Router with UPnP enabled, but no ipv6
2. Installed kube-vip Daemonset with UPnP enabled in config + cloud provider
3. Install ingress-nginx with annotation for upnp forwarding
4. Receive ipv6 error from kube-vip pod
5. Can't find documentation to disable ipv6, if possible

**Expected behavior**
Disable UPnP forwarding IPv6 if not working, or manually.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu Server 2404 on Rasperry pi 5
 - Kubernetes Version: v1.32.3+k3s1
 - Kube-vip Version: v0.8.9

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.9
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.9
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "true"
        - name: enableUPNP
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.0.40
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.8.9
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```

**Additional context**
Full error from kube-vip startup:
```
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:46Z" level=info msg="Starting kube-vip.io [v0.8.9]"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:46Z" level=info msg="Build kube-vip.io [19e660d4a692fab29f407214b452f48d9a65425e]"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:46Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:46Z" level=info msg="prometheus HTTP server started"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:46Z" level=info msg="Using node name [raspberrypi]"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="Found UPNP IGD2 Gateway address[<redacted>] error: [%!s(<nil>)]"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="Starting UPNP Port Refresher"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [plndr-svcs-lock], id [raspberrypi]"
kube-vip-ds-2mxdf kube-vip I0413 03:35:48.790134       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-svcs-lock...
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [raspberrypi]"
kube-vip-ds-2mxdf kube-vip I0413 03:35:48.792297       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
kube-vip-ds-2mxdf kube-vip I0413 03:35:48.804969       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-svcs-lock
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="(svcs) starting services watcher for all namespaces"
kube-vip-ds-2mxdf kube-vip I0413 03:35:48.806215       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-cp-lock
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="Node [raspberrypi] is assuming leadership of the cluster"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [192.168.0.40/eth0]"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:48Z" level=info msg="(svcs) adding VIP [192.168.0.69] via eth0 for [default/ingress-nginx-controller]"
kube-vip-ds-2mxdf kube-vip time="2025-04-13T03:35:50Z" level=warning msg="[UPNP] Unable to find WANIPv6FirewallControl1Clients for Gateway http://192.168.0.1:5431/dyndev/uuid:<redacted> [goupnp: service \"urn:schemas-upnp-org:service:WANIPv6FirewallControl:1\" not found within device \"Broadcom ADSL Router\" (UDN=\"uuid:<redacted>\")]"
kube-vip-ds-2mxdf kube-vip panic: runtime error: invalid memory address or nil pointer dereference
```
