### ISSUE TITLE
kube-vip pod restart unlimited

### ISSUE THREAD

**Issue by scyberway** [kube-vip/kube-vip#1147]
OS:ubuntu 24.04 x64 cloud image on pve
kube-vip: v0.8.10
kubernetes:1.31.8
containerd:1.7.6

kube-vip.yaml

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: eth0
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: lb_enable
      value: "true"
    - name: lb_port
      value: "6443"
    - name: lb_fwdmethod
      value: local
    - name: address
      value: 192.168.1.200
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.10
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/super-admin.conf
    name: kubeconfig
status: {}
```

![Image](https://github.com/user-attachments/assets/310d576c-69a0-4112-a663-9d91c7f4c337)

![Image](https://github.com/user-attachments/assets/cb93330e-1af8-4482-b3cc-4d6b119da673)

the first node k8s111 is the one I init the cluster,but after i joined the other 2 nodes k8s112 and k8s113 the kube-vip pod on the 2 nodes are always restarting, and the log told me the token not exists but on the first node k8s111 the pod is running without the token file.
