### ISSUE TITLE
Possibly need to disable rp_filter for VIP on macvlan

### ISSUE THREAD

**Issue by jennydaman** [kube-vip/kube-vip#1170]
**Describe the bug**

Starting in version 0.8.10, kube-vip adds the IP address to a macvlan interface instead of a physical interface. In the logs below, I have a:

- physical interface `enp1s0f0`
- service `chris-argentum`
- IP `10.72.8.237` obtained via DHCP

```
2025/05/14 19:40:20 INFO kube-vip bind interface=enp1s0f0
-- snip --
2025/05/14 19:40:32 INFO creating new macvlan interface for DHCP interface=vip-66a0c307
2025/05/14 19:40:32 INFO new macvlan interface interface=vip-66a0c307 "hardware address"="\x00\x00l\xc8%\x7f"
-- snip --
2025/05/14 19:40:32 INFO Hostname specified for dhcp lease interface=vip-66a0c307 hostname=chris-argentum
2025/05/14 19:40:32 DEBUG trying to get a new IP attempt=0
2025/05/14 19:40:32 DEBUG init-reboot ip=10.72.8.237
2025/05/14 19:40:33 DEBUG using channel
2025/05/14 19:40:33 DEBUG dhcp timeouts timeout1=84h0m0s timeoute2=147h0m0s
2025/05/14 19:40:33 DEBUG service security enabled=false
2025/05/14 19:40:33 INFO (svcs) adding VIP ip=10.72.8.237 interface=vip-66a0c307 namespace=chris name=chris-ui-argentum
2025/05/14 19:40:33 DEBUG service update namespace=chris name=chris-ui-argentum
2025/05/14 19:40:33 INFO layer 2 broadcaster starting
2025/05/14 19:40:33 DEBUG type: 24, route: {Ifindex: 5 Dst: 10.72.8.237/32 Src: 10.72.8.237 Gw: <nil> Flags: [] Table: 255 Realm: 0}
2025/05/14 19:40:33 DEBUG layer 2 update ip=10.72.8.237 interface=vip-66a0c307 ms=3000
2025/05/14 19:40:33 INFO [service] synchronised in=1058ms
```

This configuration yields ~92% packet loss when I run `ping -c 1000 chris-argentum`.

**To Reproduce**

Not sure how much of this bug is specific to my network.

1. Have a bare-metal Kubernetes cluster
2. Deploy kube-vip version 0.8.10 or 0.9.1
3. Create a LoadBalancer service

**Expected behavior**

Reverting to kube-vip v0.8.9 then rebooting the nodes solves the problem, achieving 0% packet loss. Logs show the IP address is assigned to the physical interface `enp1s0f0`. No `vip-*` is created.

```
time="2025-05-14T18:10:41Z" level=info msg="kube-vip will bind to interface [enp1s0f0]"
-- snip --
time="2025-05-14T18:10:49Z" level=info msg="(svcs) adding VIP [10.72.8.237] via enp1s0f0 for [chris/chris-ui-argentum]"
time="2025-05-14T18:10:49Z" level=debug msg="(svcs) will update [chris/chris-ui-argentum]"
time="2025-05-14T18:10:49Z" level=debug msg="(svcs) broadcasting ARP update for 10.72.8.237 via enp1s0f0, every 3000ms"
```

**`Kube-vip.yaml`:**

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.9.1
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.9.1
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: dns_mode
          value: first
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: enable_node_labeling
          value: "true"
        - name: vip_address
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.9.1
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      nodeSelector:
        kubernetes.io/hostname: one-specific-node-for-troubleshooting
```

**Additional context**

None

**Comment by Cellebyte** [comment]
@jennydaman we had a pull-request which changed it from physical to macvlan when DHCP is used see #897 and the issue #871.
Macvlan itself should not cause packet loss, maybe it is something else?

general info on macvlan: https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#macvlan

**Comment by jennydaman** [comment]
Thanks for the info, I see. #871 is definitely a lot to take in.

I will try to debug my network by creating a macvlan some other way, which might help us isolate the problem as being with my network or with kube-vip. Do you have any other advice on how to debug or general wisdom regarding packet loss when trying to reach a macvlan interface?

**Comment by Cellebyte** [comment]
@jennydaman what you can try is running a trace route using `mtr` to your TCP Port of the service and check with `pwru` if all packets hit the node.
Maybe you can see why it gets dropped.

**Comment by jennydaman** [comment]
@Cellebyte thanks for the pointers.

In summary, I found that packets are dropped by the kube-vip host because of reasons `SKB_CONSUMED` and `SKB_DROP_REASON_IP_RPFILTER`.

I was able to fix the issue by disabling `rp_filter`:

```shell
echo 0 > /proc/sys/net/ipv4/conf/vip-66a0c307/rp_filter
```

Can you tell me whether this is indicative of some deeper problem, or is it something we should solve by adding a feature to kube-vip?

<details>
<summary>More debugging info</summary>

On the "server" I am running kube-vip v0.9.1 and using `pwru 'dst host 10.72.8.237 and dst port 80 and tcp'` to monitor the network. The IP address `10.72.8.237` is the IP address given to kube-vip by the DHCP server.

On the "client" I am simply running `curl http://hostname:80` where `hostname` is the value of the `kube-vip.io/loadbalancerHostname` annotation on the LoadBalancer service.

In the attached log of `pwru`, the `curl` client's IP address is `10.72.8.70`.

[pwru_log.txt](https://github.com/user-attachments/files/20842357/pwru_log.txt)

</details>

**Comment by Cellebyte** [comment]
@jennydaman that is a good question.
I don't know if configuring rp_filter with `0` is correct or maybe even wanted.
I think this topic needs a short investigation.

@chdxD1 maybe a short feedback on this topic would be good.

**Comment by chdxD1** [comment]
Moving the IP to the physical interface would bring up the issues from #871 again (one of the best issues I've read).

Some distros default to rp_filter being 0 anyway, while not ideal it should be fine to have rp_filter set to 0 for the vip macvlan interface.

**Comment by jennydaman** [comment]
Right, I forgot to mention my machines are running AlmaLinux which probably has tight security defaults.

Setting `rp_filter=0` or `rp_filter=2` fixes the problem and seems like a better approach than moving the IP back to the physical interface. I have updated the title of this GitHub issue to reflect the idea.

The question is, will kube-vip in a future version be responsible for setting `rp_filter` correctly? Asking to know whether I should be writing my own Ansible notebook to fix this or wait for the feature here. (Sorry, I would love to contribute but I do not know Go.)

**Comment by Cellebyte** [comment]
@jennydaman as the Macvlan interface is managed by kube-vip we can add this without any side effects to the other network configurations on the node.

**Comment by Cellebyte** [comment]
@jennydaman it would be awesome if you couldtry the new functionality in version v.1.0.0 :)

**Comment by jennydaman** [comment]
Thanks for the ping! I got around to trying it just now. Things work with a little tweaking: kube-vip needs to be allowed to write to `/proc`:

```
      volumes:
        - name: proc-net
          hostPath:
            path: /proc/sys/net
```

It would be nice if these extra configurations were supported by the config generator. There might also be some new securityContext configs in Kubernetes 1.33 to consider (I haven't upgraded from 1.31 yet, so IDK): https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#proc-access
