### ISSUE TITLE
Zebra Integration

### ISSUE THREAD

**Issue by mushrushu** [kube-vip/kube-vip#1186]
Hello! 
continuing previous chat on the matter

**Is your feature request related to a problem? Please describe.**
I have a need to be able not only to announce my IPs to upstream routers but also to receive routes for specific prefixes from them.

**Describe the solution you'd like**
AFAIK it becomes possible through integration with [zebra](https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md) since kube-vip uses gobgp internally. I was able to check the viability of that assumption with quick hack in pkg/bgp/server.go
```go
diff --git a/pkg/bgp/server.go b/pkg/bgp/server.go
index 186ad25..b7b78ee 100644
--- a/pkg/bgp/server.go
+++ b/pkg/bgp/server.go
@@ -58,6 +58,14 @@ func NewBGPServer(c *Config, peerStateChangeCallback func(*api.WatchEventRespons
 		}
 	}
 
+	if err = b.s.EnableZebra(context.Background(), &api.EnableZebraRequest{
+		Url:          "unix:/var/run/frr/zserv.api",
+		Version:      6,
+		SoftwareName: "frr8.3",
+	}); err != nil {
+		log.Error("failed to enable zebra:", err)
+	}
+
 	return
 }
 
```
That allowed me to check to possible scenarios:
- zebra process is running on a host, and its socket is passed with hostpath to kube-vip
- zebra proccess is running in sidecar container, and it's socket is passed through emptydir

In both cases the routes received were installed in hosts routing table, achieving the goal.

At the first glance I think this can be accommodated to the project structure with extension of kubevip.Config, bgp.Config , addition of some flags to allow frr version and socket path configuration and addition of zebra enablement in bgp.NewBGPServer() depending on bgp.Config.

**Describe alternatives you've considered**
Since kube-vip uses gobgp internally I don't think there are any other solutions but I'm open to any suggestions.

**Comment by thebsdbox** [comment]
This looks pretty much like you've worked it all out then 😂 This looks a relatively straightforward addition, with the only real changes being a hostPath `/var/run/frr/zserv.api` and some additional configuration that will need passing in. This looks good to me, I'll see if @Cellebyte or @p-strusiewiczsurmacki-mobica has any additional feedback.

**Comment by mushrushu** [comment]
Yep, neither am I liking the hostpath, hence the sidecar scenario. 
I've used quay.io/frrouting/frr:8.3.0 image for that and changed command to just "/usr/lib/frr/zebra". I’m more in favour of that case.
currently my daemonset manifest looks like this:
```yaml
apiVersion: apps/v1     
kind: DaemonSet           
metadata:                
  annotations: {}        
  labels:                   
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.9.1
  name: kube-vip-ds    
  namespace: kube-system     
spec:                           
  selector:               
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.9.1
    spec:
      volumes:
      - name: sockets-volume
        emptyDir:
          sizeLimit: 50Mi
          medium: Memory
      containers:
      - name: frr
        image: "quay.io/frrouting/frr:8.3.0"
        command:
        - "/usr/lib/frr/zebra"
        volumeMounts:
        - mountPath: /var/run/frr
          name: sockets-volume
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - CAP_SETUID
            - CAP_SETGID
            - CAP_SYS_ADMIN
            drop:
            - ALL
      - args:
        - manager
        env:
… basic kub-vip env vars …
        image: localhost/kube-vip:latest
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - CAP_DAC_OVERRIDE
            drop:
            - ALL
#          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/frr
          name: sockets-volume
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
