### ISSUE TITLE
Manifest daemonset not setting default router-id

### ISSUE THREAD

**Issue by budimanjojo** [kube-vip/kube-vip#163]
**Describe the bug**
I follow the hybrid mode setup for Daemonset method with BGP and it keeps failing with this log:
```
time="2021-01-30T09:43:52Z" level=info msg="Starting the BGP server to adverise VIP routes to BGP peers"
time="2021-01-30T09:43:52Z" level=fatal msg="invalid router-id format: "
```

**Environment (please complete the following information):**
 - OS/Distro: Arch Linux
 - Kubernetes Version: 1.20.2
 - Kube-vip Version: 0.3.1

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: vip_interface
          value: lo
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_startleader
          value: "false"
        - name: vip_addpeerstolb
          value: "true"
        - name: vip_localpeer
          value: budimanjojo-kube1:192.168.200.200:10000
        - name: bgp_enable
          value: "true"
        - name: bgp_routerid
        - name: bgp_as
          value: "65000"
        - name: bgp_peeraddress
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "65000"
        - name: bgp_peers
          value: 192.168.200.201:65000::false,192.168.200.202:65000::false,192.168.200.203:65000::false
        - name: vip_address
          value: 192.168.200.200
        image: plndr/kube-vip:0.3.1
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

```
If I edit the manifest file and put my ip address into the `bgp_routerid` value then the daemonset can run again.

**Comment by thebsdbox** [comment]
Can you describe what command you are using to generate the manifest? If the `bgp_routerid` is blank then the BGP peering will fail.

**Comment by budimanjojo** [comment]
This was the command I used
```
╰ sudo kube-vip manifest daemonset \
--interface lo \
--vip 192.168.200.200 \
--controlplane \
--bgp \
--taint \
--inCluster \
--bgppeers 192.168.200.201:65000::false,192.168.200.202:65000::false,192.168.200.203:65000::false | sudo tee /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
```

**Comment by thebsdbox** [comment]
Ah! I wrote the documentation wrong! 

I'll fix this ! Apologies.

**Comment by thebsdbox** [comment]
https://kube-vip.io/hybrid/static/#bgp This is now updated! 

Apologies for the confusion.

**Comment by budimanjojo** [comment]
But what about daemonset? Will it be the same? Because each device need to have its own routerID

**Comment by budimanjojo** [comment]
https://kube-vip.io/hybrid/daemonset/ Please update there too :)

**Comment by voidengineer** [comment]
Could this please be reopend? It is still not clear how to configure the daemonset!
Each node needs to have its unique `bgp_router_id`. The same question stands for `vip_localpeer` which is generated with the one value that was current on the node, where the manifest generation was executed.

**Comment by voidengineer** [comment]
Could this work?
```yaml
- name: bgp_routerid
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
```
But I still have no idea what `vip_localpeer` is used for.
