### ISSUE TITLE
Multiple VIP's using multiple manifest file per vip/interface ..

### ISSUE THREAD

**Issue by workhorse2020** [kube-vip/kube-vip#181]
**Is your feature request related to a problem? Please describe.**
I see that we can create a single manifest file and apply the same i.e vip/interface.

**Describe the solution you'd like**
Can we have multiple manifest file each with different vip/interface. Since multiple interface are there in master which requires vips

**Describe alternatives you've considered**
With current option we are planning to shift to kube-vip to keepalive since it has multiple ip's that can be maintained

**Additional context**
None, btw since not sure if kube-vip support as of today have raised above request. If this is already supported would like to have some reference for the same.

**Comment by thebsdbox** [comment]
Are you wanting to expose multiple load-balancer addresses on multiple interfaces?

**Comment by workhorse2020** [comment]
> Are you wanting to expose multiple load-balancer addresses on multiple interfaces?

Basically for calico we have given 3 interfaces and with 3 masters we want to make all the 3 interface ip's floating and yes they are LoadBalancer IP's.. Hence you are right on the same..

**Comment by QuinnBast** [comment]
I also have this requirement.

Two network interfaces exist on each machine in the cluster. I need one network to have one VIP and the other network to have another.

**Comment by lubronzhan** [comment]
You can have different kube-vip living togetther with differnet `--leaseName`, but the problem is they can't tell the difference of vips on the service type lb. now the `loadbalancer-ips` annotation can only support specifying single ip.

**Comment by QuinnBast** [comment]
Just as a follow up -- I was able to successfully setup two kube-VIPs in one cluster where each VIP is in control of one interface (and one IP per interface).

I am using the Daemonset deployment and what I had to do was update the generated manifest a little bit:

1. Ensure that you have two unique names for kube-vip. Change `kube-vip-ds` so that each file is different. For me, I replaced `ds` with the name of my network interface.
2. Ensure that only one of them is managing the control plane (not sure if this is nessecary or not).
3. Set the `prometheus_server` ports to not clash:

I used one on 2112 and one on 2113:
```
- name: prometheus_server
   value: :2112
```

4. Manually add the following line to set the lease names to be different in each deployment of kube-vip (as @lubronzhan suggested above):
```
- name: svc_leasename
  value: "vip-<yourInterfaceName>"
```

This last step is not documented anywhere yet but is in the [source code here](https://github.com/kube-vip/kube-vip/blob/063cc2fb8d76301d910e755fb2527761c038a193/pkg/kubevip/config_envvar.go#L139-L140). However, that this only got added 2 months ago and thus you have to be [using v0.6.3 (or later) to be able to make use of this feature](https://github.com/kube-vip/kube-vip/pull/622).

Once setup, I could specify Loadbalancer services for both IPs and both services were available, and the IPs would be bound to the network interface specified when the particular machine held the kubernetes lease (verified that `ip a` interface has the IP bound)

**Comment by QuinnBast** [comment]
After further investigation, this does not work.

One of the pods for my interface says:

```
Re-applying the VIP configuration [192.168.191.26] to the interface [enp24s0f0]"
Re-applying the VIP configuration [192.168.191.27] to the interface [enp24s0f0]"
```

Even though that pod is only configured to manage one of the IPs, not both....

**Comment by thebsdbox** [comment]
This appears to be fixed using the `lb_class_name`.

**Comment by QuinnBast** [comment]
Sorry - I see this has been resolved but I actually don't think that things worked after I performed testing with the answer I posted above.

We ended up having to use MetalLB using their [AdvancedL2Configuration](https://metallb.universe.tf/configuration/_advanced_l2_configuration/) which offers more control over L2 Advertisements and AddressPools.

Our MetalLB configuration ended up looking like this, but without deploying N kube-vips, one for each NIC, I don't think this is possible to do in kube-vip.

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ens3f0
spec:
  addresses:
    - <IpAddressOne>/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ens3f0-advertiser
spec:
  ipAddressPools:
    - ens3f0
  interfaces:
    - ens3f0
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ens3f1
spec:
  addresses:
    - <IpAddressTwo>/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ens3f1-advertiser
spec:
  ipAddressPools:
    - ens3f1
  interfaces:
    - ens3f1
```
