### ISSUE TITLE
Deploy kube-vip outside of kubernetes

### ISSUE THREAD

**Issue by debMan** [kube-vip/kube-vip#190]
Hi, dear kube-vip team. Thanks to combining load balancing and VIP in a single tool.

### Experienced problems
I think deploying VIP inside of the Kubernetes cluster is a little wrong in logic. 
I've deployed it with `docker-compose` on my edge servers. Also, used my VIP as the control-plane-endpoint of the cluster.
In some cases two prorblems occurred:
1. In case of kube-vip members fail (more than half+1 number of members), the kube-vip cluster crashes and fail to select leader due to insufficient votes, although some nodes are running. Subsequently, my Kubernetes apiservers pods will fail due to time out. Although all masters of k8s are available, with no VIP, they all fail and load balanced endpoints port which is 6443 get disappeared.
It would be better the `kube-vip` **still be available even with one healthy node**.
For example, in the following `vip.yml` config, by failing 3 of 5 nodes, the VIP and subsequently the k8s cluster will crash:
``` yaml
# VIP configurations
# ----------------
localPeer:
  id: prod-20
  address: 192.168.10.20
  port: 20000
remotePeers:
- id: prod-5
  address: 192.168.10.5
  port: 20000
- id: prod-3
  address: 192.168.10.3
  port: 20000
- id: prod-2
  address: 192.168.10.2
  port: 20000
- id: prod-21
  address: 192.168.10.21
  port: 20000
# [...]
vip: 192.168.10.100
gratuitousARP: true
singleNode: false
startAsLeader: false
interface: eno2

# Downstream load balanced services configurations
# ----------------
loadBalancers:
- name: API Server Load Balancer
  type: tcp
  port: 64432
  bindToVip: true
  # Add ALL bacends
  backends:
  - port: 6443
    address: 192.168.10.5
  - port: 6443
    address: 192.168.10.2
  - port: 6443
    address: 192.168.10.3
  - port: 6443
    address: 192.168.10.20
  - port: 6443
    address: 192.168.10.21
```
And the `docker-compose.yml`:
``` yaml
version: "2.1"
services:
  kube-vip:
    image: plndr/kube-vip:0.1.1
    container_name: kube-vip
    entrypoint:
      - /kube-vip
      - start
      - -c
      - /vip.yaml
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    restart: always
    volumes:
      - ${PWD}/vip.yaml:/vip.yaml
```
2. By crashing a node that has setting `startAsLeader` as `true` for itself, one of the other nodes will be selected as the leader. It is correct up to here, but if this node comes up back, started as a leader and we will see two nodes having the same VIP! So, I've set `startAsLeader` as `false` on all `kube-vip` cluster nodes.

### Suggestion
- Propose a mechanism to voting through healthy nodes, **not** all nodes.
- Checking for existence of a leader before initializing a node that has `startAsLeader: true` 

### More info
I've faced these problems in `kube-vip` version `0.1.1`. Also, the reason for not tending updates to newer versions is complexity and lack of some documents for my use case. So, I've decided to not use the latest version.
