### ISSUE TITLE
TCP and UDP together

### ISSUE THREAD

**Issue by kferrone** [kube-vip/kube-vip#191]
**Is your feature request related to a problem? Please describe.**
Doesn't seem to be able to make an LB with TCP and UDP. 

**Describe the solution you'd like**
Basically do what MetalLb does with an annotations like so:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: syslog-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: syslog-shared
spec:
  type: LoadBalancer
  ports:
    - name: udp-port
      port: 514
      targetPort: 514
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: syslog-shared
spec:
  type: LoadBalancer
  ports:
  - name: tcp-port
    port: 601
    targetPort: 601
    protocol: TCP
```
