### ISSUE TITLE
The service type is load balancer andthe external-ip is always pending

### ISSUE THREAD

**Issue by 24sama** [kube-vip/kube-vip#221]
**Describe the bug**
I deploy kube-vip by static pod in 3 master nodes. Then I deploy a service and set up the type `LoadBalancer`. But the external-ip is always pending.

**To Reproduce**
I get svc `kubectl get svc`:
```
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP      10.233.0.1     <none>        443/TCP        16h
nginx        LoadBalancer   10.233.28.24   <pending>     80:30453/TCP   13m
```

The log `kubectl logs -n kube-system kube-vip-cloud-provider-0 -f` is:
```
I0622 06:14:41.883720       1 loadBalancer.go:149] syncing service 'nginx' (3e8b8179-7c42-4b18-baf4-a084e0c15106)
I0622 06:14:41.883749       1 loadBalancer.go:229] No cidr config for namespace [default] exists in key [cidr-default] configmap [kubevip]
I0622 06:14:41.883757       1 loadBalancer.go:234] Taking address from [cidr-global] pool
I0622 06:14:41.883772       1 loadBalancer.go:190] Updating service [nginx], with load balancer IPAM address [192.168.0.202]
E0622 06:14:41.889473       1 controller.go:275] error processing service default/nginx (will retry): failed to ensure load balancer: Error updating Service Spec [nginx] : Operation cannot be fulfilled on services "nginx": the object has been modified; please apply your changes to the latest version and try again
I0622 06:14:41.889802       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: Error updating Service Spec [nginx] : Operation cannot be fulfilled on services \"nginx\": the object has been modified; please apply your changes to the latest version and try again"
I0622 06:14:46.889745       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0622 06:14:46.906133       1 loadBalancer.go:149] syncing service 'nginx' (3e8b8179-7c42-4b18-baf4-a084e0c15106)
I0622 06:14:46.906168       1 loadBalancer.go:229] No cidr config for namespace [default] exists in key [cidr-default] configmap [kubevip]
I0622 06:14:46.906175       1 loadBalancer.go:234] Taking address from [cidr-global] pool
I0622 06:14:46.906188       1 loadBalancer.go:190] Updating service [nginx], with load balancer IPAM address [192.168.0.202]
I0622 06:14:46.919746       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
```

The event `kubectl describe svc nginx` is:

```
Events:
  Type     Reason                  Age                From                Message
  ----     ------                  ----               ----                -------
  Warning  SyncLoadBalancerFailed  12m                service-controller  Error syncing load balancer: failed to ensure load balancer: Error updating Service Spec [nginx] : Operation cannot be fulfilled on services "nginx": the object has been modified; please apply your changes to the latest version and try again
  Normal   EnsuringLoadBalancer    12m (x2 over 12m)  service-controller  Ensuring load balancer
  Normal   LoadbalancerIP          12m                service-controller  -> 192.168.0.202
  Normal   EnsuredLoadBalancer     12m                service-controller  Ensured load balance
```

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Centos7.9]
 - Kubernetes Version: [e.g. v.1.20.4]
 - Kube-vip Version: [e.g. v0.3.5]

node1 192.168.0.6 master
node1 192.168.0.7 master
node1 192.168.0.8 master
node1 192.168.0.9 node
control-plone 192.168.0.240

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kubevip
  namespace: kube-system
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: eth0
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.0.240
    image: plndr/kube-vip:v0.3.5
    imagePullPolicy: Always
    name: kubevip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

The configmap is: 
```
apiVersion: v1
data:
  cidr-global: 192.168.0.200/30
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-21T14:16:17Z"
  name: kubevip
  namespace: kube-system
  resourceVersion: "173124"
  uid: 90977376-5417-46af-88a1-c183841649cb

```

**Additional context**

**Comment by thebsdbox** [comment]
Can you get the logs from Kube-vip pods? They are the ones that will set the actual status of the load balancer service.

**Comment by 24sama** [comment]
ok, here is:
kubevip-node1:
```
time="2021-06-22T07:42:22Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
time="2021-06-22T07:42:25Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
time="2021-06-22T07:42:28Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
time="2021-06-22T07:42:31Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
time="2021-06-22T07:42:34Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
time="2021-06-22T07:42:37Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
time="2021-06-22T07:42:40Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
time="2021-06-22T07:42:43Z" level=info msg="Broadcasting ARP update for 192.168.0.240 (52:54:9e:92:33:59) via eth0"
```

kubevip-node2:
```
time="2021-06-21T14:11:41Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [node2]"
I0621 14:11:41.619502       1 leaderelection.go:243] attempting to acquire leader lease  kube-system/plndr-cp-lock...
time="2021-06-21T14:11:41Z" level=info msg="Node [node1] is assuming leadership of the cluster"
```

**Comment by thebsdbox** [comment]
For whatever reason it looks like it's not watching services. Can you restart kube-Vip to get the status/mode it has started in along with logs around the time a service is created.

**Comment by shraderdm** [comment]
I actually encountered this same bug a few days ago. @thebsdbox happy to sync up and replicate this to help troubleshoot.

**Comment by thebsdbox** [comment]
Hmm, So this is the same as #225 .. The change to allow kube-vip to reclaim the addresses if it's on a suspended VM has introduced a race condition!

**Comment by thebsdbox** [comment]
Thanks @shraderdm I need more logs as to why the kube-vip pods aren't watching the kubernetes services..

**Comment by vinayus** [comment]
We need to check mostly kube-vip pod logs which can point specific issue of why its failing. Due to ARP messages, older logs have to be checked from the initial point.

I used below changes to overcome this case because I encountered missing roles.

And I'm currently on 1.19 k8s if that matters.

```
[atom@vinay140 ~]$ kubectl describe svc -n atom haproxy-service-gw-lb
Name:                     haproxy-service-gw-lb
Namespace:                atom
Labels:                   app.kubernetes.io/managed-by=Helm
Annotations:              meta.helm.sh/release-name: haproxy-gw
                          meta.helm.sh/release-namespace: atom
Selector:                 run=haproxy-ingress-gw
Type:                     LoadBalancer
IP:                       10.106.238.59
IP:                       172.16.23.149
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  32065/TCP
Endpoints:                10.200.24.5:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                From                Message
  ----     ------                  ----               ----                -------
  Warning  SyncLoadBalancerFailed  47m                service-controller  Error syncing load balancer: failed to ensure load balancer: Error updating Service Spec [haproxy-service-gw-lb] : Operation cannot be fulfilled on services "haproxy-service-gw-lb": the object has been modified; please apply your changes to the latest version and try again
  Normal   EnsuringLoadBalancer    47m (x2 over 47m)  service-controller  Ensuring load balancer
  Normal   LoadbalancerIP          47m                service-controller  -> 172.16.23.149
  Normal   EnsuredLoadBalancer     47m                service-controller  Ensured load balancer
```

But infact the pending issue was resolved by adding certain cluster roles because I did observe below logs

```
time="2021-07-14T07:43:32Z" level=info msg="Service [haproxy-service-gw-lb] has been addded/modified, it has an assigned external addresses [172.16.23.149]"
time="2021-07-14T07:43:32Z" level=debug msg="[STARTING] Service Sync"
time="2021-07-14T07:43:32Z" level=info msg="New VIP [172.16.23.149] for [haproxy-service-gw-lb/c72841de-c573-4933-950f-59245af1d338] "
time="2021-07-14T07:43:32Z" level=info msg="Starting advertising address [172.16.23.149] with kube-vip"
time="2021-07-14T07:43:33Z" level=info msg="Started Load Balancer and Virtual IP"
time="2021-07-14T07:43:33Z" level=info msg="Broadcasting ARP update for 172.16.23.149 (00:50:56:8a:ef:9a) via ens160"
time="2021-07-14T07:43:33Z" level=error msg="Error updating Service [haproxy-service-gw-lb] Status: services \"haproxy-service-gw-lb\" is forbidden: User \"system:serviceaccount:kube-system:kube-vip\" cannot update resource \"services/status\" in API group \"\" in the namespace \"atom\""
time="2021-07-14T07:43:33Z" level=debug msg="[COMPLETE] Service Sync"
```

Here are my updated yaml files incase it helps

```
[atom@vinay140 scripts]$ cat kubevip.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "put"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints","events","services/status", "leases"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes", "services"]
    verbs: ["list","get","watch","update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kube-vip
  name: kube-vip
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-vip
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-vip
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - kube-vip
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: plndr/kube-vip:v0.3.5
        imagePullPolicy: Always
        name: kube-vip
        command:
        - /kube-vip
        - service
        env:
          - name: vip_interface
            value: "ens160"
          - name: vip_arp
            value: "true"
          - name: vip_loglevel
            value: "5"
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      hostNetwork: true
      serviceAccountName: kube-vip
status: {}
```


and respective cloud controller yaml is here

```
[atom@vinay140 scripts]$ cat kubevip-controller.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-cloud-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-cloud-controller-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "put"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints","events","services/status", "leases"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes", "services"]
    verbs: ["list","get","watch","update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-cloud-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-cloud-controller-role
subjects:
- kind: ServiceAccount
  name: kube-vip-cloud-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  serviceName: kube-vip-cloud-provider
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-vip
      component: kube-vip-cloud-provider
  template:
    metadata:
      labels:
        app: kube-vip
        component: kube-vip-cloud-provider
    spec:
      containers:
      - command:
        - /kube-vip-cloud-provider
        - --leader-elect-resource-name=kube-vip-cloud-controller
        image: kubevip/kube-vip-cloud-provider:0.1
        name: kube-vip-cloud-provider
        imagePullPolicy: Always
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: kube-vip-cloud-controller
```
Intentionally keeping the roles and sa seperately for now.

Not sure if this helps, sorry for long post.
