### ISSUE TITLE
kubeadm init failed when following the doc

### ISSUE THREAD

**Issue by fengye87** [kube-vip/kube-vip#224]
**Describe the bug**
I was following the [doc](https://kube-vip.io/hybrid/) to deploy a HA cluster with kube-vip. But it failed at the first node when doing `kubeadm init` with the following output from the kube-vip pod:

```
E0629 07:34:57.803799       1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io plndr-cp-lock)
```

My cluster infra info:

| Node | Role | IP |
| ---- | ---- | -- |
| VIP | | 192.168.28.165 |
| k8s-vip-1 | controlplane | 192.168.26.216 |
| k8s-vip-2 | controlplane | 192.168.28.160 |
| k8s-vip-3 | controlplane | 192.168.28.168 |
| k8s-vip-4 | | 192.168.28.167 |

Commands I used:

```shell
# install containerd
# install kubeadm & kubelet
alias kube-vip="ctr run --rm --net-host docker.io/plndr/kube-vip:0.3.1 vip /kube-vip"
export VIP=192.168.28.165
export INTERFACE=eth0
kube-vip manifest pod \
    --interface $INTERFACE \
    --vip $VIP \
    --controlplane \
    --services \
    --arp \
    --leaderElection | tee /etc/kubernetes/manifests/kube-vip.yaml
kubeadm init --control-plane-endpoint $VIP --upload-certs
```

**Environment (please complete the following information):**
 - OS/Distro: CentOS-7
 - Kubernetes Version: v1.21
 - Kube-vip Version: v0.3.1

**`Kube-vip.yaml`:**

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: eth0
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.28.165
    image: plndr/kube-vip:0.3.1
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

What I can confirm is:

- The kube-apiserver is up and running, and I can `curl -k https://localhost:6443` from the first node, which would get a 403 response
- I've added line `192.168.26.216 k8s-vip-1` to `/etc/hosts`, but it looks like not being passed to the kube-vip pod?

I'm not sure what's the k8s api address is kube-vip using for leader election. Any help please? Thanks!
