### ISSUE TITLE
Loss of connectivity after etcd node dies

### ISSUE THREAD

**Issue by jhughes2112** [kube-vip/kube-vip#246]
Twice this week, I had a failure that prevented my kubectl from reaching the "control-nodes" over the VIP, but I could change the .kube/config to point to a specific node name and it worked fine.

**Steps to reproduce the behavior:**
1. Configure a 3-node k8s control node setup.
2. Trash the etcd database somehow (mine just corrupted on its own, then refused to start again, in a 5-minute crash loop).
3. Maybe wait?  I noticed a few hours later my sites were all down.
4. On the failing etcd node, kube-vip will show errors stating "error retrieving resource lock", because etcd is down.
5. On the other nodes, I don't think there's any errors... lost the log on the one that owned the VIP at the time.  Sorry.
6. Try to contact the cluster with kubectl over the VIP.  Mine did not respond whatsoever.  On every machine, `arp -a` showed the MAC address hadn't moved and `tcpdump` showed traffic flowing over that IP address to the correct machine.  It just did not respond on port 6443 anymore.
7. Restart the etcd pod by deleting the /var/lib/etcd/* contents that was trashed.  Note, the VIP still doesn't respond even after etcd is back and running.
8. Restart kube-vip on the node that was hosting the VIP.  Suddenly everything pops back up again.  Other nodes don't need to be restarted.

**Expected behavior**
When ETCD has a hiccup and one of the nodes is unable to communicate (over etcd?), keep serving 6443.  Do not get stuck in that state forever, even when ETCD comes back up.

**Environment (please complete the following information):**
 - OS/Distro: 3x Ubuntu 20.04 
 - Kubernetes Version: 1.20.4
 - Kube-vip Version: 0.3.2

**`Kube-vip.yaml`:**
Launch command: `sudo docker run --network host --rm plndr/kube-vip:0.3.2 manifest pod --interface $EXTINTERFACE --vip 10.0.0.251 --arp --controlplane --leaderElection --lbEnable | tee kube-vip.yaml`
Yaml:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: eno1
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: lb_enable
      value: "true"
    - name: lb_backendport
      value: "6443"
    - name: lb_name
      value: Kubeadm Load Balancer
    - name: lb_type
      value: tcp
    - name: lb_bindtovip
      value: "true"
    - name: vip_address
      value: 10.0.0.251
    image: plndr/kube-vip:0.3.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

Curious, how does the leader election happen, and how do the nodes know about all the other control nodes?  Does it poll that from the local etcd, or some other way?  Is this inherently a problem with how kube-vip communicates with nodes, or do I have something configured wrong?

Thanks!
