### ISSUE TITLE
Kubeadm init stucks in wait-control-plane

### ISSUE THREAD

**Issue by rwanito** [kube-vip/kube-vip#251]
HI!

I'm trying to install kube-vip in a fresh kubeadm install.

I'm using last kubeadm version and containerd as CRI.
I use a private registry that is secured by my certificate.
All the kubeadm nodes know the certificate.

I've used kube-vip alias to create my /etc/kubernetes/manifest/kube-vip.yaml file.

The command is :
```bash
kube-vip manifest pod --interface eth0 --address MYADDR --controlplane --service --leaderElection
```
A only change the path of the image cause of my registry.

I have another file kubeadm.conf.yml
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.2
dns:
  imageRepository: repo...
imageRepository: repo...
controlPlaneEndPoint: "MYVIP"
networking:
  podSubnet: "192.168.0.0/16"

```

At this moment I use this command to init : 
```bash
kubeadm init --upload-certs --config kubeadm.conf.yml  --v=10
```

I haven't any warnings.
But it stucks : 
```
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static pods from directory /etc/kubernetes/manifests.
```
It loops onto a curl test in the VIP address.

It seems to be an error of pulling but I don't know.
When I try : `sudo crictl --runtime-endpoint /run/containerd/containerd.sock images`
Kubevip doesn't appear.

How can I debug that ?
Thanks for your work.

**Comment by thebsdbox** [comment]
It looks like you've not enabled `--arp` or `--bgp` so kube-vip wont be advertising the control-plane address

**Comment by rwanito** [comment]
Sorry, I haven't copy/paste this part.
But, arp is in;

```yaml
apiVersion: v1

kind: Pod

metadata:

  creationTimestamp: null

  name: kube-vip

  namespace: kube-system

spec:

  containers:

  - args:

    - manager

    env:

    - name: vip_arp

      value: "true"

    - name: vip_interface

      value: eth0

    - name: port

      value: "6443"

    - name: vip_cidr

      value: "32"

    - name: cp_enable

      value: "true"

    - name: cp_namespace

      value: kube-system

    - name: vip_ddns

      value: "false"

    - name: svc_enable

      value: "true"

    - name: vip_leaderelection

      value: "true"

    - name: vip_leaseduration

      value: "4"

    - name: vip_renewdeadline

      value: "2"

    - name: vip_retryperiod

      value: "1"

    - name: address

      value: MYVIP

    image: registry.domaine.com/miroirs/docker.io/plndr/kube-vip:v0.3.7

    imagePullPolicy: Always

    name: kube-vip

    resources: {}

    securityContext:

      capabilities:

        add:

        - NET_ADMIN

        - NET_RAW

        - SYS_TIME

    volumeMounts:

    - mountPath: /etc/kubernetes/admin.conf

      name: kubeconfig

  hostNetwork: true

  volumes:

  - hostPath:

      path: /etc/kubernetes/admin.conf

    name: kubeconfig

status: {}
```
There is a debug mod while kubeadm init or how can I debug kube-vip while this init ?
Thanks for your help !
