### ISSUE TITLE
Equinix Metal BGP peer routing issue when using a BGP password

### ISSUE THREAD

**Issue by enkelprifti98** [kube-vip/kube-vip#256]
**Describe the bug**
There seems to be an issue with kube-vip not being able to reach BGP peers on Equinix Metal when using a BGP password.

**To Reproduce**
1. Enable Equinix Metal project BGP with a BGP password.
2. Deploy a k8s cluster with kubeadm
3. Deploy CPEM and define kube-vip as the load balancer integration: https://github.com/equinix/cloud-provider-equinix-metal
3. Deploy kube-vip v0.3.7 with debug level 5.
4. Expose a service of type LoadBalancer
5. Kube-vip logs will show the following route errors:

```
time="2021-08-19T16:35:37Z" level=debug msg="try to connect" Key=169.254.255.1 Topic=Peer
time="2021-08-19T16:35:37Z" level=debug msg="try to connect" Key=169.254.255.2 Topic=Peer
time="2021-08-19T16:35:41Z" level=debug msg="failed to connect: dial tcp 0.0.0.0:0->169.254.255.1:179: i/o timeout" Key=169.254.255.1 Topic=Peer
time="2021-08-19T16:35:41Z" level=debug msg="failed to connect: dial tcp 0.0.0.0:0->169.254.255.2:179: i/o timeout" Key=169.254.255.2 Topic=Peer
time="2021-08-19T16:35:58Z" level=debug msg="try to connect" Key=169.254.255.1 Topic=Peer
time="2021-08-19T16:35:59Z" level=debug msg="try to connect" Key=169.254.255.2 Topic=Peer
time="2021-08-19T16:35:59Z" level=debug msg="failed to connect: dial tcp 0.0.0.0:0->169.254.255.2:179: connect: no route to host" Key=169.254.255.2 Topic=Peer
time="2021-08-19T16:36:07Z" level=debug msg="failed to connect: dial tcp 0.0.0.0:0->169.254.255.1:179: i/o timeout" Key=169.254.255.1 Topic=Peer
time="2021-08-19T16:36:12Z" level=debug msg="try to connect" Key=169.254.255.2 Topic=Peer
time="2021-08-19T16:36:12Z" level=debug msg="failed to connect: dial tcp 0.0.0.0:0->169.254.255.2:179: connect: no route to host" Key=169.254.255.2 Topic=Peer
time="2021-08-19T16:36:21Z" level=debug msg="try to connect" Key=169.254.255.1 Topic=Peer
time="2021-08-19T16:36:21Z" level=debug msg="failed to connect: dial tcp 0.0.0.0:0->169.254.255.1:179: connect: no route to host" Key=169.254.255.1 Topic=Peer
```

**Expected behavior**
BGP peering established.

**Screenshots**
Logs shown above.

**Environment:**
 - OS/Distro: [Ubuntu 20.04]
 - Kubernetes Version: [v.1.22.0]
 - Kube-vip Version: [v0.3.7]

**`Kube-vip.yaml`:**

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: vip_interface
          value: lo
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: svc_enable
          value: "true"
        - name: vip_startleader
          value: "false"
        - name: vip_addpeerstolb
          value: "true"
        - name: vip_localpeer
          value: controller-node:1.2.3.4:10000
        - name: annotation
          value: metal.equinix.com
        - name: bgp_enable
          value: "true"
        - name: bgp_routerid
        - name: bgp_as
          value: "65000"
        - name: bgp_peeraddress
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "65000"
        - name: vip_address
        - name: vip_loglevel
          value: "5"
        image: plndr/kube-vip:v0.3.7
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
This issue happens on older kube-vip releases as well. I tried kube-vip v0.3.3 and v0.3.7.
