### ISSUE TITLE
Disabling the primary k3s master node results in kube api becoming unreachable.

### ISSUE THREAD

**Issue by onedr0p** [kube-vip/kube-vip#260]
**Describe the bug**

Hi 👋🏼 I am having an issue when I turn off or stop the k3s systemd service on my primary master node I can no longer access Kubernetes via kubectl.

My env:

```
❯ k get nodes -o wide
NAME    STATUS   ROLES                       AGE   VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
k8s-0   Ready    control-plane,etcd,master   65d   v1.21.4+k3s1   192.168.42.10   <none>        Ubuntu 21.04   5.11.0-31-generic   containerd://1.4.9-k3s1
k8s-1   Ready    control-plane,etcd,master   65d   v1.21.4+k3s1   192.168.42.11   <none>        Ubuntu 21.04   5.11.0-31-generic   containerd://1.4.9-k3s1
k8s-2   Ready    control-plane,etcd,master   65d   v1.21.4+k3s1   192.168.42.12   <none>        Ubuntu 21.04   5.11.0-31-generic   containerd://1.4.9-k3s1
k8s-3   Ready    worker                      65d   v1.21.4+k3s1   192.168.42.13   <none>        Ubuntu 21.04   5.11.0-31-generic   containerd://1.4.9-k3s1
k8s-4   Ready    worker                      65d   v1.21.4+k3s1   192.168.42.14   <none>        Ubuntu 21.04   5.11.0-31-generic   containerd://1.4.9-k3s1
k8s-5   Ready    worker                      65d   v1.21.4+k3s1   192.168.42.15   <none>        Ubuntu 21.04   5.11.0-31-generic   containerd://1.4.9-k3s1
```

- k3s version `v1.21.4+k3s1`
- Calico configured in BGP for services
- BGP configured on Opnsense (and confirmed worked with Calico)

**Expected behavior**

When I disable k3s or shutdown the node for `k8s-0` shouldld still be able to access the kube API.

**Other Environment:**
 - OS/Distro: `Ubuntu 21.04`
 - Kubernetes Version: `v1.21.4+k3s1`
 - Kube-vip Version: `v0.3.7`
 - Opnsense: `21.7.1-amd64`

**`Kube-vip.yaml`:**

```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/name: kube-vip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-vip
      app.kubernetes.io/name: kube-vip
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kube-vip
        app.kubernetes.io/name: kube-vip
    spec:
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.3.7
          imagePullPolicy: IfNotPresent
          args:
            - manager
          env:
            - name: vip_arp
              value: "false"
            - name: vip_interface
              value: lo
            - name: port
              value: "6443"
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: vip_startleader
              value: "false"
            - name: vip_loglevel
              value: "5"
            - name: bgp_enable
              value: "true"
            - name: bgp_routerinterface
              value: "eno1"
            - name: bgp_as
              value: "64512"
            - name: bgp_peeraddress
              value: "192.168.42.1"
            - name: bgp_peeras
              value: "64512"
            - name: vip_address
              value: "192.168.69.5"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services", "services/status", "nodes"]
    verbs: ["list", "get", "watch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
  - kind: ServiceAccount
    name: kube-vip
    namespace: kube-system

```

**Additional context**

I am curious that if because opnsense does not support ECMP in the Kernel (yet), is this causing my issue?

**Comment by thebsdbox** [comment]
Very odd.. What is being displayed from the router side of things. Also is there anything interesting in the kube-vip pods?

**Comment by onedr0p** [comment]
I can see the routes in my router:

```
# sho ip bgp
...
*=i192.168.69.5/32  192.168.42.12                 100      0 i
*=i                 192.168.42.11                 100      0 i
*>i                 192.168.42.10                 100      0 i
...
```

As for kube-vip logs, there isn't much coming thru when I disable my `k8s-0` node. Logs look to only contain a lot of this:

```
time="2021-08-23T12:42:34Z" level=debug msg=sent Key=192.168.42.1 State=BGP_FSM_ESTABLISHED Topic=Peer data="&{{[] 19 4} 0x2bd4b70}"
time="2021-08-23T12:43:04Z" level=debug msg=sent Key=192.168.42.1 State=BGP_FSM_ESTABLISHED Topic=Peer data="&{{[] 19 4} 0x2bd4b70}"
time="2021-08-23T12:43:34Z" level=debug msg=sent Key=192.168.42.1 State=BGP_FSM_ESTABLISHED Topic=Peer data="&{{[] 19 4} 0x2bd4b70}"
time="2021-08-23T12:44:04Z" level=debug msg=sent Key=192.168.42.1 State=BGP_FSM_ESTABLISHED Topic=Peer data="&{{[] 19 4} 0x2bd4b70}"
time="2021-08-23T12:44:34Z" level=debug msg=sent Key=192.168.42.1 State=BGP_FSM_ESTABLISHED Topic=Peer data="&{{[] 19 4} 0x2bd4b70}"
time="2021-08-23T12:45:04Z" level=debug msg=sent Key=192.168.42.1 State=BGP_FSM_ESTABLISHED Topic=Peer data="&{{[] 19 4} 0x2bd4b70}"
```

**Comment by thebsdbox** [comment]
hmm, when you "break" your node0 is the kube-vip pod being killed? 
Is the vip pingable? and does a traceroute tell you where the traffic is going, finally can you test connecting to 6443 on the other control plane nodes that should also be peering with the router.

**Comment by onedr0p** [comment]
> hmm, when you "break" your node0 is the kube-vip pod being killed?

It doesn't appear so... maybe that is the issue. I am surprised it's not unless that is intended.

```
kube-vip-jk96t                                  1/1     Running     4          30d
kube-vip-kdg8x                                  1/1     Running     4          30d
kube-vip-r9vhx                                  1/1     Running     5          30d
```

> Is the vip pingable?

Yes

```
❯ ping 192.168.69.5
PING 192.168.69.5 (192.168.69.5): 56 data bytes
64 bytes from 192.168.69.5: icmp_seq=0 ttl=63 time=2.188 ms
64 bytes from 192.168.69.5: icmp_seq=1 ttl=63 time=8.662 ms
64 bytes from 192.168.69.5: icmp_seq=2 ttl=63 time=2.195 ms
```

> and does a traceroute tell you where the traffic is going

```
❯ traceroute 192.168.69.5
traceroute to 192.168.69.5 (192.168.69.5), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  1.808 ms  1.900 ms  2.117 ms
 2  192.168.69.5 (192.168.69.5)  1.931 ms  1.844 ms  1.739 ms
```

> finally can you test connecting to 6443 on the other control plane nodes that should also be peering with the router.

Yes this is working fine, from `k8s-1`:

```
ubuntu@k8s-1:~$ sudo k3s kubectl get nodes
NAME    STATUS     ROLES                       AGE   VERSION
k8s-0   NotReady   control-plane,etcd,master   65d   v1.21.4+k3s1
k8s-1   Ready      control-plane,etcd,master   65d   v1.21.4+k3s1
k8s-2   Ready      control-plane,etcd,master   65d   v1.21.4+k3s1
k8s-3   Ready      worker                      65d   v1.21.4+k3s1
k8s-4   Ready      worker                      65d   v1.21.4+k3s1
k8s-5   Ready      worker                      65d   v1.21.4+k3s1
```

**Comment by thebsdbox** [comment]
Ah ok.. well if the kube-vip pod is running on the dead node but it is still participating in the peering then we could be routing traffic to where the api-server is no longer running. I don't understand how the kube-vip pod is still up if kubernetes/kubelet is down on the node in question though.

**Comment by onedr0p** [comment]
While it says it's `Ready` with `kubectl get po` I am seeing the following in `sudo k3s kubectl ds/kube-vip -n kube-system -o yaml`

```
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 1
  numberReady: 2
  observedGeneration: 3
  updatedNumberScheduled: 2
```
