### ISSUE TITLE
After Successful Cluster setup, got an error and kube-vip pod restarting

### ISSUE THREAD

**Issue by shahabio** [kube-vip/kube-vip#271]
**Describe the bug**
I have setup a k3s (3 node master cluster) with kube-vip and successfully virtualized an IP address of 172.20.15.100;
but after about 1 hour, all the kube-vip pods which be deployed to the master nodes, got an error and restarts about every 1 hour which my VIP node changes.

**Screenshots**

```
E0910 03:12:42.921380       1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://controller-node2:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": context deadline exceeded
I0910 03:12:42.921700       1 leaderelection.go:278] failed to renew lease kube-system/plndr-cp-lock: timed out waiting for the condition
E0910 03:12:42.921864       1 leaderelection.go:298] Failed to release lock: resource name may not be empty
time="2021-09-10T03:12:42Z" level=info msg="This node is becoming a follower within the cluster"
time="2021-09-10T03:12:42Z" level=fatal msg="lost leadership, restarting kube-vip"
```

```
NAMESPACE     NAME                                                         READY   STATUS    RESTARTS   AGE   IP              NODE               NOMINATED NODE   READINESS GATES
kube-system   pod/coredns-7448499f4d-hl7bj                                 1/1     Running   4          39h   10.42.0.10      controller-node1   <none>           <none>
kube-system   pod/kube-vip-ds-lqd4h                                        1/1     Running   47         39h   172.20.15.112   controller-node3   <none>           <none>
kube-system   pod/kube-vip-ds-tl6sr                                        1/1     Running   50         39h   172.20.15.111   controller-node2   <none>           <none>
kube-system   pod/kube-vip-ds-wvc6c                                        1/1     Running   55         39h   172.20.15.110   controller-node1   <none>           <none>
kube-system   pod/metrics-server-86cbb8457f-7tbt7                          1/1     Running   4          39h   10.42.0.11      controller-node1   <none>           <none>
monitoring    pod/alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   0          37h   10.42.3.10      agent-node1        <none>           <none>
monitoring    pod/alertmanager-prometheus-kube-prometheus-alertmanager-1   2/2     Running   0          37h   10.42.5.9       agent-node3        <none>           <none>
monitoring    pod/alertmanager-prometheus-kube-prometheus-alertmanager-2   2/2     Running   0          37h   10.42.3.11      agent-node1        <none>           <none>
monitoring    pod/prometheus-grafana-6cbd5c4995-z4867                      2/2     Running   0          37h   10.42.4.7       agent-node2        <none>           <none>
monitoring    pod/prometheus-kube-prometheus-operator-85c8b795-wwxn6       1/1     Running   0          37h   10.42.5.6       agent-node3        <none>           <none>
monitoring    pod/prometheus-kube-state-metrics-76f66976cb-x9sq8           1/1     Running   0          37h   10.42.3.7       agent-node1        <none>           <none>
monitoring    pod/prometheus-prometheus-kube-prometheus-prometheus-0       2/2     Running   0          37h   10.42.4.10      agent-node2        <none>           <none>
monitoring    pod/prometheus-prometheus-kube-prometheus-prometheus-1       2/2     Running   0          37h   10.42.5.11      agent-node3        <none>           <none>
monitoring    pod/prometheus-prometheus-kube-prometheus-prometheus-2       2/2     Running   0          37h   10.42.4.11      agent-node2        <none>           <none>
monitoring    pod/prometheus-prometheus-node-exporter-hjqff                1/1     Running   0          37h   172.20.15.116   agent-node3        <none>           <none>
monitoring    pod/prometheus-prometheus-node-exporter-k8wx6                1/1     Running   0          37h   172.20.15.114   agent-node1        <none>           <none>
monitoring    pod/prometheus-prometheus-node-exporter-r6ssq                1/1     Running   3          37h   172.20.15.112   controller-node3   <none>           <none>
monitoring    pod/prometheus-prometheus-node-exporter-vkxsb                1/1     Running   0          37h   172.20.15.115   agent-node2        <none>           <none>
monitoring    pod/prometheus-prometheus-node-exporter-x9tkk                1/1     Running   3          37h   172.20.15.111   controller-node2   <none>           <none>
monitoring    pod/prometheus-prometheus-node-exporter-xrzzw                1/1     Running   3          37h   172.20.15.110   controller-node1   <none>           <none>
storage       pod/openebs-admission-server-7dd88c6b6-62294                 1/1     Running   0          37h   10.42.5.5       agent-node3        <none>           <none>
storage       pod/openebs-apiserver-786478c689-b2smd                       1/1     Running   4          37h   10.42.4.4       agent-node2        <none>           <none>
storage       pod/openebs-localpv-provisioner-c8676d88b-cqlcq              1/1     Running   22         37h   10.42.4.5       agent-node2        <none>           <none>
storage       pod/openebs-ndm-86j7f                                        1/1     Running   0          37h   172.20.15.116   agent-node3        <none>           <none>
storage       pod/openebs-ndm-operator-f8458bbc6-cqrfj                     1/1     Running   0          37h   10.42.5.4       agent-node3        <none>           <none>
storage       pod/openebs-ndm-whq54                                        1/1     Running   0          37h   172.20.15.115   agent-node2        <none>           <none>
storage       pod/openebs-ndm-zvgqf                                        1/1     Running   0          37h   172.20.15.114   agent-node1        <none>           <none>
storage       pod/openebs-provisioner-5c6db88f85-2jhtg                     1/1     Running   20         37h   10.42.4.6       agent-node2        <none>           <none>
storage       pod/openebs-snapshot-operator-5559695b4-fvllh                2/2     Running   14         37h   10.42.3.5       agent-node1        <none>           <none>
```

**Environment (please complete the following information):**
 - OS/Distro: [Ubuntu 20.04.2]
 - Kubernetes Version: [v.1.21]
 - Kube-vip Version: [0.8]

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: enp1s0
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 172.20.15.100
        image: plndr/kube-vip:v0.3.8
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: CriticalAddonsOnly
        operator: Exists

  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
