### ISSUE TITLE
ARP does not stop when a new leader is elected.

### ISSUE THREAD

**Issue by JumpMaster** [kube-vip/kube-vip#277]
**Describe the bug**
During quick elections (only a few seconds apart) multiple nodes can become the master.  A node correctly logs that another node has become the master but it continues to act as a master and send ARP requests.

**To Reproduce**
Unable to reproduce on demand but this is happening to me 1-3 times per week on a six node cluster.  Three masters and three workers.

**Expected behavior**
Upon quick master elections only the final elected node should remain the master.

**Screenshots**
These logs are taken from node kubemaster3.
```
time="2021-09-30T06:21:56Z" level=info msg="new leader elected: kubemaster1"
time="2021-09-30T06:21:56Z" level=info msg="Node [kubemaster1] is assuming leadership of the cluster"
I0930 13:28:30.949902       1 leaderelection.go:253] successfully acquired lease kube-system/plndr-cp-lock
time="2021-09-30T13:28:30Z" level=info msg="This node is starting with leadership of the cluster"
time="2021-09-30T13:28:30Z" level=info msg="Node [kubemaster3] is assuming leadership of the cluster"
time="2021-09-30T13:28:30Z" level=info msg="Broadcasting ARP update for 192.168.0.100 (52:54:00:d4:04:50) via enp1s0"
time="2021-09-30T13:28:33Z" level=info msg="Broadcasting ARP update for 192.168.0.100 (52:54:00:d4:04:50) via enp1s0"
time="2021-09-30T13:28:37Z" level=info msg="Broadcasting ARP update for 192.168.0.100 (52:54:00:d4:04:50) via enp1s0"
time="2021-09-30T13:28:37Z" level=info msg="new leader elected: kubemaster2"
time="2021-09-30T13:28:40Z" level=info msg="Broadcasting ARP update for 192.168.0.100 (52:54:00:d4:04:50) via enp1s0"
time="2021-09-30T13:28:43Z" level=info msg="Broadcasting ARP update for 192.168.0.100 (52:54:00:d4:04:50) via enp1s0"
...
```

**Environment (please complete the following information):**
 - OS/Distro: Debian 10
 - Kubernetes Version: 1.21.5
 - Kube-vip Version: v0.3.8

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: enp1s0
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.0.100
    image: ghcr.io/kube-vip/kube-vip:v0.3.8
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
**Additional context**
Happy to help with any further troubleshooting step.
