### ISSUE TITLE
kube-vip LB issuing same IP to multiple services 

### ISSUE THREAD

**Issue by damjankumin** [kube-vip/kube-vip#283]
**Describe the bug**
I deployed kube-vip ver. 0.3.8 to the RKE2 cluster. I deployed kube-vip-cloud-provider. I configured 8 IPs to be used for the LB.
Now after I deployed several services and assigned LB to them, I noticed, that the two different services got same LB IP - though I must admit, that one uses HTTP and other HTTPS. 

**To Reproduce**
1. deployed RKE2 cluster
2. deployed cilium 
3. deployed kube-vip
4. deployed several services
5. 
**Expected behavior**
I would imagined that the LB IP would be reserved for one service only.

**Screenshots**
No screenshots but the code of output of kubectl:
```
admin@mgmt:~$ kubectl get svc --all-namespaces | grep LoadBalancer
cattle-system              rancher-lb                                    LoadBalancer   10.43.96.203    192.168.2.244   443:31174/TCP                  2d21h
default                    keycloak                                      LoadBalancer   10.43.166.12    192.168.2.248   80:31347/TCP,443:31827/TCP     6m6s
default                    testlink                                      LoadBalancer   10.43.187.139   192.168.2.245   80:30359/TCP,443:30677/TCP     10m
default                    tomcat                                        LoadBalancer   10.43.12.96     192.168.2.244   80:32470/TCP                   8m28s
kube-system                traefik                                       LoadBalancer   10.43.156.201   192.168.2.242   80:32403/TCP,443:31808/TCP     2d20h
```

**Environment (please complete the following information):**
 - OS/Distro: ubuntu 20.04 LTS 3 as VM on Proxmox 7
 - Kubernetes Version: v1.21.5+rke2r2
 - Kube-vip Version: 0.3.8

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: ens18
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.2.241
        image: ghcr.io/kube-vip/kube-vip:v0.3.8
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
