### ISSUE TITLE
[0.4.0] Cannot create a new kubeadm cluster with kube-vip static pod and Control Plane Load-Balancing  enabled

### ISSUE THREAD

**Issue by alloran** [kube-vip/kube-vip#309]
**Describe the bug**
I'm testing the new Control Plane Load-Balancing feature.

The first time the kubelet of the first controlplne node starts, the kube-vip starts and creates the ipvs virtual-service without any real-server enabled before the kubelet joins the cluster, the api vip becomes unavailable and the cluster init fails.

**To Reproduce**
1. Generate kubevip manifest and place it to /etc/kubernetes/manifests/kube-vip.yaml
2. Run kubeadm init
3. Watch kubeadm output and kubelet logs 

**Expected behavior**
Cluster init succeeded

**Screenshots**
-

**Environment (please complete the following information):**
 - OS/Distro:  Ubuntu 1804
 - Kubernetes Version: 1.20.2
 - Kube-vip Version: 0.4.0

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: br0
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name : lb_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.100.10
    image: ghcr.io/kube-vip/kube-vip:v0.4.0
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**
vip ip : 192.168.100.10
controlplane node ips: 192.168.100.11 192.168.100.12 192.168.100.13

kubelet error:
```
Nov 10 19:11:21 adm-vm-k8s-test-lab-master01 kubelet[12647]: E1110 19:11:21.635973   12647 kubelet_node_status.go:93] Unable to register node "adm-vm-k8s-test-lab-master01" with API server: Post "https://192.168.100.10:6443/api/v1/nodes": dial tcp 192.168.100.10:6443: connect: connection refused

```
ipvsadm output
```
~#ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.168.100.10:6443 rr
< no real-servers here >
```

Maybe kube-vip should add local apiserver endpoint right after lb initialization regardless of controlplane node availability events.
Or there should be a 40-60s timeout before creating the virtual-service if there is no node registered (so the api vip address would be reachable without ipvs).
