### ISSUE TITLE
Unexpected end of JSON input when cleaning up LoadBalancer

### ISSUE THREAD

**Issue by chipzoller** [kube-vip/kube-vip#312]
**Describe the bug**
Deleting a Service of type `LoadBalancer` created before a cloud provider range has been created throws this error continually. The delete request is hung.

**To Reproduce**
1. Create a Service of type `LoadBalancer`
2. See that your dumb ass forgot to create an IP range for it to consume.
3. Create the range in the `kubevip` ConfigMap
4. See the IP does not get set.
5. Delete the Service
6. See in the logs a message similar to

```log
E1121 23:51:31.385882       1 controller.go:275] error processing service default/busybox-svc (will retry): failed to check if load balancer exists before cleanup: unexpected end of JSON input
I1121 23:51:31.386204       1 event.go:291] "Event occurred" object="default/busybox-svc" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to check if load balancer exists before cleanup: unexpected end of JSON input"
```

**Expected behavior**
The Service is deleted.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 1804
 - Kubernetes Version: 1.22.4
 - Kube-vip Version: 0.4.0

**`Kube-vip.yaml`:**

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens160
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.1.140
    image: ghcr.io/kube-vip/kube-vip:v0.4.0
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**kubevip ConfigMap:**

```yaml
apiVersion: v1
data:
  range-global: 192.168.1.125-192.168.1.129
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
```

**Additional context**
