### ISSUE TITLE
issues binding to loopback on v0.4.0

### ISSUE THREAD

**Issue by jr0dd** [kube-vip/kube-vip#322]
As of v0.4.0 the VIP will not bind to the lo interface. Rolling back to v0.3.9 fixes for now.

**logs**
```
k8s-0-nas ~ % k logs -n kube-system kube-vip-nvv7n
time="2021-11-27T18:36:39Z" level=info msg="server started"
time="2021-11-27T18:36:39Z" level=info msg="Starting Kube-vip Manager with the BGP engine"
time="2021-11-27T18:36:39Z" level=info msg="Namespace [kube-system], Hybrid mode [false]"
time="2021-11-27T18:36:39Z" level=info msg="Starting the BGP server to advertise VIP routes to BGP peers"
time="2021-11-27T18:36:39Z" level=info msg="Add a peer configuration for:10.10.0.1" Topic=Peer
time="2021-11-27T18:36:39Z" level=info msg="starting the DNS updater for the address k8s.domain.tld"
time="2021-11-27T18:36:39Z" level=info msg="setting 10.10.5.5 as an IP"
time="2021-11-27T18:36:42Z" level=info msg="stop ipUpdater"
```` 

**Environment (please complete the following information):**
 - OS/Distro: [Ubuntu 21.04]
 - Kubernetes Version: [v1.22.3+k3s1]
 - Kube-vip Version: [0.4.0]

**`Kube-vip.yaml`:**
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip
  template:
    metadata:
      labels:
        name: kube-vip
    spec:
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.3.9
          imagePullPolicy: IfNotPresent
          args:
            - manager
          env:
            - name: address
              value: "k8s.domain.tld"
            - name: vip_arp
              value: "false"
            - name: vip_interface
              value: "lo"
            - name: port
              value: "6443"
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: vip_ddns
              value: "false"
            - name: svc_enable
              value: "false"
            - name: bgp_enable
              value: "true"
            - name: bgp_source_ip
              value: 10.10.0.200
            - name: bgp_as
              value: "64512"
            - name: bgp_routerinterface
              value: "eno0"
            - name: bgp_peeraddress
              value: 10.10.0.1
            - name: bgp_peeras
              value: "64512"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
      hostNetwork: true
      hostAliases:
        - hostnames:
            - kubernetes
          ip: 127.0.0.1
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
```

**Additional context**
