### ISSUE TITLE
vip_cidr ignored, always 32

### ISSUE THREAD

**Issue by psi-4ward** [kube-vip/kube-vip#324]
kube-vip v0.4.0

```yaml
containers:
        - name: kube-vip
          image: 'ghcr.io/kube-vip/kube-vip:v0.4.0'
          args:
            - manager
          env:
            - name: vip_arp
              value: 'true'
            - name: port
              value: '6443'
            - name: vip_interface
              value: enp35s0.4000
            - name: vip_cidr
              value: '29'
            - name: svc_enable
              value: 'true'
```

```
kubectl describe configmap -n kube-system kubevip
Name:         kubevip
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
range-global:
----
321.321.321.218-321.321.321.222
Events:  <none>
```

```
ip addr show enp35s0.4000
3: enp35s0.4000@enp35s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP
    inet 321.321.321.221/32 scope global enp35s0.4000
       valid_lft forever preferred_lft forever
```

Can anyone tell me what to do to have `/29` assigned?
Thx.
