### ISSUE TITLE
unable to provision ddns based cluster

### ISSUE THREAD

**Issue by sadysnaat** [kube-vip/kube-vip#328]
**Describe the bug**

**To Reproduce**
try provsioning an ddns based cluster

kube-vip pod crashes
```bash
root@ds-ddns-mm-cluster-cp-hk6nz:~# crictl logs -f 69903653959ce
time="2021-12-13T10:00:55Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2021-12-13T10:00:55Z" level=info msg="kube-vip will bind to interface [eth0]"
time="2021-12-13T10:00:55Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2021-12-13T10:00:55Z" level=info msg="Namespace [kube-system], Hybrid mode [false]"
time="2021-12-13T10:00:55Z" level=info msg="server started"
time="2021-12-13T10:00:55Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [ds-ddns-mm-cluster-cp-hk6nz]"
I1213 10:00:55.546248       1 leaderelection.go:248] attempting to acquire leader lease kube-system/plndr-cp-lock...
I1213 10:00:55.561558       1 leaderelection.go:258] successfully acquired lease kube-system/plndr-cp-lock
time="2021-12-13T10:00:55Z" level=info msg="Node [ds-ddns-mm-cluster-cp-hk6nz] is assuming leadership of the cluster"
time="2021-12-13T10:00:55Z" level=info msg="waiting for ip from dhcp"
time="2021-12-13T10:01:55Z" level=error msg="failed to get IP from dhcp for ddns in 1 minutes"
time="2021-12-13T10:01:55Z" level=info msg="starting the DNS updater for the address ds-ddns-mm-cluster-cn22.spectrocloud.local"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa754a1]

goroutine 38 [running]:
github.com/vishvananda/netlink.(*Handle).addrHandle(0x2914a50, 0x1d91a48, 0xc000120c60, 0x0, 0xc000411d60, 0x30, 0x30)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210330154013-f5de75959ad5/addr_linux.go:78 +0x61
github.com/vishvananda/netlink.(*Handle).AddrReplace(0x2914a50, 0x1d91a48, 0xc000120c60, 0x0, 0x1dc0130, 0xc0001c9100)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210330154013-f5de75959ad5/addr_linux.go:53 +0xb7
github.com/vishvananda/netlink.AddrReplace(...)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210330154013-f5de75959ad5/addr_linux.go:42
github.com/kube-vip/kube-vip/pkg/vip.(*network).AddIP(0xc000484400, 0x1dc0130, 0xc0001c9100)
        /src/pkg/vip/address.go:97 +0x51
github.com/kube-vip/kube-vip/pkg/cluster.(*Cluster).vipService(0xc00022fec0, 0x1dc0130, 0xc0001c90c0, 0x1dc0130, 0xc0001c9100, 0x2920480, 0xc000256e60, 0x0, 0x0, 0x1000000, ...)
        /src/pkg/cluster/service.go:49 +0x192
github.com/kube-vip/kube-vip/pkg/cluster.(*Cluster).StartCluster.func3(0x1dc0130, 0xc0001c9240)
        /src/pkg/cluster/clusterLeaderElection.go:194 +0x85
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
        /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/leaderelection/leaderelection.go:211 +0x11b
root@ds-ddns-mm-cluster-cp-hk6nz:~# cat /etc/kubernetes/manifests/kube-vip.yaml
```

happening as due to refactor ddns did not start dhcpclient and request didn't have Hostname option to get a valid ddns entry

**Expected behavior**

Expected nodes to able to get an ddns entry 

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1804] Ubuntu 1804
 - Kubernetes Version: [e.g. v.1.18] v1.20.0
 - Kube-vip Version: [e.g. 0.2.3] v0.4.0

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)
```yaml
root@ds-ddns-mm-cluster-cp-hk6nz:~# cat /etc/kubernetes/manifests/kube-vip.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_ddns
      value: "true"
    - name: vip_arp
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: address
      value: "<ddnsaddress>"
    - name: port
      value: "6443"
    - name:  vip_leaseduration
      value: "15"
    - name:  vip_renewdeadline
      value: "10"
    - name:  vip_retryperiod
      value: "2"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    image: gcr.io/spectro-images-public/release/kube-vip/kube-vip:0.4.0
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```
**Additional context**
