### ISSUE TITLE
0.4.1 has issues bringing up interface on lo

### ISSUE THREAD

**Issue by cprivite** [kube-vip/kube-vip#342]
**Describe the bug**
As of 0.4.1, it no longer detects the localhost interface correctly on my test servers (c2.medium.x86 on Equinix Metal). 

Error message:
time="2021-12-22T19:22:26Z" level=fatal msg="lo is not valid interface, reason: lo is not up"

```
ip a output:
root@k8s-cluster1-pool1-cp1:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp65s0f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether 40:a6:b7:74:7a:a0 brd ff:ff:ff:ff:ff:ff
3: enp65s0f1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether 40:a6:b7:74:7a:a0 brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 40:a6:b7:74:7a:a0 brd ff:ff:ff:ff:ff:ff
    inet 145.XX.XX.X/31 brd 255.255.255.255 scope global bond0
       valid_lft forever preferred_lft forever
    inet 10.XX.XX.X/31 brd 255.255.255.255 scope global bond0:0
       valid_lft forever preferred_lft forever
    inet6 2604::1/127 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::0/64 scope link
       valid_lft forever preferred_lft forever
```

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: 1.23.1
 - Kube-vip Version: 0.4.1

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "false"
    - name: port
      value: "6443"
    - name: vip_interface
      value: lo
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_packet
      value: "true"
    - name: vip_packetproject
    - name: vip_packetprojectid
      value: ""
    - name: PACKET_AUTH_TOKEN
      value: ""
    - name: bgp_enable
      value: "true"
    - name: vip_address
      value: ""
    image: ghcr.io/kube-vip/kube-vip:v0.4.1
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**
