### ISSUE TITLE
Cannot update status when service is recreated with a different external IP

### ISSUE THREAD

**Issue by xprt64** [kube-vip/kube-vip#368]
**Describe the bug**
When a service of type LoadBalancer is recreated (deleted then created again) the kube-vip-ds cannot update service status due to an update conflict.

**To Reproduce**
1. Create a service of type LoadBalancer with `loadBalancerIP` set. For example: 

```
apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: apache-php
    status: online
  loadBalancerIP: "10.6.0.121"
  ports:
    - name: http
      port: 30047
      protocol: TCP
      targetPort: 10080
    - name: https
      port: 30048
      protocol: TCP
      targetPort: 10443
```
The service gets the external IP from kube-vip as expected.
2. Delete the service: `kubectl delete service web-lb`
3. Repeat step 1 but with a different IP:
```
apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: apache-php
    status: online
  loadBalancerIP: "10.6.0.122"
  ports:
    - name: http
      port: 30047
      protocol: TCP
      targetPort: 10080
    - name: https
      port: 30048
      protocol: TCP
      targetPort: 10443
```

The service will not get an external IP.

**Expected behavior**
The service should get the IP `10.6.0.122`. Instead, the EXTERNAL-IP is in `<pending>` state and it remains that way.

```
$ kubectl get services
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                           AGE
web-lb                 LoadBalancer   10.108.149.17    <pending>     30047:32281/TCP,30048:31178/TCP   72s
```

The logs from `kube-vip-ds`:
```
time="2022-02-26T19:37:28Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"
time="2022-02-26T19:37:31Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"
time="2022-02-26T19:37:34Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"
time="2022-02-26T19:37:37Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"
time="2022-02-26T19:37:40Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"
time="2022-02-26T19:37:44Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"
time="2022-02-26T19:37:44Z" level=info msg="Service [web-lb] has been added/modified, it has an assigned external addresses [10.6.0.121]"
time="2022-02-26T19:37:44Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2022-02-26T19:37:44Z" level=info msg="[VIP] Releasing the Virtual IP [10.6.0.121]"
time="2022-02-26T19:37:44Z" level=info msg=Stopped
time="2022-02-26T19:37:44Z" level=info msg="Removed [daa29bc9-51f7-4d06-b3b4-e8903a8362d1] from manager, [0] advertised services remain"
time="2022-02-26T19:37:44Z" level=info msg="Service [web-lb] has been deleted"
time="2022-02-26T19:37:47Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"
time="2022-02-26T19:37:48Z" level=info msg="Service [web-lb] has been added/modified, it has an assigned external addresses [10.6.0.122]"
time="2022-02-26T19:37:48Z" level=info msg="New VIP [10.6.0.122] for [web-lb/c689d438-5582-498f-9081-a88de0f2dcc9] "
time="2022-02-26T19:37:48Z" level=info msg="Starting advertising address [10.6.0.122] with kube-vip"
time="2022-02-26T19:37:48Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-02-26T19:37:48Z" level=error msg="Error updating Service [web-lb] Status: Operation cannot be fulfilled on services \"web-lb\": the object has been modified; please apply your changes to the latest version and try again"
time="2022-02-26T19:37:48Z" level=info msg="Service [web-lb] has been added/modified, it has an assigned external addresses [10.6.0.122]"
time="2022-02-26T19:37:50Z" level=info msg="Broadcasting ARP update for 10.6.0.203 (00:1e:67:49:14:e2) via bond0"

```

The k8s status:
```
k get services
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                           AGE
web-lb                 LoadBalancer   10.98.107.43     <pending>     30047:30437/TCP,30048:32263/TCP   13s
```

**Environment (please complete the following information):**
 - OS/Distro: CentOS Linux 7 (Core)
 - Kubernetes Version: v1.23.1
 - Kube-vip Version: 0.4.2

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.4.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.4.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: bond0
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.6.0.203
        image: ghcr.io/kube-vip/kube-vip:v0.4.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

```

I made a PR for this #367 .
