### ISSUE TITLE
DHCP services leak interfaces

### ISSUE THREAD

**Issue by lewisdiamond** [kube-vip/kube-vip#377]
When exposing services using `--ip-load-balancer=0.0.0.0` to use DHCP, subsequent deletion of the service leaves the `vip-abcdef@eth0` device on the host.

DHCP does not work for me so the interface(s) don't have an IP assigned, which may trigger the issue.

**To Reproduce**
1. Expose a service using DHCP
2. Validate the service ip is still <pending> (might not be required)
3. List the interfaces on the host
5. Delete the service
6. List the interfaces on the host

**Expected behavior**
After deleting the service, the `vip-abcdef` interface should be removed

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: 1.21
 - Kube-vip Version: 0.4.2

**`Kube-vip.yaml`:**
```
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "true"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "15"
        - name: vip_renewdeadline
          value: "10"
        - name: vip_retryperiod
          value: "2"
        - name: address
          value: 10.220.220.1
        image: ghcr.io/kube-vip/kube-vip:v0.4.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
```

**Additional context**
