### ISSUE TITLE
Error Interface is not up in v0.4.2

### ISSUE THREAD

**Issue by claudio4** [kube-vip/kube-vip#385]
**Describe the bug**
Kube-vip refuses to start arguing that the interface is not up, but it is. Furthermore, doing exactly the same steps but using v0.4.0 instead of v0.4.2 works flawlessly.

**To Reproduce**
1. Create a manifest using `ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.4.2 vip /kube-vip manifest pod --interface ens33 --address 192.168.140.200 --controlplane --arp --leaderElection` and place it /etc/kubernetes/manifests/kube-vip.yaml
2. Init the cluster with `kubeadm init --config kubeadm-init.yml --upload-certs` (config file provided at the end of the issue)
3. When the installation fails check the container logs with `crictl --runtime-endpoint /run/containerd/containerd.sock logs CONTAINERID`

The log will show something like this
```
time="2022-03-29T07:59:55Z" level=fatal msg="ens33 is not valid interface, reason: ens33 is not up"
```
**Expected behavior**
I expect it to work normally, as it does with v0.4.0

**Environment (please complete the following information):**
 - OS/Distro: Flatcar 3033.2.4
 - Kubernetes Version: v1.23.5
 - Kube-vip Version: v0.4.2

**`Kube-vip.yaml`:**
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens33
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.140.200
    image: ghcr.io/kube-vip/kube-vip:v0.4.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
**` kubeadm-init.yml`:***
```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "192.168.140.200:6443"
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
```
**Extra context**
This looks similar to #360.

Thank you for this great application.
