### ISSUE TITLE
When kube-vip is in services mode using metal API and BGP, it brings up the CPEM-managed EIP for the cluster VIP on the worker nodes. 

### ISSUE THREAD

**Issue by cprivitere** [kube-vip/kube-vip#397]
**Describe the bug**
When kube-vip is in services mode using metal API and BGP, it brings up the CPEM-managed EIP for the cluster VIP on the worker nodes. 

**To Reproduce**
1. Deploy a CAPP cluster with the normal template.
2. Add CNI (used calico)
3. Set the CPEM up to load balance with kube-vip (kubectl edit deployment -n kube-system cloud-provider-equinix-metal and set METAL_LOAD_BALANCER to kube-vip://)
4. Install kube-vip in services mode:
```
kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
alias kube-vip="docker run --network host --rm ghcr.io/kube-vip/kube-vip:$KVVERSION"
export VIP=metal_EIP
export INTERFACE=lo
kube-vip manifest daemonset --interface $INTERFACE \
--services \
--inCluster \
--bgp \
--metal \
--provider-config /etc/cloud-sa/cloud-sa.json | kubectl apply -f -
```
5. Deploy demo app code:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "gcr.io/google-samples/hello-frontend:1.0"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    metal.equinix.com/eip-metro: "da"
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
```
6. Check on the kube-vip logs and notice the following message:
```
❯ kubectl logs -n kube-system kube-vip-ds-9z6zt
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```
7. Note the worker node has gone NotReady
```
❯ kubectl get nodes
NAME                            STATUS     ROLES                  AGE   VERSION
cluster-a-control-plane-bncv9   Ready      control-plane,master   54m   v1.23.6
cluster-a-worker-a-z2prg        NotReady   <none>                 50m   v1.23.6
```
8. Go on the node directly and capture log from the kube-vip pod (see below in screenshots section).
9. Check out the localhost interface of the worker node:
```
root@cluster-a-worker-a-z2prg:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 147.75.35.200/32 scope host lo
       valid_lft forever preferred_lft forever
    inet 147.75.55.162/32 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
<...>
```

**Expected behavior**
It would bring up everything EXCEPT the api-server VIP on the worker nodes.
**Screenshots**
Here's a log dump from the kube-vip pod on the worker:
```
root@cluster-a-worker-a-z2prg:~# crictl -r unix:///run/containerd/containerd.sock logs 675424cf49e7e
time="2022-05-23T17:28:31Z" level=info msg="Starting kube-vip.io [v0.4.4]"
time="2022-05-23T17:28:31Z" level=warning msg="the status of the interface lo is unknown. Ensure your interface is ready to accept traffic, if so you can safely ignore this message"
time="2022-05-23T17:28:31Z" level=info msg="server started"
time="2022-05-23T17:28:31Z" level=info msg="Starting Kube-vip Manager with the BGP engine"
time="2022-05-23T17:28:31Z" level=info msg="Namespace [kube-system], Hybrid mode [false]"
time="2022-05-23T17:28:31Z" level=info msg="Looking up the BGP configuration from packet"
time="2022-05-23T17:28:32Z" level=info msg="Starting the BGP server to advertise VIP routes to BGP peers"
time="2022-05-23T17:28:32Z" level=info msg="Add a peer configuration" Key=169.254.255.1 Topic=Peer
time="2022-05-23T17:28:32Z" level=info msg="Add a peer configuration" Key=169.254.255.2 Topic=Peer
time="2022-05-23T17:28:32Z" level=info msg="Beginning watching services for type: LoadBalancer in all namespaces"
2022/05/23 17:28:32 type:STATE  peer:{conf:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530}  state:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530  session_state:IDLE  router_id:"<nil>"}  transport:{local_address:"<nil>"}}
2022/05/23 17:28:32 type:STATE  peer:{conf:{local_asn:65000  neighbor_address:"169.254.255.2"  peer_asn:65530}  state:{local_asn:65000  neighbor_address:"169.254.255.2"  peer_asn:65530  session_state:IDLE  router_id:"<nil>"}  transport:{local_address:"<nil>"}}
2022/05/23 17:28:32 type:STATE  peer:{conf:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530}  state:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530  session_state:ACTIVE  router_id:"<nil>"}  transport:{local_address:"<nil>"}}
2022/05/23 17:28:32 type:STATE  peer:{conf:{local_asn:65000  neighbor_address:"169.254.255.2"  peer_asn:65530}  state:{local_asn:65000  neighbor_address:"169.254.255.2"  peer_asn:65530  session_state:ACTIVE  router_id:"<nil>"}  transport:{local_address:"<nil>"}}
time="2022-05-23T17:28:32Z" level=info msg="Service [calico-typha] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:28:32Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:28:32Z" level=info msg="add the service [kube-system/cloud-provider-equinix-metal-kubernetes-external] with external address 147.75.35.200"
time="2022-05-23T17:28:32Z" level=info msg="New VIP [147.75.35.200] for [kube-system/cloud-provider-equinix-metal-kubernetes-external] "
time="2022-05-23T17:28:32Z" level=info msg="Starting advertising address [147.75.35.200] with kube-vip"
time="2022-05-23T17:28:32Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-05-23T17:28:32Z" level=info msg="Service [calico-kube-controllers-metrics] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:28:32Z" level=info msg="Service [calico-api] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:28:32Z" level=info msg="Service [hello] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:28:32Z" level=info msg="Service [frontend] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:28:32Z" level=info msg="Service [kubernetes] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:28:32Z" level=info msg="Service [kube-dns] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:29:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:29:04Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:29:58Z" level=info msg="Service [frontend] has been added/modified it has an assigned external addresses []"
time="2022-05-23T17:30:00Z" level=info msg="Service [frontend] has been added/modified it has an assigned external addresses [147.75.55.162]"
time="2022-05-23T17:30:00Z" level=info msg="add the service [default/frontend] with external address 147.75.55.162"
time="2022-05-23T17:30:00Z" level=info msg="New VIP [147.75.55.162] for [default/frontend] "
time="2022-05-23T17:30:00Z" level=info msg="Starting advertising address [147.75.55.162] with kube-vip"
time="2022-05-23T17:30:00Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-05-23T17:30:00Z" level=error msg="Error updating Service Spec [frontend] : Operation cannot be fulfilled on services \"frontend\": the object has been modified; please apply your changes to the latest version and try again"
time="2022-05-23T17:30:00Z" level=info msg="Service [frontend] has been added/modified it has an assigned external addresses [147.75.55.162]"
time="2022-05-23T17:30:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:30:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:31:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:31:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:32:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:32:04Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:33:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:33:04Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:34:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:34:04Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:34:20Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:34:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:35:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:35:03Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:35:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:35:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:36:20Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:36:22Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:37:20Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:37:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:38:20Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:38:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:39:20Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:39:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:40:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:40:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:41:20Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:41:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:42:20Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
time="2022-05-23T17:42:21Z" level=info msg="Service [cloud-provider-equinix-metal-kubernetes-external] has been added/modified it has an assigned external addresses [147.75.35.200]"
```

**Environment (please complete the following information):**
 - OS/Distro: CAPP v0.5.0 deploying Ubuntu 20.04
 - Kubernetes Version: 1.23.6
 - Kube-vip Version: 0.4.4

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.4.4
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.4.4
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: lo
        - name: vip_cidr
          value: "32"
        - name: svc_enable
          value: "true"
        - name: provider_config
          value: /etc/cloud-sa/cloud-sa.json
        - name: vip_packet
          value: "true"
        - name: vip_packetproject
        - name: vip_packetprojectid
        - name: PACKET_AUTH_TOKEN
        - name: bgp_enable
          value: "true"
        - name: vip_address
        image: ghcr.io/kube-vip/kube-vip:v0.4.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /etc/cloud-sa
          name: cloud-sa-volume
          readOnly: true
      hostNetwork: true
      serviceAccountName: kube-vip
      volumes:
      - name: cloud-sa-volume
        secret:
          secretName: metal-cloud-config
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  ```

**Additional context**
In this case, 147.75.35.200 is the CPEM managed VIP address that kube-vip should ignore.
