### ISSUE TITLE
calico BGP模式 与 kube-vip BGP模式问题

### ISSUE THREAD

**Issue by wangxg422** [kube-vip/kube-vip#398]
使用kube-vip作为k3s集群高可用的VIP技术，采用BGP模式，CNI选择calico，模式选择BGP。但是部署完成后集群网络有问题，
非同一主机的PodIp ping不通，主机没有其余主机上PodIp的路由。
使用calicoctl查看node结果如下：
```
root@server1:/home/paas/kube-vip# calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-----------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |            INFO             |
+---------------+-------------------+-------+----------+-----------------------------+
| 192.168.64.70 | node-to-node mesh | up    | 09:24:47 | Established                 |
| 192.168.64.50 | node-to-node mesh | start | 14:05:51 | Idle BGP Error: Bad peer AS |
| 192.168.64.60 | node-to-node mesh | start | 14:05:49 | Idle BGP Error: Bad peer AS |
+---------------+-------------------+-------+----------+-----------------------------+

IPv6 BGP status
No IPv6 peers found.
```
calico node 日志：
```
bird: BGP: Unexpected connect from unknown address 192.168.64.40 (port 47183)
```
这是kube-vip生成daemonset的命令：
```
kube-vip manifest daemonset \
    --interface $INTERFACE \
    --address $VIP \
    --inCluster \
    --taint \
    --controlplane \
    --services \
    --bgp \
    --localAS 65000 \
    --bgpRouterID 192.168.0.2 \
    --bgppeers 192.168.0.10:65000::false,192.168.0.11:65000::false | tee kube-vip-ds.yaml
```
生成的文件如下：
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.4.4
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.4.4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: lo
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: bgp_enable
          value: "true"
        - name: bgp_routerid
        - name: bgp_routerinterface
          value: "enp6s0"
        - name: bgp_as
          value: "65000"
        - name: bgp_peeraddress
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "65000"
        - name: bgp_peers
          value: 192.168.64.40:65000::false,192.168.64.50:65000::false,192.168.64.60:65000::false
        - name: address
          value: 192.168.64.30
        image: ghcr.io/kube-vip/kube-vip:v0.4.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
请问该调整哪里呢？
