### ISSUE TITLE
LoadBalancer IPs duplicated across namespaces when issued from global range

### ISSUE THREAD

**Issue by bossmonkeyman** [kube-vip/kube-vip#400]
**Describe the bug**
LoadBalancer IP addresses are only unique within a given namespace when using the cloud provider and range-global config. The same IPs are repeated from the range for services in a different namespace.

**To Reproduce**
1. Install the cloud provider and create a config map using **range-global**. For example, 10.0.10.51-10.0.10.100.
2. Deploy the first LoadBalancer service to namespace-1. It is assigned an IP of 10.0.10.51.
3. Deploy a second LoadBalancer service to namespace-1. It is assigned an IP of 10.0.10.52.
4. Deploy a LoadBalancer service to namespace-2. It is assigned a duplicate IP of 10.0.10.51.
5. Deploy a second LoadBalancer service to namespace-2. It is assigned another duplicate IP of 10.0.10.52.

**Expected behavior**
IP addresses from the global range should be assigned only once across the entire cluster.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: 1.23.6 (K3s)
 - Kube-vip Version: 0.4.4

**`Kube-vip.yaml`:**
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-cloud-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-cloud-controller-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "put"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints","events","services/status", "leases"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes", "services"]
    verbs: ["list","get","watch","update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-cloud-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-cloud-controller-role
subjects:
- kind: ServiceAccount
  name: kube-vip-cloud-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  serviceName: kube-vip-cloud-provider
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-vip
      component: kube-vip-cloud-provider
  template:
    metadata:
      labels:
        app: kube-vip
        component: kube-vip-cloud-provider
    spec:
      containers:
      - command:
        - /kube-vip-cloud-provider
        - --leader-elect-resource-name=kube-vip-cloud-controller
        image: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.2
        name: kube-vip-cloud-provider
        imagePullPolicy: Always
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: kube-vip-cloud-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
data:
  range-global: 10.0.10.51-10.0.10.100
```
