### ISSUE TITLE
Link not found en0

### ISSUE THREAD

**Issue by ddiawara** [kube-vip/kube-vip#418]
**Describe the bug**
Im work on MACOS : i don't have eth0 on mac

alias kube-vip='docker run --network host --rm ghcr.io/kube-vip/kube-vip:$KVVERSION'
kube-vip manifest daemonset --services --inCluster --arp --interface en0 | kubectl apply -f -

````
time="2022-07-01T22:37:33Z" level=info msg="Starting kube-vip.io [v0.4.4]"                                │
│ time="2022-07-01T22:37:33Z" level=fatal msg="kind is not valid interface, reason: get en0 failed, error: │
│ Stream closed EOF for kube-system/kube-vip-ds-7shln (kube-vip)
````

````
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: eth0 <============ [ I DON'T KNOW WHAT OS THE VALUE FOR MACOS]
    - name: vip_address
````

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: [MACOS 12.4]
 - Kubernetes Version: [v.1.22]
 - Kube-vip Version: [0.4.4]

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)

**Additional context**
