### ISSUE TITLE
kube-vip Cloud Provider doesn't work on any pods at worker nodes

### ISSUE THREAD

**Issue by roccqqck** [kube-vip/kube-vip#424]
**Describe the bug**
kube-vip Cloud Provider doesn't work on any pods at worker nodes.

But if the pods are at master nodes, it works.

```
kubectl get pods -A -o wide
```
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS      AGE   IP               NODE       NOMINATED NODE   READINESS GATES
default       nginx-558db87554-fbf9b                                  1/1     Running     0             28m   10.42.2.9        kworker1   <none>           <none>
kube-system   kube-vip-cloud-provider-0                               1/1     Running     0             11m     10.42.2.4        kworker1   <none>           <none>
kube-system   kube-vip-ds-52q75                                       1/1     Running     0             34m     192.168.56.101   kmaster1   <none>           <none>
kube-system   kube-vip-ds-h6rff                                       1/1     Running     0             29m     192.168.56.102   kmaster2   <none>           <none>
kube-system   rke2-ingress-nginx-controller-fqsp2                     1/1     Running     0             24m     192.168.56.201   kworker1   <none>           <none>
kube-system   rke2-ingress-nginx-controller-jl6cb                     1/1     Running     0             39m     192.168.56.101   kmaster1   <none>           <none>
kube-system   rke2-ingress-nginx-controller-q5tm2                     1/1     Running     0             28m     192.168.56.102   kmaster2   <none>           <none>
```
```
kubectl get svc -A
```
```
NAMESPACE     NAME                                      TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
default       nginx                                     LoadBalancer   10.43.91.173    192.168.56.120   80:30551/TCP                 41s
kube-system   rke2-ingress-nginx-controller             LoadBalancer   10.43.229.69    192.168.56.110   80:31955/TCP,443:31215/TCP   17m
```

I cannot curl my nginx  EXTERNAL-IP
```
curl -v http://192.168.56.120
```
```
*   Trying 192.168.56.120:80...
```

But I can ping nginx EXTERNAL-IP
```
ping 192.168.56.120
```
```
64 bytes from 192.168.56.120: icmp_seq=0 ttl=64 time=0.055 ms
64 bytes from 192.168.56.120: icmp_seq=1 ttl=64 time=0.094 ms
```

But I can curl my ingress EXTERNAL-IP 192.168.56.110

Then I tried to deploy nginx to master nodes.

I curl nginx EXTERNAL-IP successfully.

**Environment (please complete the following information):**
 - OS/Distro: [Ubuntu 2004]
 - Kubernetes Version: [rke2 v.1.23]
 - Kube-vip Version: [0.4.4]
 - kube-vip-cloud-provider:v0.0.2

**`kube-vip-cloud-provider.yaml`:**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-cloud-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-cloud-controller-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "put"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints","events","services/status", "leases"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes", "services"]
    verbs: ["list","get","watch","update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-cloud-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-cloud-controller-role
subjects:
- kind: ServiceAccount
  name: kube-vip-cloud-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  serviceName: kube-vip-cloud-provider
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-vip
      component: kube-vip-cloud-provider
  template:
    metadata:
      labels:
        app: kube-vip
        component: kube-vip-cloud-provider
    spec:
      containers:
      - command:
        - /kube-vip-cloud-provider
        - --leader-elect-resource-name=kube-vip-cloud-controller
        image: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.2
        name: kube-vip-cloud-provider
        imagePullPolicy: Always
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: kube-vip-cloud-controller
```
