### ISSUE TITLE
kube-vip v0.5.0 - some strange issues in

### ISSUE THREAD

**Issue by BBQigniter** [kube-vip/kube-vip#429]
I love kube-vip but sometimes I saw strange effects. I tried to recreate a few of the constellations I had seen. For testing I use a 3-node kubernetes cluster with a few workloads where I create loadbalanced services.

## Preparations

open several terminals with 

* `watch -n1 'ip ad | grep 10.115.199'`
* `watch -n1 'kubectl get service,daemonset,sts,lease,pod -A -o wide'`
* `kubectl logs -f -n kube-system --selector=app.kubernetes.io/name=kube-vip-ds --prefix`
* `kubectl logs -f -n kube-system --selector=app=kube-vip --prefix`

## Tests

* create service with IP
  * created service with IP 10.115.199.121 - IP popped up on interface of node 1
    * works: service behind IP is reachable
* create two additional services without VIP to check if VIP is not assigned twice (as this was fixed with cloud-provider 0.0.3)
  * works (!): but one service also uses IP 10.115.199.121 on node 1 the other service IP 10.115.199.122 node 2 - also had constellations where the already used IP popped up on a second node's interface
    * services behind IPs are reachable
* delete services and recreate services
  * delete
    * works (!): but leases stay and cannot be deleted manually as they are instantly recreated somehow
  * recreate
    * first recreate the two services with dynamic assignment
      * works: both IPs pop up on node 1
        * services reachable
    * add third service with static IP
      * works: no problems
* edit service with static IP and change it
  * changed IP of service with static configured
    * **FAILS**: service is not changing IP - kube-vip-ds detects change and logs indicate it is assigning the IP but nothing is happening
      * service still reachable via old IP had to delete service and reapply
* edit services to use same IP but different ports
  * works (!): but I had constellations where the IP was added to multiple nodes - kube-vip-ds logs indicate that there is some change that and that you should reapply to take effect (unfortunately I do not have the exact logs anymore)
    * services are reachable
* create services with same IP but different ports and with `externalTrafficPolicy: Local`
  * had to add `endpoints` to cluster-role first
    * `resources: ["services", "services/status", "nodes", "endpoints"]`
  * works (!!): IP hosted on node 1
    * one service that did not have pod on node 1 was unreachable
    * also I had some constellations where the `kube-vip-ds` crashlooped because of some reason - not sure anymore if it was because of missing `endpoints` cluster-role

So far it seems pretty useable even with those strange quirks if you keep to some workflow - like before changing an IP of a service, delete it first.

With `externalTrafficPolicy: Local` I had some super strange effects and couldn't really reproduce them - but this definitely needs more testing.

## The `kube-vip.yaml` I use

```
############################# KUBE-VIP ###############################
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.0
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.0
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_cidr
          value: "32"
        - name: svc_enable
          value: "true"
        - name: svc_election
          value: "true"
        - name: vip_address
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.5.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
  updateStrategy: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    # had to add endpoints to be able to use 'externalTrafficPolicy: Local'
    resources: ["services", "services/status", "nodes", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---
############################# CONTROLLER ###############################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  serviceName: kube-vip-cloud-provider
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-vip
      component: kube-vip-cloud-provider
  template:
    metadata:
      labels:
        app: kube-vip
        component: kube-vip-cloud-provider
    spec:
      containers:
      - command:
        - /kube-vip-cloud-provider
        - --leader-elect-resource-name=kube-vip-cloud-controller
        image: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.3
        name: kube-vip-cloud-provider
        imagePullPolicy: Always
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: kube-vip-cloud-controller
---
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: kubevip 
  namespace: kube-system 
data: 
  range-global: 10.115.199.121-10.115.199.125
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-cloud-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-cloud-controller-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "put"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints","events","services/status", "leases"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes", "services"]
    verbs: ["list","get","watch","update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-cloud-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-cloud-controller-role
subjects:
- kind: ServiceAccount
  name: kube-vip-cloud-controller
  namespace: kube-system
```
