### ISSUE TITLE
define preferred node where VIP should be hosted

### ISSUE THREAD

**Issue by BBQigniter** [kube-vip/kube-vip#430]
It would really be awesome to be able to define in a service-manifest where the VIP should preferably be hosted. What do I mean?

For example you have some workload that is always running on 3 kubernetes nodes, you then create a service e.g.

```
apiVersion: v1
kind: Service
metadata:
  name: some-service
  namespace: some-service
spec:
  ...
  type: LoadBalancer
  loadBalancerIP: "10.12.100.24"
```

But now this IP is only hosted on one of the k8s-nodes. But what if I create 2 additional services with additional `loadBalancerIP`s and a round robin DNS entry? The VIPs currently would probably all land on one node receiving all the traffic.

So I think it would be nice to have e.g. some `preferredNode: NODENAME` option. For example

```
apiVersion: v1
kind: Service
metadata:
  name: some-service-1
  namespace: some-service
spec:
  ...
  type: LoadBalancer
  preferredNode: node-1
  loadBalancerIP: "10.12.100.24"
---
apiVersion: v1
kind: Service
metadata:
  name: some-service-2
  namespace: some-service
spec:
  ...
  type: LoadBalancer
  preferredNode: node-2
  loadBalancerIP: "10.12.100.25"
---
apiVersion: v1
kind: Service
metadata:
  name: some-service-3
  namespace: some-service
spec:
  ...
  type: LoadBalancer
  preferredNode: node-3
  loadBalancerIP: "10.12.100.25"
```

With this, as long as node-1 is available the VIP should be hosted there. If the node goes down for some reason (e.g. maintenance) the VIP should just change to some still available node. 
As soon as the node and the workload is back online, the VIP should wander back to the preferred one. Like `keepalived` can do by defining the priority per node.

Or is there already some option I missed, that can achieve this?

**Comment by thebsdbox** [comment]
So it couldn't be part of the `spec` but it could certainly be an annotation. There is no mechanism for rebalancing things within Kubernetes.. it is the same with pods if you kill a bunch of nodes all pods will end up on the remaining nodes, you'll need to kill pods or re-deploy the service for things to spread out on the newly added nodes.

**Comment by BBQigniter** [comment]
I couldn't stop thinking about that this is currently not possible - and here I have a workaround script. In my case I need this for a statefulset with 3 replicas (or more pods per node - this is not yet tested with the script), where each pod is running on a separate node.

the pods are reachable via loadbalancer and local traffic-policy as I need the actual IPs of the hosts which are sending events to those pods. in the service-manifests I added an annotation which my watch-script will use

```
apiVersion: v1
kind: Service
metadata:
  name: logstash-buffer-0
  namespace: logstash-buffer
  labels:
    app: logstash-buffer
  annotations:
    kubeVipBalancePriority: "vkube-4, vkube-5, vkube-6"
spec:
  ports:
    - port: 514
      targetPort: 12345
      protocol: TCP
      name: syslog-tcp
    - port: 514
      targetPort: 12345
      protocol: UDP
      name: syslog-udp
  selector:
    app: logstash-buffer
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "10.115.199.122"
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-buffer-1
  namespace: logstash-buffer
  labels:
    app: logstash-buffer
  annotations:
    kubeVipBalancePriority: "vkube-5, vkube-6, vkube-4"
spec:
  ports:
    - port: 514
      targetPort: 12345
      protocol: TCP
      name: syslog-tcp
    - port: 514
      targetPort: 12345
      protocol: UDP
      name: syslog-udp
  selector:
    app: logstash-buffer
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "10.115.199.123"
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-buffer-2
  namespace: logstash-buffer
  labels:
    app: logstash-buffer
  annotations:
    kubeVipBalancePriority: "vkube-6, vkube-4, vkube-5"
spec:
  ports:
    - port: 514
      targetPort: 12345
      protocol: TCP
      name: syslog-tcp
    - port: 514
      targetPort: 12345
      protocol: UDP
      name: syslog-udp
  selector:
    app: logstash-buffer
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "10.115.199.124"
```

The watch-script looks like this - I'm currently still testing and probably I'm still missing some test-cases and other stuff :D and prolly I'm doing it rather complicated, but this is what I came up, and it seems to work

```
#!/usr/bin/env python3

from kubernetes import client, config, watch

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

v1_core = client.CoreV1Api()
v1_coordination = client.CoordinationV1Api()

w = watch.Watch()


def check_node_state(node_name):
    node_status = v1_core.read_node_status(node_name)
    node_conditions = node_status.status.conditions
    for condition in node_conditions:
        if condition.type == "Ready":
            return True
            break  # not really necessary
        # endif
    # endfor
    return False
# enddef


def check_container_state(pod_container_statuses):
    number_of_containers = len(pod_container_statuses)
    ready_containers = 0

    for container_status in pod_container_statuses:
        if container_status.ready:
            ready_containers += 1
        # endif
    # endfor

    if ready_containers == number_of_containers:
        return True
    else:
        return False
    # endif
# enddef


for item in w.stream(v1_core.list_pod_for_all_namespaces, timeout_seconds=0):
    balance_vip = False
    get_lease = False

    try:
        # first we get pods where we need the VIP balanced
        if bool(item['object'].metadata.annotations['kubeVipBalanceIP']):
            # print(item['object'])
            pod_name = item['object'].metadata.name
            try:
                pod_labels_app = item['object'].metadata.labels['app']
            except:
                pod_labels_app = None
                print("App-Label not set")
            # endtry

            if pod_labels_app is not None:
                pod_node_name = item['object'].spec.node_name
                pod_status_phase = item['object'].status.phase
                pod_container_statuses = item['object'].status.container_statuses
                namespace = item['object'].metadata.namespace
                print("Namespace %s - Pod: %s - App-Label: %s - Node-Name: %s - Status: %s" % (namespace, pod_name, pod_labels_app, pod_node_name, pod_status_phase))
                # in the next step we will check if a rebalance is needed
                balance_vip = True
            else:
                print("Ignoring %s in Namespace %s because App-Label is not set" % (namespace, pod_name))
            # endif

            # then we get the service corresponding to the pod
            if balance_vip:
                try:
                    service = v1_core.read_namespaced_service(pod_name, namespace)
                    service_name = service.metadata.name
                    balance_priority_string = service.metadata.annotations['kubeVipBalancePriority']
                    balance_priority = str(balance_priority_string).split(",")
                    balance_priority = [sub_element.strip() for sub_element in balance_priority]  # remove whitespaces for each element in the list fixed_section
                    print("Service: %s - Balance Priority: %s" % (service_name, balance_priority))
                    # in the next step we will get the lease
                    get_lease = True
                except:
                    print("No Service %s found" % pod_name)
                # endtry

                # we check the if the lease is on the correct node
                if get_lease:
                    try:
                        # leases created by kube-vip are prefixed with "kubevip-"
                        lease = v1_coordination.read_namespaced_lease("kubevip-" + service_name, namespace)
                        lease_name = lease.metadata.name
                        lease_holder = lease.spec.holder_identity
                        print("Lease: %s - Node: %s" % (lease_name, lease_holder))

                        # no we check if pod is running and if the lease_holder is corresponding to the first node in the priority list
                        # if not we patch the holder-value in the lease after checking that the node to swtich to is available and has a running pod
                        if lease_holder == balance_priority[0] and check_container_state(pod_container_statuses):
                            print("Lease holder OK and pod's containers are ready")
                        else:
                            print("Detected wrong lease holder or issues with pod's containers")

                            # now get node state
                            if check_node_state(balance_priority[0]) and check_container_state(pod_container_statuses):
                                print("Node %s ready - checking if needed pod is running" % balance_priority[0])

                                # If pods are back online and ready, this should switch back to first node mentioned in the annotation
                                if check_container_state(pod_container_statuses):
                                    # we have to use "holderIdentity" instead of "holder_identity"
                                    lease_body_patch = {"spec": {"holderIdentity": balance_priority[0]}}
                                    lease_patch_response = v1_coordination.patch_namespaced_lease("kubevip-" + service_name, namespace, lease_body_patch)
                                    try:
                                        # it seems that if we do not patch this kube-vip sometimes removes the VIP completely for about 60s until it reassigns the VIP to some other node
                                        service_body_patch = {"metadata": {"annotations": {"kube-vip.io/vipHost": balance_priority[0]}}}
                                        service_patch_response = v1_core.patch_namespaced_service(service_name, namespace, service_body_patch)
                                        # print(service_patch_response)
                                    except Exception as e:
                                        print("Exception when calling CoreV1Api->patch_namespaced_service: %s\n" % e)
                                    print("HOLDER CHANGED TO PRIMARY NODE %s" % lease_patch_response.spec.holder_identity)
                                    print("entering grace-period for next change for about 30sec")
                            else:
                                print("Node %s currently unavailable or pod's containers has issues - checking for suitable node" % balance_priority[0])

                                # check other nodes until a ready one with a running pod was found
                                # as the preferred node currently has a problem, we start from second on
                                holder_changed = False
                                for node in balance_priority[1:]:
                                    if check_node_state(node) and not holder_changed:
                                        print("Node %s is ready - checking for available pod" % node)
                                        # check for pod with ok state
                                        # get pods from namespace
                                        pods_in_namespace = v1_core.list_namespaced_pod(namespace)
                                        # get pods with pod_app_label from this node and check if ready
                                        for pod in pods_in_namespace.items:
                                            if pod.metadata.labels['app'] == pod_labels_app and pod.spec.node_name != balance_priority[0] and pod.spec.node_name == node:
                                                print("Pod %s found - checking for ready containers" % pod.metadata.name)
                                                if check_container_state(pod.status.container_statuses):
                                                    print("Pod %s ready on node %s - patching holder" % (pod.metadata.name, node))
                                                    lease_body_patch = {"spec": {"holderIdentity": node}}
                                                    lease_patch_response = v1_coordination.patch_namespaced_lease("kubevip-" + service_name, namespace, lease_body_patch)
                                                    try:
                                                        service_body_patch = {"metadata": {"annotations": {"kube-vip.io/vipHost": node}}}
                                                        service_patch_response = v1_core.patch_namespaced_service(service_name, namespace, service_body_patch)
                                                        # print(service_patch_response)
                                                    except Exception as e:
                                                        print("Exception when calling CoreV1Api->patch_namespaced_service: %s\n" % e)
                                                    print("HOLDER CHANGED TO ALTERNATIVE NODE %s" % lease_patch_response.spec.holder_identity)
                                                    holder_changed = True
                                                    print("entering grace-period for next change for about 30sec")
                                                # endif
                                            # endif
                                        # endfor
                                    else:
                                        break
                                    # endif
                                else:
                                    print("currently cannot assign VIP to different node - none ready or we are currently in grace-period because of recent change")
                                # endfor
                            # endfi
                        # endif
                    except:
                        print("No Lease kubevip-%s found" % service_name)
                    # endtry
                # endif
            # endif
    except:
        pass
    # endtry
# endfor

```

So if one of the pods have an issue and are not ready the VIP will be assigned to a secondary node mentioned in the annotation. If the pod later gets back online, the VIP gets back to the "primary" wanted node.

Like I wrote - I'm still testing and absolutely no warranty that this is smart or doesn't create any other issues :D
