### ISSUE TITLE
externalTrafficPolicy Local not working as expected

### ISSUE THREAD

**Issue by p3lim** [kube-vip/kube-vip#431]
**Describe the bug**
Creating a service with `externalTrafficPolicy: Local` never gets advertised by kube-vip after receiving a loadbalancerIP from kube-vip-cloud-provider.

Logs complain that no local pods were found, even though they exist.

If I create the service with `externalTrafficPolicy: Cluster` it gets an IP, and if I edit/update the service and set `externalTrafficPolicy: Local` I get Local behavior as expected.

**To Reproduce**
1. Deploy kube-vip + kube-vip-cloud-provider
  - ARP mode, see manifest below
2. Configure cidr/range for kvcp
3. Deploy a service with `externalTrafficPolicy: Local`
4. ExternalIP stuck in pending

**Expected behavior**
I expected kube-vip to advertise the IP.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: k3s 1.23.9
 - Kube-vip Version: 0.5.0

**`Kube-vip.yaml`:**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: cp_enable
          value: "true"
        - name: svc_enable
          value: "true"
        - name: address
          value: 192.168.60.100
        - name: port
          value: "6443"
        - name: vip_ddns
          value: "false"
        - name: prometheus_server
          value: :2112
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: eth0
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: svc_election
          value: "true"
        image: ghcr.io/kube-vip/kube-vip:v0.5.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 2
  updatedNumberScheduled: 3
```

**Additional context**

Output from `kubectl get pod,svc -A -owide`:
```
NAMESPACE     NAME                            READY   STATUS    RESTARTS        AGE    IP                NODE    NOMINATED NODE   READINESS GATES
default       pod/whoami-76b79cb87f-dbprt     1/1     Running   0               15m    10.42.1.15        kube2   <none>           <none>
default       pod/whoami-76b79cb87f-fzkxq     1/1     Running   0               15m    10.42.0.16        kube1   <none>           <none>
default       pod/whoami-76b79cb87f-gknw2     1/1     Running   0               15m    10.42.2.15        kube3   <none>           <none>
kube-system   pod/kube-vip-cloud-provider-0   1/1     Running   0               130m   10.42.2.4         kube3   <none>           <none>
kube-system   pod/kube-vip-ds-gcnhc           1/1     Running   1 (4h3m ago)    4h7m   192.168.121.205   kube3   <none>           <none>
kube-system   pod/kube-vip-ds-l6kmg           1/1     Running   1 (3h59m ago)   4h7m   192.168.121.107   kube1   <none>           <none>
kube-system   pod/kube-vip-ds-p4cgh           1/1     Running   1 (4h3m ago)    4h7m   192.168.121.135   kube2   <none>           <none>

NAMESPACE     NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                  AGE    SELECTOR
default       service/kubernetes        ClusterIP      10.43.0.1       <none>          443/TCP                  4h8m   <none>
default       service/whoami-service    LoadBalancer   10.43.81.93     <pending>       80:31588/TCP             15m    app=whoami
kube-system   service/kube-dns          ClusterIP      10.43.0.10      <none>          53/UDP,53/TCP,9153/TCP   4h8m   k8s-app=kube-dns
```

Relevant logs from Cluster:
```
time="2022-08-03T10:44:47Z" level=info msg="service [whoami-service] has been added/modified it has an assigned external addresses [192.168.60.18]"
time="2022-08-03T10:44:47Z" level=info msg="beginning services leadership, namespace [default], lock name [kubevip-whoami-service], id [kube1]"
I0803 10:44:47.251039       1 leaderelection.go:248] attempting to acquire leader lease default/kubevip-whoami-service...
time="2022-08-03T10:44:47Z" level=info msg="new leader elected: kube3"
time="2022-08-03T10:44:47Z" level=info msg="service [whoami-service] has been added/modified it has an assigned external addresses [192.168.60.18]"
time="2022-08-03T10:44:47Z" level=info msg="service [whoami-service] has been added/modified it has an assigned external addresses [192.168.60.18]"
```

Relevant logs from Local:
```
time="2022-08-03T10:45:20Z" level=warning msg="loadBalancer has External Traffic Policy: Local, no local pods found"
```
