### ISSUE TITLE
[0.5.0] externalTrafficPolicy: Local does not work. kube-vip does not detect endpoint changes in table mode (or at all?)

### ISSUE THREAD

**Issue by alloran** [kube-vip/kube-vip#448]
**Describe the bug**
externalTrafficPolicy: Local does not work. kube-vip does not detect endpoint changes in table mode (or at all?)

**To Reproduce**
1.Apply service + single-pod deployment manifest with affinity to single node (i.e. test-lab-worker02 in my case)
2. Change deployment pod affinity to another node (i.e. test-lab-worker03 in my case)
3. See no changes for loadbalancer address announcement

**Expected behavior**
kube-vip must remove the loadbalancer ip address announcement  from the node with no local pods and add it to another node

**Screenshots**
Deployment manifest
```
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.164.64
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - test-lab-worker02
      containers:
      - image: nginx:1.21.5
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
```

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 1804
 - Kubernetes Version: v.1.20.15
 - Kube-vip Version: 0.5.0

**`Kube-vip.yaml`:**
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services", "services/status", "nodes", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.0
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.0
    spec:
      containers:
      - args:
        - manager
        - --log=5
        - --table
        - --services
        - --servicesElection
        - --serviceInterface=kube-dummy-if
        image: ghcr.io/kube-vip/kube-vip:v0.5.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
```

**Additional context**
kube-vip logs (initial pod placenent node)
```
time="2022-09-09T12:30:33Z" level=info msg="Starting kube-vip.io [v0.5.0]"
time="2022-09-09T12:30:33Z" level=info msg="namespace [kube-system], Mode: [Routing Table], Features(s): Control Plane:[false], Services:[true]"
time="2022-09-09T12:30:33Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2022-09-09T12:30:33Z" level=info msg="kube-vip will bind to interface [ens3]"
time="2022-09-09T12:30:33Z" level=warning msg="the status of the interface kube-dummy-if is unknown. Ensure your interface is ready to accept traffic, if so you can safely ignore this message"
time="2022-09-09T12:30:33Z" level=info msg="prometheus HTTP server started"
time="2022-09-09T12:30:33Z" level=info msg="Starting Kube-vip Manager with the Routing Table engine"
time="2022-09-09T12:30:33Z" level=info msg="all routing table entries will exist in table [198]"
time="2022-09-09T12:30:33Z" level=info msg="beginning watching services, leaderelection will happen for every service"
time="2022-09-09T12:30:33Z" level=warning msg="loadBalancer has External Traffic Policy: Local, no local pods found"
time="2022-09-09T12:35:02Z" level=info msg="service [nginx] has been added/modified it has an assigned external addresses [192.168.164.64]"
time="2022-09-09T12:35:02Z" level=info msg="beginning services leadership, namespace [default], lock name [kubevip-nginx], id [adm-vm-k8s-test-lab-worker02]"
I0909 12:35:02.601865       1 leaderelection.go:248] attempting to acquire leader lease default/kubevip-nginx...
I0909 12:35:02.701862       1 leaderelection.go:258] successfully acquired lease default/kubevip-nginx
time="2022-09-09T12:35:02Z" level=info msg="adding the service [default/nginx] with external address [192.168.164.64]"
time="2022-09-09T12:35:02Z" level=info msg="new VIP [192.168.164.64] for [default/nginx] "
time="2022-09-09T12:35:02Z" level=info msg="Starting advertising address [192.168.164.64] with kube-vip"
time="2022-09-09T12:35:02Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-09-09T12:35:03Z" level=info msg="service [nginx] has been added/modified it has an assigned external addresses [192.168.164.64]"
```
kube-vip logs (second node)
```
time="2022-09-09T12:30:35Z" level=info msg="Starting kube-vip.io [v0.5.0]"
time="2022-09-09T12:30:35Z" level=info msg="namespace [kube-system], Mode: [Routing Table], Features(s): Control Plane:[false], Services:[true]"
time="2022-09-09T12:30:35Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2022-09-09T12:30:35Z" level=info msg="prometheus HTTP server started"
time="2022-09-09T12:30:35Z" level=info msg="kube-vip will bind to interface [ens3]"
time="2022-09-09T12:30:35Z" level=warning msg="the status of the interface kube-dummy-if is unknown. Ensure your interface is ready to accept traffic, if so you can safely ignore this message"
time="2022-09-09T12:30:35Z" level=info msg="Starting Kube-vip Manager with the Routing Table engine"
time="2022-09-09T12:30:35Z" level=info msg="all routing table entries will exist in table [198]"
time="2022-09-09T12:30:35Z" level=info msg="beginning watching services, leaderelection will happen for every service"
time="2022-09-09T12:30:35Z" level=warning msg="loadBalancer has External Traffic Policy: Local, no local pods found"
time="2022-09-09T12:35:04Z" level=warning msg="loadBalancer has External Traffic Policy: Local, no local pods found"
<< nothing about endpoint change here >>

```

It seems this issue is related to #431
