### ISSUE TITLE
Panic after cluster restore with Velero

### ISSUE THREAD

**Issue by bjschafer** [kube-vip/kube-vip#450]
**Describe the bug**
I'm running the kube-vip daemonset in BGP mode. Recently I restored my entire cluster from a Velero backup. Since then, all kube-vip pods have been crashlooping.

<details>
<summary>Logs and stacktrace</summary>

```
time="2022-09-13T15:12:25Z" level=info msg="Starting kube-vip.io [v0.5.0]"
time="2022-09-13T15:12:25Z" level=info msg="namespace [kube-system], Mode: [BGP], Features(s): Control Plane:[true], Services:[true]"
time="2022-09-13T15:12:25Z" level=info msg="prometheus HTTP server started"
time="2022-09-13T15:12:25Z" level=info msg="Starting Kube-vip Manager with the BGP engine"
time="2022-09-13T15:12:25Z" level=info msg="Starting the BGP server to advertise VIP routes to BGP peers"
time="2022-09-13T15:12:25Z" level=info msg="Add a peer configuration" Key=10.0.10.51 Topic=Peer
time="2022-09-13T15:12:25Z" level=info msg="Add a peer configuration" Key=10.0.10.52 Topic=Peer
time="2022-09-13T15:12:25Z" level=info msg="Add a peer configuration" Key=10.0.10.53 Topic=Peer
time="2022-09-13T15:12:25Z" level=info msg="Add a peer configuration" Key=10.0.10.1 Topic=Peer
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.51" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.51" peer_asn:64512 session_state:IDLE router_id:"<nil>"} transport:{local_address:"<nil>"}}
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.52" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.52" peer_asn:64512 session_state:IDLE router_id:"<nil>"} transport:{local_address:"<nil>"}}
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.52" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.52" peer_asn:64512 session_state:ACTIVE router_id:"<nil>"} transport:{local_address:"<nil>"}}
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.53" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.53" peer_asn:64512 session_state:IDLE router_id:"<nil>"} transport:{local_address:"<nil>"}}
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.51" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.51" peer_asn:64512 session_state:ACTIVE router_id:"<nil>"} transport:{local_address:"<nil>"}}
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.53" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.53" peer_asn:64512 session_state:ACTIVE router_id:"<nil>"} transport:{local_address:"<nil>"}}
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.1" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.1" peer_asn:64512 session_state:IDLE router_id:"<nil>"} transport:{local_address:"<nil>"}}
2022/09/13 15:12:25 type:STATE peer:{conf:{local_asn:64512 neighbor_address:"10.0.10.1" peer_asn:64512} state:{local_asn:64512 neighbor_address:"10.0.10.1" peer_asn:64512 session_state:ACTIVE router_id:"<nil>"} transport:{local_address:"<nil>"}}
time="2022-09-13T15:12:25Z" level=info msg="service [traefik] has been added/modified it has an assigned external addresses [10.0.10.93]"
time="2022-09-13T15:12:25Z" level=info msg="add the service [kube-system/traefik] with external address [10.0.10.93]"
time="2022-09-13T15:12:25Z" level=info msg="new VIP [10.0.10.93] for [kube-system/traefik] "
time="2022-09-13T15:12:25Z" level=info msg="Starting advertising address [10.0.10.93] with kube-vip"
time="2022-09-13T15:12:25Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-09-13T15:12:25Z" level=info msg="service [ftpserver] has been added/modified it has an assigned external addresses [10.0.10.80]"
time="2022-09-13T15:12:25Z" level=info msg="add the service [paperless/ftpserver] with external address [10.0.10.80]"
time="2022-09-13T15:12:25Z" level=info msg="new VIP [10.0.10.80] for [paperless/ftpserver] "
time="2022-09-13T15:12:25Z" level=info msg="Starting advertising address [10.0.10.80] with kube-vip"
time="2022-09-13T15:12:25Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-09-13T15:12:26Z" level=info msg="service [traefik] has been added/modified it has an assigned external addresses [10.0.10.93]"
time="2022-09-13T15:12:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2022-09-13T15:12:26Z" level=info msg="[VIP] Releasing the Virtual IP [10.0.10.93]"
time="2022-09-13T15:12:26Z" level=info msg=Stopped
time="2022-09-13T15:12:26Z" level=info msg="add the service [kube-system/traefik] with external address [10.0.10.93]"
time="2022-09-13T15:12:26Z" level=info msg="new VIP [10.0.10.93] for [kube-system/traefik] "
time="2022-09-13T15:12:26Z" level=info msg="Starting advertising address [10.0.10.93] with kube-vip"
time="2022-09-13T15:12:26Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-09-13T15:12:27Z" level=info msg="service [ftpserver] has been added/modified it has an assigned external addresses [10.0.10.80]"
time="2022-09-13T15:12:27Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2022-09-13T15:12:27Z" level=info msg="[VIP] Releasing the Virtual IP [10.0.10.80]"
time="2022-09-13T15:12:27Z" level=info msg=Stopped
time="2022-09-13T15:12:27Z" level=info msg="add the service [paperless/ftpserver] with external address [10.0.10.80]"
time="2022-09-13T15:12:27Z" level=info msg="new VIP [10.0.10.80] for [paperless/ftpserver] "
time="2022-09-13T15:12:27Z" level=info msg="Starting advertising address [10.0.10.80] with kube-vip"
time="2022-09-13T15:12:27Z" level=info msg="Started Load Balancer and Virtual IP"
time="2022-09-13T15:12:27Z" level=info msg="service [traefik] has been added/modified it has an assigned external addresses [10.0.10.93]"
time="2022-09-13T15:12:27Z" level=info msg="service [ftpserver] has been added/modified it has an assigned external addresses [10.0.10.80]"
time="2022-09-13T15:12:27Z" level=info msg="service [traefik] has been added/modified it has an assigned external addresses [10.0.10.93]"
time="2022-09-13T15:12:27Z" level=info msg="Delete a peer configuration" Key=10.0.10.51 Topic=Peer
time="2022-09-13T15:12:27Z" level=info msg="Delete a peer configuration" Key=10.0.10.52 Topic=Peer
time="2022-09-13T15:12:27Z" level=info msg="Delete a peer configuration" Key=10.0.10.53 Topic=Peer
time="2022-09-13T15:12:27Z" level=info msg="Delete a peer configuration" Key=10.0.10.1 Topic=Peer
panic: close of closed channel

goroutine 1 [running]:
github.com/kube-vip/kube-vip/pkg/cluster.(*Cluster).Stop(0xc000107440)
        /src/pkg/cluster/cluster.go:55 +0x29
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).deleteService(0xc000478d20, {0xc0006678f0, 0x24})
        /src/pkg/manager/services.go:33 +0x1c5
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).syncServices(0xc000478d20, {0xc00051d860?, 0x10?}, 0xc000704a00, 0xc0001dbea0?)
        /src/pkg/manager/services.go:83 +0x3d6
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).servicesWatcher(0xc000478d20, {0x1bd2b10?, 0xc000313640?}, 0xc0001039f0)
        /src/pkg/manager/watch_services.go:119 +0x101e
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).startBGP(0xc000478d20)
        /src/pkg/manager/manager_bgp.go:111 +0x6ba
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).Start(0xc000478d20)
        /src/pkg/manager/manager.go:126 +0x312
github.com/kube-vip/kube-vip/cmd.glob..func11(0x27e6d60, {0x193f8f2?, 0x0?, 0x0?})
        /src/cmd/kube-vip.go:334 +0xa47
github.com/spf13/cobra.(*Command).execute(0x27e6d60, {0x2832588, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x27e7c60)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kube-vip/kube-vip/cmd.Execute()
        /src/cmd/kube-vip.go:146 +0x25
main.main()
        /src/main.go:16 +0x85
```

</details>

I wonder if the restore restored something that kube-vip doesn't like. The logs aren't super clear on that, though.

**To Reproduce**
1. Install kube-vip in BGP mode
2. Take a velero backup
3. Restore velero backup
4. Watch as the kube-vip pods crashloop

**Expected behavior**
Pods run without issue after restore.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: v1.24.4+k3s1
 - Kube-vip Version: v0.5.0

**`Kube-vip.yaml`:**

<details>
<summary>ds.yaml</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.0
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: bgp_enable
          value: "true"
        - name: bgp_as
          value: "64512"
        - name: bgp_peeraddress
          value: "10.0.10.1"
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "64512"
        - name: bgp_peers
          value: 10.0.10.51:64512::false,10.0.10.52:64512::false,10.0.10.53:64512::false
        - name: address
          value: 10.0.10.50
        - name: bgp_routerinterface
          value: "eth0"
        image: ghcr.io/kube-vip/kube-vip:v0.5.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```

</details>

<details>
<summary>configmap.yaml</summary>

```yaml
apiVersion: v1
data:
  range-global: 10.0.10.80-10.0.10.99
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"range-global":"10.0.10.80-10.0.10.99"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"kube-vip"},"name":"kubevip","namespace":"kube-system"}}
  creationTimestamp: "2022-09-12T03:09:50Z"
  labels:
    app.kubernetes.io/instance: kube-vip
  name: kubevip
  namespace: kube-system
  resourceVersion: "1315508"
  uid: e9cac826-66ed-4d98-8e43-27f04f374f97
```

</details>
