### ISSUE TITLE
Log flooded with "\"\" is not an Ethernet MAC address"

### ISSUE THREAD

**Issue by xinbinhuang** [kube-vip/kube-vip#458]
**Describe the bug**

I just deployed `kube-vip` as a deamonset using this command

```
export INTERFACE=lo

kube-vip manifest daemonset \        
    --interface $INTERFACE \
    --address $VIP \
    --inCluster \
    --taint \
    --controlplane \
    --services \
    --arp \
    --leaderElection > daemonset.yaml
```

I aslo added the load-balancing environment variable.
```
        - name : lb_enable
          value: "true"
```

HA control plane is working correctly, and I can interact with the AP I server using the VIP.

However, leader pod's log is flooded with this warning/error message

```
 time="2022-10-04T06:04:38Z" level=warning msg="\"\" is not an Ethernet MAC address"
...

```

**Expected behavior**
Log is not flooded

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: ubuntu 22.04
 - Kubernetes Version: v1.24.4+k3s1
 - Kube-vip Version: 0.5.0

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.0
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: <INTERFACE>
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name : lb_enable
          value: "true"
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: <VIP>
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.5.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
