### ISSUE TITLE
kube-apiserver intermidantly returns connection refused

### ISSUE THREAD

**Issue by ImNtReal** [kube-vip/kube-vip#468]
I have a k8s cluster that I recently rebuilt using kube-vip to provide HA for the control plane, and LoadBalancer services. It appears that pods inside the cluster receive Connection Refused on approximately 1/3 of attempts to make an API call. I'm still not sure exactly where the disconnects are happening.

**To Reproduce**
1. Build cluster using kubeadm
2. Run kubectl run tmp-shell --rm -i --tty --image nicolaka/netshoot
3. From inside the pod run curl -k https://kubernetes.default.svc/api multiple times
4. Get Connection Refused on some responses

**Expected behavior**
In this case, I would expect the API server to return a 403 forbidden on every attempt.

**Screenshots**
```
 tmp-shell  ~  cat test.sh
#! /bin/bash

while true; do
  sleep 5
  curl -k https://kubernetes.default.svc/api
done

 tmp-shell  ~  ./test.sh
curl: (7) Failed to connect to kubernetes.default.svc port 443 after 2 ms: Connection refused
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}curl: (7) Failed to connect to kubernetes.default.svc port 443 after 2 ms: Connection refused
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}curl: (7) Failed to connect to kubernetes.default.svc port 443 after 2 ms: Connection refused
```

**Environment (please complete the following information):**
 - OS/Distro: Clear Linux
 - Kubernetes Version: v1.25.2
 - Kube-vip Version: v0.5.5

**`Kube-vip.yaml`:**
```
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "443"
    - name: vip_interface
      value: ens192
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 172.16.73.21
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.5.5
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**
I have been trying to track down the issue with a Github issue opened with flannel (the CNI plugin I'm running): https://github.com/flannel-io/flannel/issues/1661

**Comment by ImNtReal** [comment]
Here's my kubeadm.yaml in case it's helpful:
```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: ####################
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 172.16.73.16
  bindPort: 443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: vminkube01.nghs.com
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  certSANs:
  - 172.16.73.21
  - 172.16.73.16
  - 172.16.73.17
  - 172.16.73.18
  - kube.nghs.com
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: kube.nghs.com:443
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kubernetesVersion: v1.25.2
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.245.0.0/16
scheduler: {}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"
protectKernelDefaults: false
```
