### ISSUE TITLE
kube-vip services drops the VIP, doesn't retake it without manual restart

### ISSUE THREAD

**Issue by mdbooth** [kube-vip/kube-vip#475]
TL;DR

This isn't really a bug report; it's more of a feature request. The structure of the services controller is nothing like I have ever seen. It's extremely hard to reason about. I suspect it contains a lot of races, more than one of which are likely causing the issues I hit daily. I was going to try to find and fix the bugs I'm hitting, but I'm left thinking I'd rather re-architect the control loop.

The control plane VIP has been *solid*, though 👍

**Describe the bug**
I run kube-vip in a small, unreliable cluster. The hardware's janky. The network's janky. Everything's janky. Something somewhere is failing most of the time.

The cluster is deployed by kubeadm. I deploy kube-vip as a static pod on the control plane. YAML below.

In this environment kube-vip LB services frequently get wedged in a state where a node has dropped the service VIP but no other node has taken it. The lease has expired, so presumably the other nodes weren't watching it. I run most most of my services with `externalTrafficPolicy: Local`, so scheduling may also be a factor.

I see at least 4 different failure modes in the kube-vip logs:

1. Nothing. Everything's fine, apparently, but the node doesn't have the VIP.
2. Screens of kube-apiserver connection errors from a variety of controller sources (retrywatcher, leaderelection).
3. Screens of *client-side* rate throttling because the client is looping with no backoff.
4. Something happened, the node lost the service election and dropped the VIP, but never took it back.

These may or may not have common causes. As mentioned above I suspect a variety of causes.

In all cases, manually killing kube-vip will cause it to recover *immediately*. This is important because it suggests that whatever condition caused kube-vip to drop the VIP in the first place is no longer present, but kube-vip wasn't able to recover in its current state.

The code structure of the services handling is unusual. I've only spent an hour or so browsing, so apologies if I've missed something very important. It seems to involve setting separate watches on individual services. Apart from being harder to reason about concurrency, I suspect this has also has a higher overhead on the apiserver than a single watch on services. Is there any reason you've done it this way rather than something more like, e.g. the controller runtime approach? I guess the complexity here is the multiple leader elections? I suspect we're missing numerous ordering edge cases which are fairly easy to hit in practise once you start introducing the occasional failure and a bit of latency. Having a single control loop which is able to reconstruct state on each iteration should make that a lot more failure tolerant in practise.

Anyway, this is something I'm potentially willing and able to work on. Is that something you're interested in? If so, any insight into how we got here?

**Environment (please complete the following information):**
 - OS/Distro: Fedora CoreOS
 - Kubernetes Version: 1.25
 - Kube-vip Version: 0.5.5

**`Kube-vip.yaml`:**
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: eno1
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: svc_election
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: lb_enable
      value: "true"
    - name: lb_port
      value: "6443"
    - name: lb_fwdmethod
      value: local
    - name: address
      value: api.cluster.heisenbug.com
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.5.5
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
```
