### ISSUE TITLE
Virtual IP address bouncing between the nodes

### ISSUE THREAD

**Issue by emulated24** [kube-vip/kube-vip#491]
**Describe the bug**
Virtual IP address bouncing between the nodes on the fresh installation of k3s 3-node cluster running on RPi 4b.

**To Reproduce**
1. Install k3s with three master nodes:

```
NAME   STATUS   ROLES                       AGE    VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
rpi1   Ready    control-plane,etcd,master   128m   v1.25.4+k3s1   192.168.1.41   <none>        Debian GNU/Linux 11 (bullseye)   5.15.76-v8+      containerd://1.6.8-k3s1
rpi2   Ready    control-plane,etcd,master   125m   v1.25.4+k3s1   192.168.1.42   <none>        Debian GNU/Linux 11 (bullseye)   5.15.76-v8+      containerd://1.6.8-k3s1
rpi3   Ready    control-plane,etcd,master   123m   v1.25.4+k3s1   192.168.1.43   <none>        Debian GNU/Linux 11 (bullseye)   5.15.76-v8+      containerd://1.6.8-k3s1
```

2. Deploy kube-vip:

```
curl -s https://kube-vip.io/manifests/rbac.yaml | sudo tee /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml
sudo /usr/local/bin/k3s crictl pull docker.io/plndr/kube-vip:latest
sudo /usr/local/bin/k3s ctr run --rm --net-host docker.io/plndr/kube-vip:latest \
        vip /kube-vip manifest daemonset \
          --arp \
          --interface eth0 \
          --address 192.168.1.30 \
          --controlplane \
          --services \
          --leaderElection \
          --inCluster \
          --taint \
  | sudo tee /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
```

3. Check where the IP is located:

```
arp 192.168.1.30
```
Output of two command executions:
```
? (192.168.1.30) at <mac>:d8 on en0 ifscope [ethernet]
? (192.168.1.30) at <mac>:c9 on en0 ifscope [ethernet]
```

**Expected behavior**
VIP should remain on one node until the node has an issue or is restarted.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: DietPi v8.11.2, kernel 5.15.76-v8+, based on Debian 11 (bullseye)
 - Kubernetes Version: k3s v1.25.3+k3s1
 - Kube-vip Version: v0.5.7

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.7
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.7
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.1.30
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.5.7
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
