### ISSUE TITLE
v0.5.11 is building manifests that reference v0.5.10

### ISSUE THREAD

**Issue by cprivitere** [kube-vip/kube-vip#527]
**Describe the bug**
v0.5.11 is building manifests that reference v0.5.10
Also the docker alias on the equinix metal page has a typo (refers to KVVERSION instead of $KVVERSION)

**To Reproduce**
1. Go to https://kube-vip.io/docs/usage/equinix/
2. Follow directions to do the kube-vip alias
3. Instead of piping it to kubectl apply -f, just inspect the output.
4. You'll see things like:
```yaml
 image: ghcr.io/kube-vip/kube-vip:v0.5.10
```

**Expected behavior**
```yaml
 image: ghcr.io/kube-vip/kube-vip:v0.5.11
```

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: 1.26
 - Kube-vip Version: 0.5.11

**`Kube-vip.yaml`:**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.10
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.10
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: lo:0
        - name: vip_cidr
          value: "32"
        - name: svc_enable
          value: "true"
        - name: annotation
          value: metal.equinix.com
        - name: bgp_enable
          value: "true"
        - name: bgp_routerid
        - name: bgp_as
          value: "65000"
        - name: bgp_peeraddress
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "65000"
        - name: vip_address
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.5.10
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
