### ISSUE TITLE
kube-vip not running in just services mode

### ISSUE THREAD

**Issue by cprivitere** [kube-vip/kube-vip#530]
**Describe the bug**
I’m trying to pass a daemon set config and not enable the control plane stuff. However it comes and tries to bind the IP of the control plane on an interface on my worker nodes.

**To Reproduce**
1. Set up kube-vip to run with just services and do not pass the control plane flag

**Expected behavior**
Should start up and manage loadbalancer services on the worker nodes.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: 1.26.1
 - Kube-vip Version: 0.5.11

**`Kube-vip.yaml`:**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.11
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.11
    spec:
      containers:
      - args:
        - manager
        env:
        - name: svc_enable
          value: "true"
        - name: annotation
          value: metal.equinix.com
        - name: bgp_enable
          value: "true"
        - name: bgp_as
          value: "65000"
        - name: bgp_peeras
          value: "65000"
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.5.11
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
```
k logs -n kube-system kube-vip-ds-6psvb
time="2023-03-06T22:46:13Z" level=info msg="Starting kube-vip.io [v0.5.10]"
time="2023-03-06T22:46:13Z" level=info msg="namespace [kube-system], Mode: [BGP], Features(s): Control Plane:[false], Services:[true]"
time="2023-03-06T22:46:13Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2023-03-06T22:46:13Z" level=info msg="prometheus HTTP server started"
time="2023-03-06T22:46:13Z" level=info msg="kube-vip will bind to interface [bond0]"
time="2023-03-06T22:46:13Z" level=info msg="Kube-Vip is waiting for annotation prefix [metal.equinix.com] to be present on this node"
time="2023-03-06T22:46:13Z" level=info msg="Starting Kube-vip Manager with the BGP engine"
time="2023-03-06T22:46:13Z" level=info msg="Starting the BGP server to advertise VIP routes to BGP peers"
time="2023-03-06T22:46:13Z" level=info msg="Add a peer configuration" Key=169.254.255.1 Topic=Peer
time="2023-03-06T22:46:13Z" level=info msg="starting services watcher for all namespaces"
2023/03/06 22:46:13 type:STATE  peer:{conf:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530}  state:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530  session_state:IDLE  router_id:"<nil>"}  transport:{local_address:"<nil>"}}
2023/03/06 22:46:13 type:STATE  peer:{conf:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530}  state:{local_asn:65000  neighbor_address:"169.254.255.1"  peer_asn:65530  session_state:ACTIVE  router_id:"<nil>"}  transport:{local_address:"<nil>"}}
time="2023-03-06T22:46:13Z" level=info msg="[service] adding VIP [147.28.182.118] for [kube-system/cloud-provider-equinix-metal-kubernetes-external] "
time="2023-03-06T22:46:13Z" level=info msg="[service] synchronised in 22ms"
```

**Comment by cprivitere** [comment]
Still an issue in v0.5.12.

**Comment by bjschafer** [comment]
I think this could be a more general issue when running in DaemonSet mode. I'm running with both control-plane and services mode, and seeing the control-plane VIP get advertised on all nodes, including workers.

Oddly nothing in the logs mentions advertising the control-plane IP.

## DS yaml

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/name: kube-vip-ds
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: lo
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: bgp_enable
          value: "true"
        - name: bgp_as
          value: "64512"
        - name: bgp_peeraddress
          value: 10.0.10.1
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "64512"
        - name: address
          value: 10.0.10.50
        - name: bgp_routerid
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: ghcr.io/kube-vip/kube-vip:v0.6.0
        imagePullPolicy: Always
        name: kube-vip
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
