### ISSUE TITLE
kube-vip ignoring kube-vip.io/loadbalancerIPs annotation

### ISSUE THREAD

**Issue by larsks** [kube-vip/kube-vip#534]
I am running kube-vip v0.5.11 (but see below) on k3s (`v1.25.7+k3s1`) on Rocky Linux 9.1. I tried creating a Service using a manifest like this using the `kube-vip.io/loadbalancerIPs` annotation:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.1.216
  labels:
    app.kubernetes.io/instance: house
    app.kubernetes.io/name: whoami
  name: whoami
  namespace: lb-example
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/instance: house
    app.kubernetes.io/name: whoami
  type: LoadBalancer
```

With this deployed, the Service never receives an external ip address; I always see `<pending>` in the `EXTERNAL-IP` field:

```
NAME                        TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
whoami                      LoadBalancer   10.43.157.209   <pending>     80:30094/TCP     62s
cm-acme-http-solver-zlffp   NodePort       10.43.38.212    <none>        8089:30444/TCP   21s
```

At the same time, `kube-vip` doesn't log any messages when the service is created.

If I add `spec.loadBalancerIP`, like this:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.1.216
  labels:
    app.kubernetes.io/instance: house
    app.kubernetes.io/name: whoami
  name: whoami
  namespace: lb-example
spec:
  loadBalancerIP: 192.168.1.216
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/instance: house
    app.kubernetes.io/name: whoami
  type: LoadBalancer
```

Then `kube-vip` recognizes the Service:

```
kube-vip-svc-node-0 kube-vip time="2023-03-18T13:57:06Z" level=info msg="[service] adding VIP [192.168.1.216] for [lb-example/whoami] "
kube-vip-svc-node-0 kube-vip time="2023-03-18T13:57:07Z" level=info msg="[service] synchronised in 633ms"
```

And the Service now has an external ip:

```
NAME     TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
whoami   LoadBalancer   10.43.157.209   192.168.1.216   80:30094/TCP   2m7s
```

This behavior seems to be contrary to the documentation, which suggests that one should be able to set an IP using either `spec.loadBalancerIP` field or the `kube-vip.io/loadbalancerIPs` annotaiton.

---

I've noticed that while the Pod manifest has:

```
image: ghcr.io/kube-vip/kube-vip:v0.5.11
```

The logs still show:

```
time="2023-03-18T13:12:24Z" level=info msg="Starting kube-vip.io [v0.5.10]"
```
