### ISSUE TITLE
Communications errors on dns port

### ISSUE THREAD

**Issue by i5Js** [kube-vip/kube-vip#541]
**Describe the bug**
Communications errors between a host and the DNS (pihole) port TCP/UDP
K3s cluster + metallb

**To Reproduce**
1. Deployed K3s and metallb per doc guides
2. Deployed kube-vip with the latest version per doc
3. Deployed pihole with helm, usign mojo2600 chart ( https://github.com/MoJo2600/pihole-kubernetes)
4. dig to the dns server
5. See error:
```
i5Js@raspiserver:~$ dig +notcp @192.168.1.122 www.google.es
;; communications error to 192.168.1.122#53: timed out
;; communications error to 192.168.1.122#53: timed out
;; communications error to 192.168.1.122#53: timed out

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> +notcp @192.168.1.122 www.google.es
; (1 server found)
;; global options: +cmd
;; no servers could be reached

i5Js@raspiserver:~$ dig +tcp @192.168.1.122 www.google.es
;; Connection to 192.168.1.122#53(192.168.1.122) for www.google.es failed: timed out.
;; Connection to 192.168.1.122#53(192.168.1.122) for www.google.es failed: timed out.
;; Connection to 192.168.1.122#53(192.168.1.122) for www.google.es failed: timed out.

```
**Expected behavior**
```
i5Js@raspiserver:~$ dig +tcp @192.168.1.122 www.google.es

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> +tcp @192.168.1.122 www.google.es
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40352
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: b0d04262623865da (echoed)
;; QUESTION SECTION:
;www.google.es.                 IN      A

;; ANSWER SECTION:
www.google.es.          126     IN      A       142.250.179.131

;; Query time: 51 msec
;; SERVER: 192.168.1.122#53(192.168.1.122) (TCP)
;; WHEN: Sat Apr 15 09:02:36 CEST 2023
;; MSG SIZE  rcvd: 83

i5Js@raspiserver:~$ dig +notcp @192.168.1.122 www.google.es

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> +notcp @192.168.1.122 www.google.es
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38173
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.es.                 IN      A

;; ANSWER SECTION:
www.google.es.          109     IN      A       142.250.179.131

;; Query time: 3 msec
;; SERVER: 192.168.1.122#53(192.168.1.122) (UDP)
;; WHEN: Sat Apr 15 09:02:53 CEST 2023
;; MSG SIZE  rcvd: 58jsalas@raspiserver:~$ dig +tcp @192.168.1.122 www.google.es

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> +tcp @192.168.1.122 www.google.es
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40352
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: b0d04262623865da (echoed)
;; QUESTION SECTION:
;www.google.es.                 IN      A

;; ANSWER SECTION:
www.google.es.          126     IN      A       142.250.179.131

;; Query time: 51 msec
;; SERVER: 192.168.1.122#53(192.168.1.122) (TCP)
;; WHEN: Sat Apr 15 09:02:36 CEST 2023
;; MSG SIZE  rcvd: 83

i5Js@raspiserver:~$ dig +notcp @192.168.1.122 www.google.es

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> +notcp @192.168.1.122 www.google.es
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38173
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.es.                 IN      A

;; ANSWER SECTION:
www.google.es.          109     IN      A       142.250.179.131

;; Query time: 3 msec
;; SERVER: 192.168.1.122#53(192.168.1.122) (UDP)
;; WHEN: Sat Apr 15 09:02:53 CEST 2023
;; MSG SIZE  rcvd: 58
```

**Screenshots**

**Environment (please complete the following information):**
```
i5Js@raspiserver:~$ k get nodes -o wide
NAME          STATUS   ROLES                  AGE    VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                           KERNEL-VERSION       CONTAINER-RUNTIME
noldork3sm1   Ready    control-plane,master   2d1h   v1.26.3+k3s1   192.168.1.241   <none>        Raspbian GNU/Linux 11 (bullseye)   6.1.21-v7+           containerd://1.6.19-k3s1
noldork3sm2   Ready    control-plane,master   2d     v1.26.3+k3s1   192.168.1.242   <none>        Raspbian GNU/Linux 11 (bullseye)   6.1.21-v7+           containerd://1.6.19-k3s1
noldork3sn6   Ready    worker                 2d     v1.26.3+k3s1   192.168.1.240   <none>        Ubuntu 22.04.2 LTS                 6.0.19-media         containerd://1.6.19-k3s1
noldork3sn4   Ready    worker                 2d     v1.26.3+k3s1   192.168.1.246   <none>        Debian GNU/Linux 11 (bullseye)     5.15.93-rockchip64   containerd://1.6.19-k3s1
noldork3sn3   Ready    worker                 2d     v1.26.3+k3s1   192.168.1.245   <none>        Debian GNU/Linux 11 (bullseye)     6.1.21-v8+           containerd://1.6.19-k3s1
noldork3sn2   Ready    worker                 2d     v1.26.3+k3s1   192.168.1.244   <none>        Debian GNU/Linux 11 (bullseye)     6.1.21-v8+           containerd://1.6.19-k3s1
noldork3sn1   Ready    worker                 2d     v1.26.3+k3s1   192.168.1.243   <none>        Debian GNU/Linux 11 (bullseye)     6.1.21-v8+           containerd://1.6.19-k3s1
noldork3sn5   Ready    worker                 2d     v1.26.3+k3s1   192.168.1.247   <none>        Debian GNU/Linux 11 (bullseye)     5.15.93-rockchip64   containerd://1.6.19-k3s1
```
 - Kubernetes Version: v1.26.3
 - Kube-vip Version: 0.5.12

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.5.12
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.5.12
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.1.120
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.5.12
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
```
i5Js@raspiserver:~$ k get svc -n dns-home
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                    AGE
pihole-web       ClusterIP      10.43.74.191   <none>          80/TCP,443/TCP,49312/TCP   22h
pihole-dns-tcp   LoadBalancer   10.43.1.86     192.168.1.122   53:30668/TCP               22h
pihole-dns-udp   LoadBalancer   10.43.11.13    192.168.1.122   53:31335/UDP               22h
```
```
i5Js@raspiserver:~$ k describe svc pihole-dns-tcp -n dns-home
Name:                     pihole-dns-tcp
Namespace:                dns-home
Labels:                   app=pihole
                          app.kubernetes.io/managed-by=Helm
                          chart=pihole-2.12.0
                          heritage=Helm
                          release=pihole
Annotations:              kube-vip.io/vipHost: noldork3sm1
                          meta.helm.sh/release-name: pihole
                          meta.helm.sh/release-namespace: dns-home
                          metallb.universe.tf/allow-shared-ip: svc-pihole
                          metallb.universe.tf/ip-allocated-from-pool: default
Selector:                 app=pihole,release=pihole
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.1.86
IPs:                      10.43.1.86
IP:                       192.168.1.122
LoadBalancer Ingress:     192.168.1.122
Port:                     dns  53/TCP
TargetPort:               dns/TCP
NodePort:                 dns  30668/TCP
Endpoints:                10.42.2.10:53
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30027
Events:                   <none>
```
```
i5Js@raspiserver:~$ k describe svc pihole-dns-udp -n dns-home
Name:                     pihole-dns-udp
Namespace:                dns-home
Labels:                   app=pihole
                          app.kubernetes.io/managed-by=Helm
                          chart=pihole-2.12.0
                          heritage=Helm
                          release=pihole
Annotations:              kube-vip.io/vipHost: noldork3sm1
                          meta.helm.sh/release-name: pihole
                          meta.helm.sh/release-namespace: dns-home
                          metallb.universe.tf/allow-shared-ip: svc-pihole
                          metallb.universe.tf/ip-allocated-from-pool: default
Selector:                 app=pihole,release=pihole
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.11.13
IPs:                      10.43.11.13
IP:                       192.168.1.122
LoadBalancer Ingress:     192.168.1.122
Port:                     dns-udp  53/UDP
TargetPort:               dns-udp/UDP
NodePort:                 dns-udp  31335/UDP
Endpoints:                10.42.2.10:53
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31873
Events:                   <none>
```
```
i5Js@raspiserver:~$ k get ep -n dns-home
NAME             ENDPOINTS                                       AGE
pihole-web       10.42.2.10:443,10.42.2.10:80,10.42.2.10:49312   22h
pihole-dns-tcp   10.42.2.10:53                                   22h
pihole-dns-udp   10.42.2.10:53                                   22h

```
logs

```
i5Js@raspiserver:~$ k logs --follow kube-vip-ds-d7n78 -n kube-system
time="2023-04-15T08:43:15Z" level=info msg="Starting kube-vip.io [v0.5.12]"
time="2023-04-15T08:43:15Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2023-04-15T08:43:15Z" level=info msg="prometheus HTTP server started"
time="2023-04-15T08:43:15Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2023-04-15T08:43:15Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [plndr-svcs-lock], id [noldork3sm2]"
I0415 08:43:15.995177       1 leaderelection.go:248] attempting to acquire leader lease kube-system/plndr-svcs-lock...
time="2023-04-15T08:43:15Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [noldork3sm2]"
I0415 08:43:15.996678       1 leaderelection.go:248] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2023-04-15T08:43:16Z" level=info msg="new leader elected: noldork3sm1"
time="2023-04-15T08:43:16Z" level=info msg="Node [noldork3sm1] is assuming leadership of the cluster"
^C
i5Js@raspiserver:~$ k get pod -n kube-system
NAME                                              READY   STATUS    RESTARTS   AGE
nginx-ingress-nginx-controller-6cd8b549d9-pzdkt   1/1     Running   0          23h
coredns-7c444649cb-2gszf                          1/1     Running   0          13h
metrics-server-7b67f64457-nv2tx                   1/1     Running   0          13h
kube-vip-ds-xj9d5                                 1/1     Running   0          57m
kube-vip-ds-d7n78                                 1/1     Running   0          57m
i5Js@raspiserver:~$ k logs --follow kube-vip-ds-xj9d5 -n kube-system
time="2023-04-15T08:42:42Z" level=info msg="Starting kube-vip.io [v0.5.12]"
time="2023-04-15T08:42:42Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2023-04-15T08:42:42Z" level=info msg="prometheus HTTP server started"
time="2023-04-15T08:42:42Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2023-04-15T08:42:42Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [plndr-svcs-lock], id [noldork3sm1]"
time="2023-04-15T08:42:42Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [noldork3sm1]"
I0415 08:42:42.386671       1 leaderelection.go:248] attempting to acquire leader lease kube-system/plndr-svcs-lock...
I0415 08:42:42.387562       1 leaderelection.go:248] attempting to acquire leader lease kube-system/plndr-cp-lock...
I0415 08:42:42.698608       1 leaderelection.go:258] successfully acquired lease kube-system/plndr-cp-lock
time="2023-04-15T08:42:42Z" level=info msg="Node [noldork3sm1] is assuming leadership of the cluster"
time="2023-04-15T08:42:42Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [192.168.1.120]"
I0415 08:42:42.705151       1 leaderelection.go:258] successfully acquired lease kube-system/plndr-svcs-lock
time="2023-04-15T08:42:42Z" level=info msg="starting services watcher for all namespaces"
time="2023-04-15T08:42:42Z" level=info msg="[service] adding VIP [192.168.1.122] for [dns-home/pihole-dns-udp] "
time="2023-04-15T08:42:42Z" level=info msg="[service] synchronised in 125ms"
time="2023-04-15T08:42:42Z" level=info msg="[service] adding VIP [192.168.1.122] for [dns-home/pihole-dns-tcp] "
time="2023-04-15T08:42:43Z" level=info msg="[service] synchronised in 116ms"
```
