### ISSUE TITLE
failed to renew ip - hardware address not found

### ISSUE THREAD

**Issue by kreeuwijk** [kube-vip/kube-vip#542]
**Describe the bug**
I have a cluster where kube-vip will successfully request an IP in `--ddns` mode, but at the 50% life of the lease it logs this error:
```
level=error msg="renew failed, error: got an error while processing the request: error writing packet to connection: hardware address not found"
```
and the lease does not get renewed. Eventually the lease expires and the cluster fails when the associated dynamic DNS record gets cleaned up. If kube-vip is manually restarted, it will request a fresh lease, but if the IP wasn't fixed through a reservation, a fresh IP can get assigned which messes up the etcd and kube-apiserver configuration.

I'm unable to determine what is causing the error and would like some pointers in the direction I should look.

**Expected behavior**
kube-vip should renew the address without issue, or provide better error message to indicate what the problem is.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04.5 LTS
 - Kubernetes Version: 1.24.10
 - Kube-vip Version: 0.5.12

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: eth0
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "true"
    - name: address
      value: cluster-name.domain-name.com
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.5.12
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```

**Additional context**
The host itself is also using a DHCP address.

We were originally using kubevip 0.4.0-v1beta1 and with that version I had the same issue but the error message was:
```
level=error msg="renew failed, error: create unicast client failed, error: unable to apply option: unable to start listening UDP port: listen udp4 :68: bind: address already in use, server ip: 0.0.0.0"
```
So I upgraded to the latest version but got the same problem, with a different error.
