### ISSUE TITLE
Unable to reach vip on the same subnet

### ISSUE THREAD

**Issue by tringler** [kube-vip/kube-vip#556]
**Describe the bug**
I spin up two Azure RHEL 8.6 instances and installed kube-vip on the 1st node by:
```
alias kube-vip="podman pull ghcr.io/kube-vip/kube-vip:v0.5.12; podman run --rm ghcr.io/kube-vip/kube-vip:v0.5.12 manifest pod"

kube-vip manifest pod \
    --interface eth0 \
    --address 172.20.0.200 \
    --controlplane \
    --services \
    --arp \
    --leaderElection | sudo tee /etc/kubernetes/manifests/kube-vip.yaml
```
I successfully built the kubernetes cluster with `sudo kubeadm init --control-plane-endpoint=172.20.0.200 --pod-network-cidr=10.244.0.0/16`.

After that 172.16.0.200 is pingable locally on the 1st node. On the 2nd node inside the same subnet I'm unable to ping 172.20.0.200 neither I can reach 172.20.0.200:6443. From the 2nd node I am able to ping the physical IP of 1st node, but not the vip. I disabled firewalld so it should be not an iptables issue.

Any ideas?

Thanks in Advance!

**Environment:**
 - OS/Distro: RHEL 8.6
 - Kubernetes Version: 1.27.1
 - Kube-vip Version: 0.5.12

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: eth0
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 172.20.0.200
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.5.12
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
