### ISSUE TITLE
Lease is not removed when service is removed

### ISSUE THREAD

**Issue by EmielBruijntjes** [kube-vip/kube-vip#590]
**Describe the bug**
When removing a service, the associated lease is not removed.

**To Reproduce**
Run kube-vip with these settings as a DaemonSet:
```
image: ghcr.io/kube-vip/kube-vip:v0.6.0
args:
- manager
env:
- name: svc_enable          # monitor services of type "loadbalancer"
  value: "true"
- name: svc_election        # each service should have its own leader
  value: "true"
- name: lb_class_only       # only monitor services with a "loadbalancerClass" property
  value: "true"
- name: lb_class_name       # the loadbalancerClass must be set to "internal"
  value: "internal"
- name: vip_arp             # use arp (meaning: assign the IP address to one of the nodes
  value: "true"
- name: vip_leaseduration   # seconds a lease is held for
  value: "10"
- name: vip_renewdeadline   # seconds a leader can attempt to renew
  value: "5"
- name: vip_retryperiod     # number of seconds a leader will hold the lease for
  value: "2"
```
Create a service:
```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: mynamespace
spec:
  type: LoadBalancer
  loadBalancerClass: internal
  loadBalancerIP: "10.32.59.10"
  selector:
    app: whatever
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
```
Then remove the service
```
$ kubectl delete service -n mynamespace test
```
Check if the lease that is associated with the service has been removed:
```
$ kubectl get lease -n mynamespace
NAME           HOLDER                AGE
kubevip-test   server1233            18m
```

**Expected behavior**
The lease should be removed

**Environment:**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: v1.25.3
 - Kube-vip Version: 0.6.0

**Additional context**
This might be part of a more generic problem with leases:
- When the service is re-added (and the lease becomes necessary again) the VIP is no longer picked up by a node.
- When the lease is manually removed, it is automatically recreated (so one or more kube-vip instances still *think* it is relevant)

**Current workaround**
- Remove the kube-vip daemonset
- Remove lease manually
- Recreate the kube-vip daemonset
