### ISSUE TITLE
[0.6.1] -> [0.6.2] Causing loadbalancer to stop, release virtual ip, re-add then repeat causing high CPU usage

### ISSUE THREAD

**Issue by atropos112** [kube-vip/kube-vip#604]
**Describe the bug**
After updating from v0.6.1 to v0.6.2 I noticed CPU usage of traefik pods as well as of kube-vip pods has drastically increased, my kube-vip resource per pod are

```yaml
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

they are not huge, but before it would never get even close to reaching the resource usage provided (it would use abuout 3-5m and 5-15Mi). After updating to 0.6.2 i started seeing these logs 

```
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:26Z" level=info msg="[service] synchronised in 60ms"
time="2023-08-27T08:57:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:26Z" level=info msg="[service] synchronised in 26ms"
time="2023-08-27T08:57:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:26Z" level=info msg="[service] synchronised in 119ms"
time="2023-08-27T08:57:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:26Z" level=info msg="[service] synchronised in 23ms"
time="2023-08-27T08:57:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:26Z" level=info msg="[service] synchronised in 93ms"
time="2023-08-27T08:57:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:26Z" level=info msg="[service] synchronised in 27ms"
time="2023-08-27T08:57:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:26Z" level=info msg="[service] synchronised in 23ms"
time="2023-08-27T08:57:26Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-08-27T08:57:26Z" level=info msg="[VIP] Releasing the Virtual IP [9.0.0.190]"
time="2023-08-27T08:57:26Z" level=info msg="Removed [ce2c96e8-6628-476d-a37e-0b1b2369f1f0] from manager, [0] advertised services remain"
time="2023-08-27T08:57:26Z" level=info msg="[service] adding VIP [9.0.0.190] for [platform/traefik]"
time="2023-08-27T08:57:27Z" level=info msg="[service] synchronised in 30ms"
```
which is clear that load balancers are stopped and started, I dont have much expertise here but I know its different to 0.6.1 and i have a suspicion this is the cause of high CPU usage (relatively to 0.6.1).

**To Reproduce**
Update to v0.6.2 and have traefik exposed as a load balancer.

**Expected behavior**
Not have my kube-vip and traefik usage at 100% cpu at all times

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: 1.27.1
 - Kube-vip Version: 0.6.1 / 0.6.2 

**`Kube-vip.yaml`:**
```yaml
image:
  repository: ghcr.io/kube-vip/kube-vip
  pullPolicy: Alway
  tag: v0.6.1

config:
  address: 9.0.0.110

env:
  vip_interface: eth0
  vip_arp: 'true'
  lb_enable: 'true'
  lb_port: '6443'
  cp_namespace: kube-system
  vip_cidr: '32'
  cp_enable: 'true'
  svc_enable: 'true'
  vip_leaseduration: '5'
  vip_renewdeadline: '3'
  vip_retryperiod: '1'
  vip_leaderelection: 'true'
  prometheus_server: :2112

fullnameOverride: kube-vip

tolerations: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

**Comment by atropos112** [comment]
This is still very much an issue (I am sticking to 0.6.1), is anyone able to look at this ?

**Comment by atropos112** [comment]
![image](https://github.com/kube-vip/kube-vip/assets/33070637/605e99b3-fdba-477f-b01a-22f59cb13320)
(orange is Traefik, purpleish is kube-vip)

This is on 0.6.4 (the jump that you can see on that graph is caused by me manually updating 0.6.1 -> 0.6.4)

**Comment by thebsdbox** [comment]
Can you attach any manifests and describe what is running? I can't recreate the same?

**Comment by atropos112** [comment]
I am using the chart from https://kube-vip.github.io/helm-charts with version 0.4.4 (of kube-vip chart)
with the following values.yaml
```yaml
image:
  repository: ghcr.io/kube-vip/kube-vip
  pullPolicy: Always
  tag: v0.6.1
  
config:
  address: 9.0.0.110

env:
  vip_interface: eth0
  vip_arp: 'true'
  lb_enable: 'true'
  lb_port: '6443'
  cp_namespace: kube-system
  vip_cidr: '32'
  cp_enable: 'true'
  svc_enable: 'true'
  vip_leaseduration: '5'
  vip_renewdeadline: '3'
  vip_retryperiod: '1'
  vip_leaderelection: 'true'
  prometheus_server: :2112

fullnameOverride: kube-vip

tolerations: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```
Notice non-standard address in config.address (it really shouldn't cause issues I woudn't think). Changing tag: v0.6.1 to say `tag: v0.6.2` or `tag: v0.6.4` causes the effect i show above. Note that on `tag: v0.6.4` I am not seeing the log messages (which i did in `tag: v0.6.2`). I am unsure if
- There is a regression in v0.6.2 for my setup
- My current setup has some missconfiguration or otherwise that has been highlighted by the 0.6.2 update
I can't exclude the latter but I am in the process of moving my nodes to new setup (which utilizes nixos instead of ubuntu), I would be keen to try to bump 0.6.1 -> 0.6.4 once I have moved everything this would certainly be a good test to see "was it the setup", I will come back here in a week or so with my findings.
