### ISSUE TITLE
External IP not attached to loadbalancer when `externalTrafficPolicy: Local` [0.6.2]

### ISSUE THREAD

**Issue by starizard** [kube-vip/kube-vip#608]
**Describe the bug**

When `svc_election: true` and `externalTrafficPolicy: Local` is set, the loadbalancer IP remains Pending

**To Reproduce**
1. Generate Manifest using: 
```
kube-vip manifest daemonset \
    --interface ens160 --taint --inCluster \
    --address 10.255.3.250 \
    --controlplane \
    --services \
    --arp \
    --servicesElection \
    --leaderElection 
```
3. create a service with `externalTrafficPolicy: Local`
4. Loadbalancer's external IP remains Pending

**Expected behavior**
Expect the IP to be provisioned

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1]
 - Kubernetes Version: [e.g. v1.23.15]
 - Kube-vip Version: [e.g. 0.6.2]

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.6.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.6.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: _VIPINTERFACE_
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: svc_election
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: _VIPADDRESS_
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /etc/kubernetes/admin.conf
          name: kubeconfig
      hostAliases:
      - hostnames:
        - kubernetes
        ip: 127.0.0.1
      hostNetwork: true
      serviceAccountName: kube-vip
      volumes:
      - hostPath:
          path: /etc/kubernetes/admin.conf
        name: kubeconfig
  updateStrategy: {}

```
**Additional context**

Couldn't find documentation on this, but will svc_election work when the NodeAffinity restricts kube-vip to master pods only?
