### ISSUE TITLE
Kube-VIP does not work as DaemonSet with interfaces configured by `altname` property

### ISSUE THREAD

**Issue by stefan-lange** [kube-vip/kube-vip#609]
**Describe the bug**
Maybe it is a bug, maybe it is an edge case. I am also interested in (different) solutions of other users.

Given are 3 nodes with `different interface names`, e.g. `eth0`, `enp0s31f6` and `eno1`. Kube-VIP should be created via DaemonSet.

Potential solution: give all vip interfaces the same `altname` (e.g. kubevip) and use it during config creation.

**To Reproduce**

```sh
VIP_INTERFACE_ALT_NAME=kubevip

# on node1
VIP_INTERFACE=eth0
ip link property add dev $VIP_INTERFACE altname $VIP_INTERFACE_ALT_NAME

# on node2
VIP_INTERFACE=enp0s31f6
ip link property add dev $VIP_INTERFACE altname $VIP_INTERFACE_ALT_NAME

# on node3
VIP_INTERFACE=eno1
ip link property add dev $VIP_INTERFACE altname $VIP_INTERFACE_ALT_NAME

# get interface details (execute on all nodes)
ip addr show $VIP_INTERFACE_ALT_NAME
```

create kube-vip config (DaemonSet)

```sh
kube-vip manifest daemonset \
    --interface $VIP_INTERFACE_ALT_NAME \
    --address $VIP \
    ...
```

error message in kube-vip pod

```
time="2023-09-05T11:16:42Z" level=warning msg="failed to get interface \"kubevip\": route ip+net: no such network interface"
time="2023-09-05T11:16:45Z" level=warning msg="failed to get interface \"kubevip\": route ip+net: no such network interface"
time="2023-09-05T11:16:48Z" level=warning msg="failed to get interface \"kubevip\": route ip+net: no such network interface"
```

**Expected behavior**
Expect the IP to be provisioned on interface with altname `kubevip`

**Environment (please complete the following information):**
 - OS/Distro: Debian 12
 - Kubernetes Version: v1.27.4+k3s1
 - Kube-vip Version: 0.6.2

**`Kube-vip.yaml`:**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.6.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.6.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: kubevip
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.133.7.40
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
