### ISSUE TITLE
kube-vip ha doesn't work with edit lb_port

### ISSUE THREAD

**Issue by cyclinder** [kube-vip/kube-vip#610]
**Describe the bug**

I changed the lb_port from 6443 to 16443, Only the leader node has IPVS rules, and only the leader can access the api-server via `VIP:lb_port`. Note: api-server's port is 6443.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1804]
 - Kubernetes Version: [e.g. v.1.18]
 - Kube-vip Version: [e.g. 0.2.3]

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-vip
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "True"
    - name: port
      value: "6443"
    - name: lb_port
      value: "16443"
    - name: lb_fwdmethod
      value: "masquerade"
    - name: vip_loglevel
      value: "5"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "False"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: "10.70.16.100"
    - name: lb_enable
      value: "true"
    image: 10.70.8.100:8090/kubespray/kube-vip/kube-vip:v0.6.2
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**
