### ISSUE TITLE
Kube-VIP split brain v0.6.3

### ISSUE THREAD

**Issue by QuinnBast** [kube-vip/kube-vip#665]
**Describe the bug**
Kube-VIP is getting split brain when managing both the control plane and service VIP at the same time - resulting in two host machines being assigned ownership of the same IP.

**To Reproduce**
1. Run one kube-vip instance with both `cp_enable` and `svc_enable` true.
```
containers:
        - args:
            - manager
          env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_interface
              value: enp24s0f0
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: vip_ddns
              value: "false"
            - name: svc_enable
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
            - name: address
              value: 192.168.191.38
            - name: prometheus_server
              value: :2112
          image: ghcr.io/kube-vip/kube-vip:v0.6.3
```

2. Let kube-vip start up
3. Run `ip a` on the host of each machine claming leadership. Verify that `ip a` shows the IP address from kube-vip.
4. Manually `kubectl delete pod` on the `kube-vip` pod that is controlling one of the deployments. Wait for it to restart.
5. Verify that the two leases in the cluster are now managed by different hosts with `kubectl get leases`.
6. Once the leases are different - run an `ip a` your hosts in the cluster and verify that two hosts are controlling the same IP address:

Host 1 has `192.168.191.38`:
```
4: enp24s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.191.35/24 brd 192.168.191.255 scope global enp24s0f0
       valid_lft forever preferred_lft forever
    inet 192.168.191.38/32 scope global enp24s0f0
       valid_lft forever preferred_lft forever
```

Host 2 has `192.168.191.38`:
```
4: enp24s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.191.36/24 brd 192.168.191.255 scope global enp24s0f0
       valid_lft forever preferred_lft forever
    inet 192.168.191.38/32 scope global enp24s0f0
       valid_lft forever preferred_lft forever
```

You can also verify that the kube-vip logs on host 1 and host 2 both indicate that they think they are the leader:

Host 1 kube-vip logs (after host 1 was deleted):
```
time="2023-11-16T21:42:19Z" level=info msg="Starting kube-vip.io [v0.6.3]"
time="2023-11-16T21:42:19Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2023-11-16T21:42:19Z" level=info msg="prometheus HTTP server started"
time="2023-11-16T21:42:19Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2023-11-16T21:42:19Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [kube-vip-enp24s0f0], id [tgrm-ic-qa1-1]"
I1116 21:42:19.125472       1 leaderelection.go:245] attempting to acquire leader lease kube-system/kube-vip-enp24s0f0...
time="2023-11-16T21:42:19Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [tgrm-ic-qa1-1]"
I1116 21:42:19.125820       1 leaderelection.go:245] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2023-11-16T21:42:19Z" level=info msg="Node [tgrm-ic-qa1-2] is assuming leadership of the cluster"
I1116 21:42:19.141591       1 leaderelection.go:255] successfully acquired lease kube-system/kube-vip-enp24s0f0
time="2023-11-16T21:42:19Z" level=info msg="starting services watcher for all namespaces"
time="2023-11-16T21:42:19Z" level=info msg="[service] adding VIP [192.168.191.38] for [kube-system/rke2-ingress-nginx-controller]"
time="2023-11-16T21:42:19Z" level=info msg="[service] synchronised in 17ms"
```

You can see after node 1 restarted, at `21:42:19` host 1 thinks it got the lease with: "successfully acquired lease kube-system/kube-vip-enp24s0f0".

However, The host 2 kube-vip logs:
```
time="2023-11-16T20:54:15Z" level=info msg="Starting kube-vip.io [v0.6.3]"
time="2023-11-16T20:54:15Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2023-11-16T20:54:15Z" level=info msg="prometheus HTTP server started"
time="2023-11-16T20:54:15Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2023-11-16T20:54:15Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [kube-vip-enp24s0f0], id [tgrm-ic-qa1-2]"
I1116 20:54:15.133469       1 leaderelection.go:245] attempting to acquire leader lease kube-system/kube-vip-enp24s0f0...
time="2023-11-16T20:54:15Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [tgrm-ic-qa1-2]"
I1116 20:54:15.133762       1 leaderelection.go:245] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2023-11-16T20:54:15Z" level=info msg="new leader elected: tgrm-ic-qa1-1"
I1116 20:54:15.151491       1 leaderelection.go:255] successfully acquired lease kube-system/plndr-cp-lock
time="2023-11-16T20:54:15Z" level=info msg="Node [tgrm-ic-qa1-2] is assuming leadership of the cluster"
time="2023-11-16T20:54:15Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [192.168.191.38]"
```

We can see "Node 2 is assuming leadership of the cluster" at `20:54:15` but at `21:000` or later, there are no logs indicating that Node 2 recognizes that host 1 re-claimed the lease. Node 2 continues to think it is in control of the lease.

Finally, we can verify that node-3 also thinks that node-1 re-joined the cluster but node-2 was not aware:

Host 3 kube-vip logs:
```
time="2023-11-16T20:54:55Z" level=info msg="Starting kube-vip.io [v0.6.3]"
time="2023-11-16T20:54:55Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2023-11-16T20:54:55Z" level=info msg="prometheus HTTP server started"
time="2023-11-16T20:54:55Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2023-11-16T20:54:55Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [kube-vip-enp24s0f0], id [tgrm-ic-qa1-3]"
I1116 20:54:55.774253       1 leaderelection.go:245] attempting to acquire leader lease kube-system/kube-vip-enp24s0f0...
time="2023-11-16T20:54:55Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [tgrm-ic-qa1-3]"
I1116 20:54:55.774609       1 leaderelection.go:245] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2023-11-16T20:54:55Z" level=info msg="Node [tgrm-ic-qa1-2] is assuming leadership of the cluster"
time="2023-11-16T20:54:55Z" level=info msg="new leader elected: tgrm-ic-qa1-1"
```

The last 2 lines show that node-3 saw node 2 become the leader, but then immediately after (once qa1 came back online), node 3 saw host 1 take control of the lease.

Note: Because of two machines sharing the same IP address, this ends up resulting in us getting regular timeout and stream disconnected broken pipe issues. For example, while doing a `docker push` command, if kube-vip has a split brain, the docker push will fail with:

> use of closed network connection

Or, if using k9s, we will get various other errors like:

> 😡 [list watch] access denied on resource "grafana":"v1/pods"

Or, 

> 😡 Post "https://192.168.191.38:6443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": read tcp 192.168.191.38:33010->192.168.191.38:6443: read: connection reset by peer

Or, while streaming logs with `kubectl logs -f`, we can only stream the logs for less than a second before getting

> error: read tcp 192.168.191.38:55986->192.168.191.38:6443: read: connection reset by peer

This is because the traffic initially goes to one host, but then future requests go to a different host and cause errors with the traffic flow.

**Expected behavior**
Kube-VIP should NOT have a split brain...

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version:  1.26.3+rke2r1
 - Kube-vip Version: 0.6.3

**`Kube-vip.yaml`:**

```
# This file was generated
# Generated from the documentation here: https://kube-vip.io/docs/installation/daemonset/

# Steps:
# 1. Add the RBAC rules from https://kube-vip.io/manifests/rbac.yaml
# 2. Use Version v0.5.12
# 3. `alias kube-vip="docker run --network host --rm ghcr.io/kube-vip/kube-vip:$KVVERSION"`
# 4. `kube-vip manifest daemonset --interface $INTERFACE --address $VIP --inCluster --controlplane --services --arp --leaderElection --taint`
#    Where:
#    --address is the Kubernetes API floating IP
#    --interface is the network interface to control (enp1s0 for the testbed)
#        Note: I left both these generic and filled them with ansible template variables
#    --inCluster Required as a daemonset
#    --taint Only runs on controlplanes
#    --arp Use arpping to control the leader
#    --services Also act as an in-cluster LoadBalancer
#    --leaderElection Perform leader election to select a master
#
# 5. This will dump a Manifest to the console. Append that with the RBAC rules above to create this file.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-enp24s0f0
    app.kubernetes.io/version: v0.5.12
  name: kube-vip-enp24s0f0
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-enp24s0f0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-enp24s0f0
        app.kubernetes.io/version: v0.5.12
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - args:
            - manager
          env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_interface
              value: enp24s0f0
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: vip_ddns
              value: "false"
            - name: svc_enable
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
            - name: address
              value: 192.168.191.38
            - name: prometheus_server
              value: :2112
          image: ghcr.io/kube-vip/kube-vip:v0.6.3
          imagePullPolicy: IfNotPresent
          name: kube-vip
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services", "services/status", "nodes", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
  - kind: ServiceAccount
    name: kube-vip
    namespace: kube-system
```

**Additional context**

The lease in `kubectl get lease` also shows that node 1 holds the lease, yet host 2 is still controlling the IP.

![Screenshot from 2023-11-16 16-01-53](https://github.com/kube-vip/kube-vip/assets/22599103/78a908b5-a390-402a-911e-115fabd56743)

**Comment by QuinnBast** [comment]
Potentially a duplicate of https://github.com/kube-vip/kube-vip/issues/665

**Comment by QuinnBast** [comment]
Update: I just did some more investigation and it turns out that we are hitting this issue much more often than we originally thought we were. I've updated the original post. It also turns out that this is not only an issue when deploying 2 kube-vip, this is an issue for EVERY deployment of kube-vip and causes kube-vip to be unstable and unreliable for a production setting!

**Comment by thebsdbox** [comment]
Very peculiar, the separate leases should ensure that one kube-vip instance ignores the other. I'll need to update the testing to generate the same configuration.

**Comment by QuinnBast** [comment]
I think i figured out the real issue.
It's not that there is a split-brain -- it's that there are two different leases.

There is one lease for the control plane, and there is one lease for the service masters. If two different VIPs get control of each lease, then it is game over.

As an attempt to naturally fix the issue, I just restarted one of the kube-VIP instances that was in contention for the IP address, but when it restarted I found this:

```
Node [gx-k8s-testbed-node-1] is assuming leadership of the cluster
new leader elected: gx-k8s-testbed-node-2
```

And `kubectl get leases`:
```
kube-system       plndr-cp-lock                                    gx-k8s-testbed-node-1                                                            200d
kube-system       plndr-svcs-lock                                  gx-k8s-testbed-node-2                                                            200d
```

I think that both leases are advertising the kube-vip IP address from the owner of the lease. `plndr-cp-lock` makes node-1 think it has control of the IP address for the control-plane and therefore it advertises the IP address. But `plndr-svcs-lock` makes node-2 think it has control of the IP address to ingress incoming service traffic and so it also advertises the IP address, resulting in 2 hosts advertising the same IP address.

**Comment by QuinnBast** [comment]
Yes, this appears to be the issue.

I manually edited one of the leases to make both lease owners the same. I ran `kubectl edit lease plndr-svcs-lock -n kube-system` (which was held by node-2) and changed the lease YAML to change the holder identity to node 1:

```
spec:
  holderIdentity: gx-k8s-testbed-node-1
```

And after this got applied, my cluster was fixed and I was no longer getting timeouts or stream disconnects.

**Comment by QuinnBast** [comment]
Same here. I've been hoping that the maintainers get to this but haven't seen any priority put on this. I'm surprised more people are being hit by this...

**Comment by comminutus** [comment]
I wish I could help diagnose it but I'm not even sure where to start.

**Comment by lubronzhan** [comment]
Hi @QuinnBast @comminutus 

I think it's intentional that service and control plane logic use different leases since they are two set of functionalities, and it can help distribute the IP load on different hosts between these two functionalities.

BTW, since this commit you should be able to configure your service lease name https://github.com/kube-vip/kube-vip/commit/e41abf0f88ef3556c3400abfb68572559ba1fe0a to the same name as you control plane lease name, using svc_leasename variable or plndr-svcs-lock flag. It's in 0.6.4 and 0.6.3. I still have concern that once you delete the service, the logic will also try to remove that IP from the VM, then it might impact the control plane HA. Not sure have you tried that.

>Is there any reason why there are two leases, or, more importantly, why each lease is broadcasting the IPs at L2? I guess the answer to this is because the service lease needs to handle CIDR pools and/or DHCP so would need to broadcast IPs at L2 for newly assigned IPs from the pool.

Yes, service type lb's ip is also broadcast through L2 if you configure ARP mode.

> Maybe we can make it so that the service lease doesn't do an L2 advertisement for IPs that match the --address CLI/env param if it exists? This should prevent clobbering the control plane IP

How do you allocate IP to service type loadbalancer though, do you use kube-vip-cloud-provider? The problem of using kube-vip-cloud-provider is that it's just responsible to blindly assigning ip to service type lb from a pool, it doesn't care about what's the control plane endpoint. Even though kube-vip can stop advertising that IP, it still need to inform kube-vip-cloud-provider that it shouldn't allocate that IP to that service, instead of just stoping advertising twice. This sounds more like a hack. instead of proper fix.

Supporting same IP address shared between control plane HA and services I think it would be more complicated than that. Since you need to think how many services will you create, do they all share the same VIP? Then if there are multiple services, how can k8s route the traffic to correct backend pod, especially if they share the same port. Also how to take care of deleting service would need some different logic to skip deleting VIPs like I mentioned above.

So rather than claiming support it, we should explicitly state that this is not supported, since there are many implications if enabling it. I think you can just use svc_leasename variable or plndr-svcs-lock flag to achieve the same goal for now if you really want to use same IP for service and control plane endpoint

And we could also do either of followings:
 
1. Ask user not to include the control plane endpoint inside the pool of kube-vip-cloud-provider in kube-vip-cloud-provider doc.
1. if kube-vip-cloud-provider selects an ip that's used by control plane endpoint advertised by kube-vip, let kube-vip make an annotation/condition on the service, indicating that that IP is invalid, please reselect. Then kube-vip-cloud-provider could choose a different ip. Keep that IP in a cache so it could skip it next time when selecting IPs. If user doesn't use kube-vip-cloud-provider to allocate 
1. add a new field `exclude-cidr-global` or `exclude-iprange-global` to configmap of kube-vip-cloud-provider so that user could add control plane endpoint directly in that group, without having to change their existing cidrs or ipranges settings.

What's your thought cc @thebsdbox ?

**Comment by comminutus** [comment]
This is enlightening @lubronzhan , I didn't realize this configuration wasn't really supported.  I'll have to rethink the few clusters I maintain with this configuration and see if I can rebuild them to separate out the control plane IP from the service(s) IP(s).

**Comment by QuinnBast** [comment]
Good point about the `kube-vip-cloud-provider`. I don't use this component so I'm not really sure about the implications of using this.

Typically the workflow for my clusters is to just do something like this:

```
type: Service
spec:
    kind: LoadBalancer
    loadBalancerIP: <MyFloatingIPAddress>
```

Where I manually specify the `ladBalancerIP` on each of the services in my cluster. In my case, `MyFloatingIPAddress` is also the IP of the control plane. We make sure to ensure that services exposed on these IPs don't use the same ports. I would say that if people are using `kube-vip-cloud-provider` to allocate IP addresses from a pool or CIDR range, then this isn't an issue for them, as they can just make the cloud-provider's pool or CIDR range exclude the control plane IP, as having a pool of IPs to allocate from means they probably wouldn't have a need to share the control plane and service IPs anyway (though correct me if I'm wrong, I don't really know what `kube-vip-cloud-provider` does).

> since this commit you should be able to configure your service lease name https://github.com/kube-vip/kube-vip/commit/e41abf0f88ef3556c3400abfb68572559ba1fe0a to the same name as you control plane lease name, using svc_leasename variable or plndr-svcs-lock flag. But I assume it might not work since you can't start two leases with same names.

This could be the solution, honestly. I will try this out and as long as it doesn't fail when attempting to create the second lease with the same name then I think this should work. If it does fail when attempting to create the new lease, maybe the fix is to just do something like this:

```
if (svc_leasename in k8s.getLeases()) {
   // skip creation of the lease
} else {
  k8s.createLease(svc_leasename)
}
```
