### ISSUE TITLE
Issue with proxy (Ingress-Nginx) and externalTrafficPolicy to preserve source IP

### ISSUE THREAD

**Issue by aerott** [kube-vip/kube-vip#666]
**Describe the bug**
Hello people,
I might be doing something wrong, but I'm having issues with following setup:

+) **kube-vip** 
-- static Pod
-- svc_enable & svc_election =true
+) **Ingress Nginx** 
-- externalTrafficPolicy =true (Local)

This is being implemented in an 'on-premises' environment.

This is the on-premises environment.

The recap is that I don't see any errors anywhere (on kube-vip, svc, events, etc.), but the Ingress Nginx just doesn't respond (as if the IP address wasn't assigned to this service).

I've also tried using different versions of kube-vip, but with no success.

**Screenshots**
These are screenshots with some logs:
![kube-vip-1](https://github.com/kube-vip/kube-vip/assets/73528004/795d9077-5696-4c48-9b12-96b2394d4cdb)

**Environment (please complete the following information):**
 - OS/Distro: `Ubuntu 2204`
 - Kubernetes Version: `v.1.28.2` (kubeadm; 3 CP nodes)
 - Kube-vip Version: `0.5.12` or `0.6.3`

**`Kube-vip.yaml`:**
```makefile
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: eth0
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: svc_election
      value: "true"
    - name: svc_leasename
      value: "kube-vip-eth0"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 170.18.1.120
    image: ghcr.io/kube-vip/kube-vip:v0.5.12
    imagePullPolicy: Always
	name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
``` 

**Additional context**
My goal is to set up an Ingress-Nginx configuration that will preserve the source IP address.

**Comment by reefland** [comment]
Trying to solve the same problem with Traefik.  No luck yet.  I get the IP of the Traefik POD not the client IP.

Did you review [Kube-VIP External Traffic Policy](https://kube-vip.io/docs/usage/kubernetes-services/#external-traffic-policy-kube-vip-v050) where it says to add:
```
- name: enableServicesElection
    value: "true"
```

I didn't see that in your provided configuration, and set  `externalTrafficPolicy: Local` on the LB?

**Comment by aerott** [comment]
I think `enableServicesElection` flag is equal `svc_election` (please look here: https://github.com/kube-vip/kube-vip/issues/455#issuecomment-1661553194 ).

My Ingress-Nginx (proxy) configuration is:
```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
  --create-namespace \
  --namespace ingress-basic \
  --set controller.replicaCount=2 \
  --set controller.service.type=LoadBalancer \
  --set controller.service.loadBalancerIP=170.18.1.121 \
  --set controller.service.externalTrafficPolicy=Local
```

**Comment by gielvandanu** [comment]
I have the same problem. If I deploy the ingress nginx using helm with default mode (using externalTrafficPolicy=Cluster) it gets the IP for the services. But if I add the `--set controller.service.externalTrafficPolicy=Local` flag when deploy, pending,

![image](https://github.com/kube-vip/kube-vip/assets/12169544/31525dd4-fa94-4b1d-8be2-833fc1de758c)


But the service describe shows it gives the IP address :
` kubectl -n ingress-nginx describe service/ingress-nginx-controller
Name:                     ingress-nginx-controller
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/component=controller
                          app.kubernetes.io/instance=ingress-nginx
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/part-of=ingress-nginx
                          app.kubernetes.io/version=1.9.4
                          helm.sh/chart=ingress-nginx-4.8.3
                          implementation=kube-vip
Annotations:              kube-vip.io/loadbalancerIPs: 10.66.250.16
                          meta.helm.sh/release-name: ingress-nginx
                          meta.helm.sh/release-namespace: ingress-nginx
Selector:                 app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.100.50.132
IPs:                      10.100.50.132
IP:                       10.66.250.16
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  31148/TCP
Endpoints:                10.244.4.24:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  32675/TCP
Endpoints:                10.244.4.24:443
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30869
Events:
  Type    Reason                Age                From                Message
  ----    ------                ----               ----                -------
  Normal  EnsuringLoadBalancer  61s (x2 over 62s)  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   61s (x2 over 61s)  service-controller  Ensured load balancer
  Normal  LoadbalancerIP        61s                service-controller  -> 10.66.250.16`

**Comment by d-uzlov** [comment]
Could this be related to node names, like in that issue?
- https://github.com/kube-vip/kube-vip/issues/608

Kube-vip advertises `Local` services from nodes where relevant pods are present.
When k8s node name didn't match `hostname` output, kube-vip couldn't check it, so it never advertised addresses.

Maybe fix for that issue broke something, or maybe it wasn't fully fixed.
I currently don't have any test clusters, so I can't check.

**Comment by aerott** [comment]
@d-uzlov 
I'm not sure if I'm understanding the #608 issue related to hostname well, but I think it is a little different case.

My node name: 
![image](https://github.com/kube-vip/kube-vip/assets/73528004/e41b2984-8494-41d1-b31f-406dc67c8b2c)

My hostname:
![image](https://github.com/kube-vip/kube-vip/assets/73528004/dff7d77d-577b-48dd-bc09-5790bee78657)

**Comment by sematula** [comment]
Having the same issue. When externalTrafficPolicy is set to cluster, no problems. When set to local, services get stuck in pending. Tried with 5.11 and 6.4. My node names and hostnames are identical, and no fqdn is set. This is a local bare metal cloud built on Ubuntu 22.04 and microk8s.

**Comment by Cellebyte** [comment]
FYI. We got a small fix merged which fixes the shortName lookup for hosts which have no fqdn set.

* hostname.example.com was working
* hostname was not working.

Fix was -> #724 and my issue was #723

**Comment by aerott** [comment]
@Cellebyte - Thank you for your FYI. As soon as the new image (version) is available, I will try to do a test.

**Comment by cyberops7** [comment]
Chiming in here to say that I'm seeing the same/similar issue.  After updating the kube-vip manifest with 
```
- name: svc_election
  value: "true"
  ```
  All sorts of things broke, including loadBalancer services stuck with External-IP pending.  As soon as I removed those lines from the manifest, the `kube-vip-ds` pods redeployed and everything came back online.

I saw this error frequently in the `kube-vip-ds-*` pod logs while it was in the broken state:
```
time="2024-01-30T06:27:26Z" level=error msg="[endpoint] unable to find shortname from k3s-m2"
```
My three kube-vip-ds pods are running on my 3 master nodes (`k3s-m{1..3}`), and each pod had the same errors logged with the respective shortname.

**Comment by Cellebyte** [comment]
@cyberops7 @aerott again, can you verify on your side if the latest release helps with your discovered issues?

**Comment by aerott** [comment]
> @cyberops7 @aerott again, can you verify on your side if the latest release helps with your discovered issues?

Unfortunately, it's still the same. I can't connect externally to Ingress Nginx, even though there are no visible errors anywhere.

Update note:
My K8s cluster is currently running with:
 - Kubernetes Version: `v.1.29.1` (kubeadm; 3 CP nodes)
 - Kube-vip Version: `0.7.0`

**Comment by Cellebyte** [comment]
Do you have the same deployment config as the person who created this issue? :)

**Comment by lholota** [comment]
@Cellebyte Good point, probably not, I use an ansible role to deploy the whole rke2 cluster including kube-vip. Kube-vip is running as a daemon set (manifest below) and the cloud controller is running as a StatefulSet (manifest below)

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-vip-ds
    k8slens-edit-resource-version: v1
    objectset.rio.cattle.io/hash: df8554deac08f5bfb609d09470da1244dab4a242
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
    spec:
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.7.0
          args:
            - manager
          env:
            - name: vip_arp
              value: 'true'
            - name: vip_interface
              value: vmbr0
            - name: port
              value: '6443'
            - name: vip_cidr
              value: '24'
            - name: cp_enable
              value: 'true'
            - name: cp_namespace
              value: kube-system
            - name: vip_ddns
              value: 'false'
            - name: enableUPNP
              value: 'false'
            - name: svc_enable
              value: 'true'
            - name: svc_election
              value: 'true'
            - name: vip_leaderelection
              value: 'true'
            - name: vip_leaseduration
              value: '5'
            - name: vip_renewdeadline
              value: '3'
            - name: vip_retryperiod
              value: '1'
            - name: address
              value: 10.1.8.130
            - name: prometheus_server
              value: ':2112'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kube-vip
      serviceAccount: kube-vip
      hostNetwork: true
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      schedulerName: default-scheduler
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10

```


```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-vip
      component: kube-vip-cloud-provider
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-vip
        component: kube-vip-cloud-provider
    spec:
      containers:
        - name: kube-vip-cloud-provider
          image: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.8
          command:
            - /kube-vip-cloud-provider
            - '--leader-elect-resource-name=kube-vip-cloud-controller'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kube-vip-cloud-controller
      serviceAccount: kube-vip-cloud-controller
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: kube-vip-cloud-provider
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
```
