### ISSUE TITLE
Load does not take effect when load balancing apiserver with kube-vip

### ISSUE THREAD

**Issue by ii2day** [kube-vip/kube-vip#685]
**Describe the bug**
I have three control-plane nodes, installed kube-vip using manifest, when accessing the vip, the traffic is sent to the apiserver of the node where the vip is located, no load balancing is done.

**To Reproduce**

**Expected behavior**
Load balancing in effect

**Screenshots**
![image](https://github.com/kube-vip/kube-vip/assets/45119426/798db856-eeba-4c01-966f-55808d979fa5)

![image](https://github.com/kube-vip/kube-vip/assets/45119426/58eaed84-1b5b-4c26-bd7f-a0cf4a8f4347)

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1804]
 - Kubernetes Version: [e.g. v.1.18]
 - Kube-vip Version: [e.g. 0.2.3]

**`Kube-vip.yaml`:**
```yaml
# Inspired by https://github.com/kube-vip/kube-vip/blob/v0.5.11/pkg/kubevip/config_generator.go#L13
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-vip
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "False"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: "10.1.105.1"
    - name: lb_enable
      value: "true"
    image: 10.29.208.120:18082/daocloud-docker-v/cncp/ghcr.io/kube-vip/kube-vip:v0.5.12
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**
