### ISSUE TITLE
kube-vip pod keeps failing "cannot assign requested address\n"

### ISSUE THREAD

**Issue by Ashkaan** [kube-vip/kube-vip#711]
**Describe the bug**
1x of my kube-vip pods keeps failing with this message:
`level=fatal msg="listen:listen tcp 10.1.0.131:9090: bind: cannot assign requested address\n"`

**To Reproduce**
1. Run kube-vip and kube-vip-cloud-providor
2. Observe the 1x out of 3x kube-vip pods keeps restarting

**Expected behavior**
All 3x pods work without error.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04 LTS
 - Kubernetes Version: v1.28.4+k3s2
 - Kube-vip Version: v0.6.4

**`Kube-vip.yaml`:**
```yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/version: "v0.6.4"
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: "eth0"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: "kube-system"
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: bgp_enable
          value: "true"
        - name: bgp_routerinterface
          value: "eth0"
        - name: bgp_routerid
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: bgp_as
          value: "65001"
        - name: bgp_peeraddress
          value: "10.1.0.1"
        - name: bgp_peeras
          value: "65000"
        - name: address
          value: "10.1.0.101"
        - name: prometheus_server
          value: prometheus.home:9090
        - name: TZ
          value: America/Los_Angeles
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
There are 3x control-plane nodes (identically configured) and 5x worker nodes.  Again, 2x other pods are running great.

Here's the entire log:
```
time="2024-01-04T18:08:25Z" level=info msg="Starting kube-vip.io [v0.6.4]"
time="2024-01-04T18:08:25Z" level=info msg="namespace [kube-system], Mode: [BGP], Features(s): Control Plane:[true], Services:[true]"
time="2024-01-04T18:08:25Z" level=info msg="prometheus HTTP server started"
time="2024-01-04T18:08:25Z" level=info msg="Starting Kube-vip Manager with the BGP engine"
time="2024-01-04T18:08:25Z" level=info msg="Starting the BGP server to advertise VIP routes to BGP peers"
time="2024-01-04T18:08:25Z" level=fatal msg="listen:listen tcp 10.1.0.131:9090: bind: cannot assign requested address\n"
```
