### ISSUE TITLE
High Availability Not Working

### ISSUE THREAD

**Issue by Ashkaan** [kube-vip/kube-vip#714]
**Describe the bug**
It seems like kube-vip is only actually functioning on 1x node at a time.

**To Reproduce**
1. Configure kube-vip on 3x nodes
2. ssh the VIP and each node
3. reboot node 1
4. see a small blip in the ping to the VIP, but now it's solid again
5. reboot node 2
6. see a small blip in the ping to the VIP, but now it's solid again
7. reboot node 3
8. ping to VIP goes down for almost exactly the length of node 3 being down

**Expected behavior**
Pings should stay relatively stable while each node reboots.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04 LTS
 - Kubernetes Version: v1.28.4+k3s2
 - Kube-vip Version: 0.6.4

**`Kube-vip.yaml`:**
``` yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/version: "v0.6.4"
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: "eth0"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: "kube-system"
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: bgp_enable
          value: "true"
        - name: bgp_routerinterface
          value: "eth0"
        - name: bgp_routerid
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: bgp_as
          value: "65001"
        - name: bgp_peeraddress
          value: "10.1.0.1"
        - name: bgp_peeras
          value: "65000"
        - name: address
          value: "10.1.0.101"
        - name: prometheus_server
          value: prometheus.home:9090
        - name: TZ
          value: America/Los_Angeles
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
The entire cluster goes down each time node 3 goes down, every time.
