### ISSUE TITLE
Kube-VIP for Cilium KubeProxyReplacement - error retrieving resource lock kube-system/plndr-cp-lock: Get dial tcp 10.43.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by Divinii** [kube-vip/kube-vip#721]
**Describe the bug**
I wanted to deploy a RKE2 cluster with Rancher that uses Cilium as Container Network Plugin with KubeProxyReplacement. This requires a single VIP for Cilium to call the Kubernetes API which is why I tried to deploy kube-vip. kube-vip seems to not be able to call the kube api.

**To Reproduce**
1. Deploy Cluster with Rancher with Cilium set as cnp and kubeproxy disabled, i used following following addon-config:
```
hubble.enabled: true
hubble.relay.enabled: true
hubble.ui.enabled: true
bgpControlPlane.enabled: true
externalIPs.enabled: true
kubeProxyReplacement: true
k8sServiceHost: 10.48.1.1
k8sServicePort: 6443
```

2. Setup Kube-vip
```
kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
export VIP=10.48.1.1
export INTERFACE=ens192
export KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
alias kube-vip="ctr --address /run/k3s/containerd/containerd.sock image pull ghcr.io/kube-vip/kube-vip:$KVVERSION; ctr --address /run/k3s/containerd/containerd.sock run --rm --net-host ghcr.io/kube-vip/kube-vip:$KVVERSION vip /kube-vip"
mkdir -p ~/kubernetes/kubevip
kube-vip manifest daemonset \
    --interface ens192 \
    --address 10.48.1.1 \
    --inCluster \
    --taint \
    --controlplane \
    --arp \
    --leaderElection  | sudo tee ~/kubernetes/kubevip/kube-vip.yaml
kubectl apply -f ~/kubernetes/kubevip/kube-vip.yaml
```

**Expected behavior**
Kube-vip is able to announce the ip 10.48.1.1 as HA IP for the kubernetes API.

**Environment (please complete the following information):**
 - OS/Distro: Debian 12 on VMWare
 - Kubernetes Version: v1.27.7+rke2r2
 - Kube-vip Version: v0.6.4 (also tested v0.5.0)

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.6.4
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.6.4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens192
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.48.1.1
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

### Pod Logs
```
k logs kube-vip-ds-hxvpl -n kube-system
time="2024-01-10T17:27:40Z" level=info msg="Starting kube-vip.io [v0.6.4]"
time="2024-01-10T17:27:40Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2024-01-10T17:27:40Z" level=info msg="prometheus HTTP server started"
time="2024-01-10T17:27:40Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-01-10T17:27:40Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [c02-controlplane-01]"
I0110 17:27:40.481978       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
E0110 17:28:10.483002       1 leaderelection.go:332] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp 10.43.0.1:443: i/o timeout
```
### State of the cluster
```
k get pods -A
NAMESPACE       NAME                                                   READY   STATUS             RESTARTS         AGE
cattle-system   cattle-cluster-agent-5b4bbddfcb-x7kj4                  0/1     Pending            0                108m
kube-system     cilium-operator-7b5c57f775-9clz8                       0/1     Running            34 (5m51s ago)   108m
kube-system     cilium-operator-7b5c57f775-qgr5b                       0/1     Pending            0                108m
kube-system     cilium-rgbsv                                           0/1     Init:1/7           32 (5m43s ago)   108m
kube-system     cloud-controller-manager-c02-controlplane-01           0/1     CrashLoopBackOff   31 (59s ago)     109m
kube-system     etcd-c02-controlplane-01                               0/1     Running            24 (55s ago)     108m
kube-system     helm-install-rke2-cilium-mxn8x                         0/1     Completed          0                108m
kube-system     helm-install-rke2-coredns-qhvxt                        0/1     Completed          0                108m
kube-system     helm-install-rke2-metrics-server-dgc5x                 0/1     Pending            0                108m
kube-system     helm-install-rke2-snapshot-controller-crd-lxqmk        0/1     Pending            0                108m
kube-system     helm-install-rke2-snapshot-controller-rj2tj            0/1     Pending            0                108m
kube-system     helm-install-rke2-snapshot-validation-webhook-z2dn9    0/1     Pending            0                108m
kube-system     hubble-relay-6457d65f49-jrx2d                          0/1     Pending            0                108m
kube-system     hubble-ui-67b8976844-slqr9                             0/2     Pending            0                108m
kube-system     kube-apiserver-c02-controlplane-01                     1/1     Running            0                109m
kube-system     kube-controller-manager-c02-controlplane-01            0/1     CrashLoopBackOff   32 (58s ago)     109m
kube-system     kube-scheduler-c02-controlplane-01                     0/1     CrashLoopBackOff   28 (54s ago)     109m
kube-system     kube-vip-ds-hxvpl                                      1/1     Running            0                71s
kube-system     rke2-coredns-rke2-coredns-autoscaler-6f97df447-cw5d7   0/1     Pending            0                108m
kube-system     rke2-coredns-rke2-coredns-f6c9f9649-5tw9j              0/1     Pending            0                108m

```

**Comment by thebsdbox** [comment]
That's odd `10.43.0.1:443`, it looks like it should be `6443`

**Comment by Divinii** [comment]
Oh you are totally correct, I currently have no access to the cluster but will curl the IP asap. On my homelab Clusters (similar setup with rke2 but single master ergo no kube-vip) the kube api also listens on 6443. I will also try and specifi `--lbPort 6443`, but I think that will make no difference since my manifest already specifies:
```
        - name: port
          value: "6443"
```

**Comment by Divinii** [comment]
Okay, so I did some testing and found some similar issues. Please correct me if i am wrong with my assumptions.

Kube-vip tries to connect to the Kubernetes service, this is not possible because the container network plugin is not ready yet.
```
root@c02-controlplane-01:~# k get svc -o wide -A
NAMESPACE       NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE     SELECTOR
cattle-system   cattle-cluster-agent        ClusterIP   10.43.74.162    <none>        80/TCP,443/TCP   2d22h   app=cattle-cluster-agent
default         kubernetes                  ClusterIP   10.43.0.1       <none>        443/TCP          2d22h   <none>
```

```
root@c02-controlplane-01:~# curl https://10.43.0.1:6443
^C
root@c02-controlplane-01:~# curl https://10.43.0.1:443
^C
root@c02-controlplane-01:~# curl https://127.0.0.1:443
curl: (7) Failed to connect to 127.0.0.1 port 443 after 0 ms: Couldn't connect to server
root@c02-controlplane-01:~# curl https://127.0.0.1:6443
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I found this issue https://github.com/kube-vip/kube-vip/issues/454 and tried to add the host aliases to the manifest, this did not result in a change of the IP. Is it possible to manually set the IP and Port kube-vip tries to use to connect to the Kubernetes API? I´d need to set loadbalance https://127.0.0.1:6443 from each master as far as I understand it.

## Manifest with hostAliases
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.6.4
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.6.4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens192
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.48.1.1
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostAliases:
      - hostnames:
        - kubernetes
        ip: 127.0.0.1
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
## Logs
```
root@c02-controlplane-01:~# k logs kube-vip-ds-ffpx4 -n kube-system
time="2024-01-13T14:01:37Z" level=info msg="Starting kube-vip.io [v0.6.4]"
time="2024-01-13T14:01:37Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2024-01-13T14:01:37Z" level=info msg="prometheus HTTP server started"
time="2024-01-13T14:01:37Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-01-13T14:01:37Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [c02-controlplane-01]"
I0113 14:01:37.945457       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
E0113 14:02:07.946133       1 leaderelection.go:332] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp 10.43.0.1:443: i/o timeout
E0113 14:02:40.123820       1 leaderelection.go:332] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp 10.43.0.1:443: i/o timeout
E0113 14:03:12.180638       1 leaderelection.go:332] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp 10.43.0.1:443: i/o timeout
```

**Comment by Apsu** [comment]
Confirming that adding hostAliases worked in my cluster with Cilium as kube-proxy replacement and kube-vip as daemonset

**Comment by ashtonian** [comment]
In addition to:
```
      hostAliases:
      - hostnames:
        - kubernetes
        ip: 127.0.0.1
```

Need the config volume mount mount as well see https://github.com/kube-vip/kube-vip/issues/684

volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
```
```
      volumes:
      - hostPath:
          path: /etc/rancher/rke2/rke2.yaml
        name: kubeconfig
```

Working with rke2 ha, kube vop ha/control plane bgp, cilium bgp kube proxy replace.

**Comment by Apsu** [comment]
@ashtonian Confirmed, works for me in RKE2 HA, kube-vip ha/control plane, cilium kube-proxy replacement -- but in ARP mode (kube-vip and Cilium).

**Comment by Divinii** [comment]
@ashtonian Thank you for your reply, this worked perfectly. I think it might be great to put this into documentation, I will keep the issue open for now as a request for documenting this. If keeping the issue open is not wanted, I will close it. The full working manifest is here:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.6.4
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.6.4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens192
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.48.0.1
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /etc/kubernetes/admin.conf
          name: kubeconfig
      hostAliases:
      - hostnames:
        - kubernetes
        ip: 127.0.0.1
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/rancher/rke2/rke2.yaml
        name: kubeconfig
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Comment by P4R4DiSi4C** [comment]
I confirm, adding hostAliases and volumemount to K3S kubeconfig (/etc/rancher/k3s/k3s.yaml) worked.
K3S + Cilium (and kubeproxy replacement) + KubeVIP Daemonset with ARP

**Comment by BloodyIron** [comment]
I think this particular topic is tripping me up right now, and pretty sure I didn't spot it in the Documentation. Going to try this when I get a chance (literally running out of time as I type this).

So seriously thanks for everyone involved for this probably super handy-dandy info! :D

**Comment by BloodyIron** [comment]
Adding the volumeMounts and volumes declarations for RKE2 in the same way as @Divinii stated worked for me! 3x test k8s cluster, RK2 nodes, built and managed with Rancher v2.7.6. Yay! Thanks for all this info, very helpful!

**Comment by ashtonian** [comment]
So I think this is indeed a bug as the admin.conf shouldn't be needed for in cluster daemonset using the kube role manifests which allow the pod to use the role to auth with the kube api. I haven't been able to go through the code all the way but it sort of looks like it may work with a blank admin.conf file.  

I think the issue is somewhere in here
https://github.com/kube-vip/kube-vip/blob/6752dc0fdde98b56a137ecbbe56d50ef8dfe1a51/pkg/manager/manager.go#L93-L140

Part of leveraging this with rke2 is being able to deploy this with the manifests by placing them in `/var/lib/rancher/rke2/server/manifests/`. I'd like to figure out the proper way to use this without the kubeconfig in order to run kube-vip on the agents as well, where there is no kubeconfig file.

**Comment by ashtonian** [comment]
Yea, I can confirm after setting 
```yaml
        - name: vip_loglevel
          value: "5"
```
```sh
time="2025-03-04T06:29:28Z" level=debug msg="Using external Kubernetes configuration from incluster config."
```

That shows without the admin.conf path its going down this path on [L139](https://github.com/kube-vip/kube-vip/blob/6752dc0fdde98b56a137ecbbe56d50ef8dfe1a51/pkg/manager/manager.go#L139). 

Interesting on [L108](https://github.com/kube-vip/kube-vip/blob/6752dc0fdde98b56a137ecbbe56d50ef8dfe1a51/pkg/manager/manager.go#L108) there is a `kuberenetes:{config.port}` override which would theoretically allow it to connect. 

I'm not sure what should change or if an empty yaml file would work. Will try to test further.

**Comment by ashtonian** [comment]
So you do not need the kubeconfig mounted for in cluster config! Assuming you have a way to install the rolebindings and setup the service account you just need to set the env overrides. 

The [k8s.io/client-go/rest ](https://github.com/kubernetes/client-go/blob/ec8a292223d913dc635704c6d57959e1bc00290a/rest/config.go#L548) uses env variables to allow setting the kube host and port with     `KUBERNETES_SERVICE_HOST` and  `KUBERNETES_SERVICE_PORT`. 

Setting these works:
```yaml
       env:
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
    ...
      serviceAccountName: kube-vip
```
With this you do not need to set the admin.conf file or hostAliases for in cluster configs.

**Comment by Divinii** [comment]
@ashtonian I created a test cluster (rke2 v1.31.5+rke2r1) and was able to replicate the issue again. Your env variables worked perfectly to solve it! Cluster comes up and kubevip is able to talk to apiserver without volumemounts.

I was not able to find these env vars in documentation, I can make a PR in the Website repo under https://github.com/kube-vip/website/blob/main/content/docs/installation/flags.md if that is okay.

Manifest I used:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list","get","watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.6
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.6
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.201.10.16
        - name: prometheus_server
          value: :2112
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        image: ghcr.io/kube-vip/kube-vip:v0.8.6
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostAliases:
      - hostnames:
        - kubernetes
        ip: 127.0.0.1
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```
