### ISSUE TITLE
[Bug] BGP Mode does not advertise `externalTrafficPolicy: Local` correctly.

### ISSUE THREAD

**Issue by Cellebyte** [kube-vip/kube-vip#729]
**Describe the bug**
When I configure kube-vip as described in my Kube-vip.yaml.
Kube-vip announces all loadbalancer prefixes from all nodes regardless of the `externalTrafficPolicy`.
When I swap and enable `svc_election` the announcement is done from one node when `externalTrafficPolicy: Local`
and from all nodes when `externalTrafficPolicy: Cluster`. Unfortunately there should be one mode which also allows the correct announcement of Loadbalancer Services with the `externalTrafficPolicy: Local`. To allow anycast routing to work.
Probably #714 is related.
Probably #705  is also related.

**To Reproduce**
1. Configure a neighbor
2. Configure kube-vip to peer with it.
3. use the above environment to configure kube-vip
4. change the `svc_election` to `true`
5. get it working but not completely as it should

**Expected behavior**

externalTrafficPolicy: Local should be announced from any node hosting a valid endpoint when `svc_election` is disabled.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04.3 LTS
 - Kubernetes Version: 1.27.9
 - Kube-vip Version: v0.7.0+a2129b04df95acba81278af81ff5efd16a52f234+dualstack-support

**`Kube-vip.yaml`:**

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "4"
  labels:
    app.kubernetes.io/name: kube-vip-svc
    app.kubernetes.io/version: v0.7.0
  name: kube-vip-svc
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-svc
        app.kubernetes.io/version: v0.7.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_loglevel
          value: "4"
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: svc_enable
          value: "true"
        - name: svc_election
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_interface
          value: lo
        - name: bgp_enable
          value: "true"
        - name: disable_service_updates
          value: "true"
        - name: bgp_hold_time
          value: "3"
        - name: bgp_keepalive_interval
          value: "1"
        - name: bgp_sourceip
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: bgp_routerid
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: bgp_as
          value: "<myAS>"
        - name: bgp_peers
          value: <theirIP>:<theirAS>::false
        - name: prometheus_server
          value: :2112
        image: ghcr.io/cellebyte/kube-vip:v0.7.0-test.3
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 4
  updatedNumberScheduled: 3
 ```
