### ISSUE TITLE
VIP is lost when kubernetes control plane goes down

### ISSUE THREAD

**Issue by busyboy77** [kube-vip/kube-vip#732]
**Describe the bug**

I'm using kubernetes cluster using RKE2, with 1 Control Plane and 3 worker nodes. The idea is that the services running on nodes should remain available even if the kubernetes control plane goes down. However, this is not happening, after the control plane goes down ( power off simulated ) , the IP assigned to one of the worker node is removed from the VIP interface.

removing the `taint` switch for Kube-vip deployment should make the VIP be available from Workers only, however, in case the Kubernetes control plane goes down, the VIP is also lost after 5 minutes and the services are not made available.

**To Reproduce**

set VIP
```
export VIP=192.168.1.216
export INTERFACE=enp1s0
```
Deploy as DaemonSet

 ```curl https://kube-vip.io/manifests/rbac.yaml > /var/lib/rancher/rke2/server/manifests/kube-vip-rbac.yaml```
 ```/var/lib/rancher/rke2/bin/crictl -r "unix:///run/k3s/containerd/containerd.sock"  pull ghcr.io/kube-vip/kube-vip:latest```
```
CONTAINERD_ADDRESS=/run/k3s/containerd/containerd.sock  ctr -n k8s.io run \
--rm \
--net-host \
ghcr.io/kube-vip/kube-vip:latest vip /kube-vip manifest daemonset --arp --interface $INTERFACE --address $VIP --controlplane  --leaderElection --services --inCluster | tee /var/lib/rancher/rke2/server/manifests/kube-vip.yaml 
```

the VIP is assigned to one of the worker nodes, however, when the Control Plane goes down, the VIP on the Worker node is also gone and services become inaccessible after 5 minutes. ( VIP stays alive at Worker node for 5 minutes ) 

**Expected behavior**

In case the Kubernetes Cluster goes down, the VIP should remain accessible on any of the worker nodes

**Environment (please complete the following information):**
 - OS/Distro:  Ubuntu 2204
 - Kubernetes Version: 1.26
 - Kube-vip Version:  v0.6.4

**`Kube-vip.yaml`:**
```YAML
root@devops212:/var/lib/rancher/rke2/server/manifests# cat kube-vip.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.6.4
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.6.4
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens160
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.2.216
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

```

Any idea why the VIP is lost ( after 5 minutes ) when Kubernetes control plane goes down. however it should remain available on worker nodes.
