### ISSUE TITLE
kube-vip 0.7.0 causes nodes to lose connection and interfaces would lose IPs

### ISSUE THREAD

**Issue by Michaelpalacce** [kube-vip/kube-vip#752]
I am writing this, with the full understanding that it's very vague. I tried pretty much the whole day trying to debug what is happening and came to the realization that kube-vip was somehow causing node eth0 interfaces to lose connection. 

This lead to a bunch of other issues of course. I don't have the necessary knowledge to figure out what exactly was happening, but outside of connection loss, this was causing entire network slowdowns, and it was also affecting other devices not connected to k3s at all (like my phone's Wi-Fi).

**To Reproduce**
1. Set up a fresh cluster k3s v 1.29.0
2. Get values from [here](https://github.com/Michaelpalacce/HomeLab/blob/master/cluster/homelab/core/kube-vip/helm-release.yaml)
3. Helm install with provided values.

**Expected behavior**
Create a virtual ip that I can use

**Screenshots**
Can't do this now... at this point, I redid my cluster and restored all my backups. I realize this is not helpful, still deciding to post this if anyone else finds this.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu Server 20.04
 - Kubernetes Version: v.1.28.3, v.1.28.5, v.1.29.0
 - Kube-vip Version: 0.7.0 (works with 0.6.4)

**`Kube-vip.yaml`:**
```yaml
image:
    repository: ghcr.io/kube-vip/kube-vip
    tag: "v0.6.4"

config:
    address: "192.168.1.2"

env:
    vip_interface: ""
    vip_arp: "true"
    lb_enable: "true"
    lb_port: "6443"
    vip_cidr: "32"
    cp_enable: "true"
    svc_enable: "true"
    vip_leaderelection: "false"
```

**Comment by Michaelpalacce** [comment]
This is still observed with both 0.7.1 and 0.7.2, not sure if anything is changed... Essentially when I run these versions the whole cluster loses connection internally and etcd goes haywire trying to elect a new leader constantly

**Comment by Michaelpalacce** [comment]
Should be reopened @thebsdbox

**Comment by Cellebyte** [comment]
@Michaelpalacce you should not run cp_enable and lb enable with the same daemonset.

**Comment by Michaelpalacce** [comment]
So enabling leader election would solve the problem? Will try it out.

@Cellebyte if you can, can you please explain why this is a bad thing?

**Comment by Michaelpalacce** [comment]
This is what happens immediately:

![image](https://github.com/kube-vip/kube-vip/assets/17056014/418fb2fe-3468-41cb-af23-31f9bdfbaee0)

![image](https://github.com/kube-vip/kube-vip/assets/17056014/63ba0ff6-dc91-42ce-b02e-810825951c41)


![image](https://github.com/kube-vip/kube-vip/assets/17056014/6be694da-db78-4830-9229-d5bd4e844540)


This is what I went for:

```yaml
        image:
            repository: ghcr.io/kube-vip/kube-vip
            tag: "v0.7.2"

        config:
            address: "192.168.1.2"
        env:
            vip_interface: ""
            vip_arp: "true"
            lb_enable: "true"
            lb_port: "6443"
            vip_cidr: "32"
            cp_enable: "true"
            svc_enable: "true"
            vip_leaderelection: "true"
```
