### ISSUE TITLE
kube-vip v0.7.0 broken the control plane load balancing

### ISSUE THREAD

**Issue by W0n9** [kube-vip/kube-vip#755]
**Describe the bug**
After upgrade to kube-vip v0.7.0 from v0.6.4，kube-vip will be exited with error with enabled control plane load balancing.

**To Reproduce**
Enable `lb_enable` and upgrade to v0.7.0 from v0.6.4

**Expected behavior**
Works without errors.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Debian 12
 - Kubernetes Version: K3S v1.27.8+k3s2
 - Kube-vip Version: v0.7.0

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.7.0
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.7.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: enp1s0
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: svc_election
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: lb_enable
          value: "true"
        - name: lb_port
          value: "6443"
        - name: lb_fwdmethod
          value: local
        - name: address
          value: 192.168.1.50
        - name: prometheus_server
          value: :2112
        - name: EGRESS_CLEANUP
          value: 'true'
        - name: egress_withnftables
          value: 'true'
        image: plndr/kube-vip-iptables:v0.7.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
Logs v0.7.0
```python
time="2024-02-09T04:40:55Z" level=info msg="Starting kube-vip.io [v0.7.0]"
time="2024-02-09T04:40:55Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2024-02-09T04:40:55Z" level=info msg="prometheus HTTP server started"
time="2024-02-09T04:40:55Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-02-09T04:40:55Z" level=info msg="beginning watching services, leaderelection will happen for every service"
time="2024-02-09T04:40:55Z" level=info msg="(svcs) starting services watcher for all namespaces"
time="2024-02-09T04:40:55Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [dmz-app-master-1]"
I0209 04:40:55.564441       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2024-02-09T04:40:55Z" level=info msg="Node [dmz-app-master-2] is assuming leadership of the cluster"
time="2024-02-09T04:40:55Z" level=info msg="(svc election) service [rsyslog-forwarder], namespace [rsyslog], lock name [kubevip-rsyslog-forwarder], host id [dmz-app-master-1]"
I0209 04:40:55.601144       1 leaderelection.go:250] attempting to acquire leader lease rsyslog/kubevip-rsyslog-forwarder...
I0209 04:40:55.612949       1 leaderelection.go:260] successfully acquired lease rsyslog/kubevip-rsyslog-forwarder
time="2024-02-09T04:40:55Z" level=info msg="(svcs) adding VIP [[192.168.1.60]] for [rsyslog/rsyslog-forwarder]"
time="2024-02-09T04:40:55Z" level=info msg="[service] synchronised in 12ms"
I0209 04:41:01.744223       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-cp-lock
time="2024-02-09T04:41:01Z" level=info msg="Node [dmz-app-master-1] is assuming leadership of the cluster"
time="2024-02-09T04:41:01Z" level=info msg="Starting IPVS LoadBalancer"
time="2024-02-09T04:41:01Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2024-02-09T04:41:01Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [192.168.1.50]"
time="2024-02-09T04:41:01Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2024-02-09T04:41:01Z" level=error msg="Error querying backends file does not exist"
time="2024-02-09T04:41:01Z" level=error msg="Unable to create an IPVS service, ensure IPVS kernel modules are loaded"
time="2024-02-09T04:41:01Z" level=fatal msg="IPVS service error: netlink receive: invalid argument"
```

Logs v0.6.4
```python
time="2024-02-09T06:42:41Z" level=info msg="Starting kube-vip.io [v0.6.4]"
time="2024-02-09T06:42:41Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2024-02-09T06:42:41Z" level=info msg="prometheus HTTP server started"
time="2024-02-09T06:42:41Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-02-09T06:42:41Z" level=info msg="beginning watching services, leaderelection will happen for every service"
time="2024-02-09T06:42:41Z" level=info msg="(svcs) starting services watcher for all namespaces"
time="2024-02-09T06:42:41Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [dmz-app-master-3]"
I0209 06:42:41.232585       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
I0209 06:42:41.257512       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-cp-lock
time="2024-02-09T06:42:41Z" level=info msg="Node [dmz-app-master-3] is assuming leadership of the cluster"
time="2024-02-09T06:42:41Z" level=info msg="Starting IPVS LoadBalancer"
time="2024-02-09T06:42:41Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2024-02-09T06:42:41Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [192.168.1.50]"
time="2024-02-09T06:42:41Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2024-02-09T06:42:41Z" level=error msg="Error querying backends file does not exist"
time="2024-02-09T06:42:41Z" level=info msg="Created Load-Balancer services on [192.168.1.50:6443]"
time="2024-02-09T06:42:41Z" level=info msg="Added backend for [192.168.1.50:6443] on [192.168.1.51:6443]"
time="2024-02-09T06:42:41Z" level=info msg="Added backend for [192.168.1.50:6443] on [192.168.1.52:6443]"
time="2024-02-09T06:42:41Z" level=info msg="Added backend for [192.168.1.50:6443] on [192.168.1.53:6443]"
time="2024-02-09T06:42:41Z" level=info msg="(svc election) service [rsyslog-forwarder], namespace [rsyslog], lock name [kubevip-rsyslog-forwarder], host id [dmz-app-master-3]"
I0209 06:42:41.279595       1 leaderelection.go:250] attempting to acquire leader lease rsyslog/kubevip-rsyslog-forwarder...
time="2024-02-09T06:42:41Z" level=info msg="(svc election) new leader elected: dmz-app-master-2"
```

May be linked to #752
