### ISSUE TITLE
Old routes are not removed if service is modified when kube-vip is down

### ISSUE THREAD

**Issue by p-strusiewiczsurmacki-mobica** [kube-vip/kube-vip#762]
**Describe the bug**
When kube-vip is deployed in routing table mode and service is created, rute is created (in table `198` by default). If kube-vip will be down and service will be recreated with another loadbalancer IP address, old route will stay in the routing table.

**To Reproduce**
1. Deploy kube-vip in routing table mode (both non-leader-election and service-leader-election tested).
2. Deploy service with some LB IP (e.g. 172.190.0.10**5**)
3. Delete kube-vip deployment.
4. Delete the service.
5. Recreate the service with different LB IP (e.g. 172.190.0.10**6**).
6. See that routing table has still both IP addresses present:

```
$ docker exec -it kind-worker2 ip route show table 198
172.190.0.105 dev lo 
172.190.0.106 dev lo
```

**Expected behavior**
kube-vip should remove old routes if possible.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: v1.27.3
 - Kube-vip Version:v0.7.0

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "4"
  labels:
    app.kubernetes.io/name: kube-vip-svc
    app.kubernetes.io/version: v0.7.0
  name: kube-vip-svc
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-svc
        app.kubernetes.io/version: v0.7.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_loglevel
          value: "5"
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: svc_enable
          value: "true"
        - name: svc_election
          value: "false"
        - name: vip_leaderelection
          value: "false"
        - name: vip_interface
          value: lo
        - name: vip_routingtable
          value: "true"
        - name: disable_service_updates
          value: "false"
        - name: prometheus_server
          value: :2112
        - name: enable_endpointslices
          value: "true"
        image: plndr/kube-vip:v0.7.0
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

**Additional context**
Service example:
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    kube-vip.io/loadbalancerIPs: "172.190.0.105"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  externalTrafficPolicy: Local
  type: LoadBalancer
```
