### ISSUE TITLE
Kube-VIP ARPs conflicting VIP information

### ISSUE THREAD

**Issue by dacjames** [kube-vip/kube-vip#788]
**Describe the bug**
We are using kube-vip to advertise LoadBalancer VIPs using ARP. Normally, this works fine. In at least two cases, we have observed duplicate conflicting ARP advertisements happening simultaneously.

**To Reproduce**
The issue has been difficult to reproduce in isolation. 

The cluster will run happily for a while and then seemingly at random we'll see issues resulting from the conflicting ARPs.

20:28:45.815587 ARP, Reply 10.240.17.183 is-at fa:c3:09:08:be:14, length 28
20:28:47.130643 ARP, Reply 10.240.17.183 is-at 42:92:ad:23:12:3z, length 46

When this occurs, the instance sending out ARP appears not to know that it a leader for the other IPs, because when shut down (by killing the pod), it does not report cleaning up the IP in question.

Shutting down the bad node will cause ARPs to stop but will not clear out the local IP address on the interface. 

It appears that the ARP broadcasting goroutine is somehow running in the background while kube-vip is in this state. An investigation of the code made me suspicious of this line: https://github.com/kube-vip/kube-vip/blob/main/pkg/cluster/clusterLeaderElection.go#L116 not calling arpCancel(). But, of course, that is just a wild guess.

**Expected behavior**
All VIPs should only ever be advertised from one leader at a time. If an instance is not leader for a service, it should not send ARPs for that service. 

**Environment (please complete the following information):**
 - OS/Distro: SLE Micro (based on SLES 15.5)
 - Kubernetes Version: v1.26 (rke2, rancher)
 - Kube-vip Version: 0.6.2

**`Kube-vip.yaml`:**
I think this is the relevant config. The only non-obvious variable here is the vip_interface, which is set to `eth1` in this instance.
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: ${daemonset_version}
  name: kube-vip-ds
  namespace: ${app_namespace}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: ${daemonset_version}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - args:
            - manager
          env:
            - name: vip_arp
              value: 'true'
            - name: port
              value: '6443'
            - name: vip_interface
              value: '${vip_interface}'
            - name: vip_servicesinterface
              value: '${vip_interface}'
            - name: vip_cidr
              value: '32'
            - name: svc_enable
              value: 'true'
            - name: svc_election
              value: 'true'
            - name: enable_service_security
              value: 'false'
            - name: prometheus_server
              value: ':2112'
          image: ghcr.io/kube-vip/kube-vip:${daemonset_version}
          imagePullPolicy: IfNotPresent
          name: kube-vip
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

**Additional context**
