### ISSUE TITLE
DDNS support is completely removed after v0.7.0

### ISSUE THREAD

**Issue by adavis10006** [kube-vip/kube-vip#794]
**Describe the bug**

After change in https://github.com/kube-vip/kube-vip/commit/3d559ba0ce801a8c8329178ca2be3f2147161e97, no ddns `network` is appended into `networks`. And the whole control plane routine is skipped as the `networks` is empty.

**To Reproduce**

Any ARP mode manifest with vip_ddns as `true`

**Expected behavior**

A DHCP client is started and the VIP get the IP using DHCP.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04 LTS
 - Kubernetes Version: v.1.28
 - Kube-vip Version: >= v0.7.0

**`Kube-vip.yaml`:**

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens160
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "true"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: k3s
        image: ghcr.io/kube-vip/kube-vip:v0.4.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```

**Additional context**
