### ISSUE TITLE
Frequent connection reset by peer when accessing from another network

### ISSUE THREAD

**Issue by heschlie** [kube-vip/kube-vip#797]
**Describe the bug**
I am running kube-vip on my 3 controller nodes, in BGP mode. When I access the API server VIP from the same network it works flawlessly, but when accessing it from another network I frequently get `connection reset by peer` errors. I have tested this with more than one machine and from various points in my network.

I am having trouble pinning down if this is an issue with my cluster, kube-vip, or my network. There isn't anything special about my network, and we are just 1 hop between the VLANs. This is a fresh cluster on local nodes setup with kubeadm.

**To Reproduce**
1. stand up cluster with kubeadm with 3 controllers
2. wait for cluster to be ready
3. access cluster outside its own network
4. try something that requires a long standing connection like logs or port forwarding

**Expected behavior**
Stable access to the api server

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: 1.29.3
 - Kube-vip Version: 0.7.2

**`Kube-vip.yaml`:**
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_loglevel
      value: "5"
    - name: vip_arp
      value: "false"
    - name: port
      value: "6443"
    - name: vip_interface
      value: lo
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: vip_ddns
      value: "false"
    - name: bgp_enable
      value: "true"
    - name: bgp_routerid
      value: 192.168.16.100
    - name: bgp_as
      value: "65000"
    - name: bgp_peeraddress
    - name: bgp_peerpass
    - name: bgp_peeras
      value: "65000"
    - name: bgp_peers
      value: 192.168.16.101:65000::false,192.168.16.102:65000::false
    - name: address
      value: 192.168.16.10
    image: ghcr.io/kube-vip/kube-vip:v0.7.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**
