### ISSUE TITLE
How to make a virtual ip jump to another control plane when the node where the virtual ip is located is notReady?

### ISSUE THREAD

**Issue by HuaJFrame** [kube-vip/kube-vip#800]
**Is your feature request related to a problem? Please describe.**
Whether or not to support virtual ip jumps to other nodes when the control plane is notReady for some special reason.

**Describe the solution you'd like**
After control plane A, which holds the virtual IP, is notReady, the virtual ip jumps to control plane B or C.

**Describe alternatives you've considered**
I am simulating a network shutdown scenario and kube-vip is working fine. I would like to have some configurations to control the jump conditions for the virtual IP, such as node not ready, network disconnected, and so on.

1. When the jump condition is that the node is notReady
    Node not ready and network disconnection will make the virtual ip jump to other nodes.
2. When the node network is disconnected at the time of the jump condition
    - Virtual ip does not jump when node is not ready.
    - Virtual ip jumps when the network is disconnected.

**Additional context**
```
Kubernetes version: v1.27.3
Container Runtimes: cri-dockerd 0.3.4
kube-vip version:  v0.6.3
```
Or is it possible that the functionality already exists because my version of kube-vip is not the latest? 
Here is the manifest for my static pod for bube-vip.

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens33
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.44.100
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.6.3
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
