### ISSUE TITLE
[Question] Does BGP Mode assign addresses to interfaces on the nodes?

### ISSUE THREAD

**Issue by CrimsonFez** [kube-vip/kube-vip#803]
I'm looking at using cilium egress snat functionality. In order for cilium to do egress the IP must be assigned on the node, does kube-vip do this in BGP mode?

Thanks

**Comment by thebsdbox** [comment]
Yes, kube-vip will apply the address to an interface. Although its expected that the interface will be `lo` in order to stop an IP address conflict.

**Comment by Cellebyte** [comment]
@CrimsonFez if you configure cilium to do so. It should be able to use it :)

**Comment by CrimsonFez** [comment]
Thanks, I just tested it and this does work. I even have my LB IPs on the `lo` interface and the source is preserved which is great.

Although I'm having an issue where if my current primary node fails my connections drop (i killed the pod in this case).
The IP does failover to another route but not before enough packets are lost or rejected by the new node.

Do you guys have any ideas on how I can make my connections HA?

I've done this in the past with conntrackd and keepalived for a redundant gateway setup in a regular network, but kubernetes networking is so much more complicated.

Any input would be appreciated! If this isn't the right place for this discussion please point me in the right direction.

Thanks!

**Comment by Cellebyte** [comment]
@CrimsonFez please share your current deployment manifest, then I could have a look.

**Comment by CrimsonFez** [comment]
Here's my kube-vip config
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-lb
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip-lb
  template:
    metadata:
      labels:
        app: kube-vip-lb
    spec:
      containers:
      - args:
        - manager
        env:
        - name: svc_enable
          value: "true"
        - name: lb_class_name
          value: "kube-vip"
        - name: vip_interface
          value: "lo"
        - name: vip_servicesinterface
          value: "lo"
        - name: bgp_enable
          value: "true"
        - name: bgp_routerid
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: bgp_as
          value: "65000"
        - name: bgp_peeraddress
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "65000"
        - name: bgp_peers
          value: 192.168.0.21:65000::false,192.168.0.22:65000::false,192.168.0.23:65000::false,192.168.100.11:64512::false,192.168.100.14:65000::false
        - name: prometheus_server
          value: :2113
        image: ghcr.io/kube-vip/kube-vip:v0.7.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

Here's my BIRD2 config
```
log syslog {warning};

router id 192.168.100.11;

protocol device {
}

protocol kernel {
	ipv4 {
		table master4;
		import none;
		export all;
	};
}

filter kube_ips {
	accept;
}

template bgp kube {
	local 192.168.100.11 as 64512;
	ipv4 {
		table master4;
		import filter kube_ips;
		export none;
	};
}

protocol bgp g1 from kube {
	neighbor 192.168.100.21 as 65000;
}

protocol bgp g2 from kube {
	neighbor 192.168.100.22 as 65000;
}

protocol bgp g3 from kube {
	neighbor 192.168.100.23 as 65000;
}

protocol bgp c1 from kube {
	neighbor 192.168.100.14 as 65000;
}
```

I just started learning BGP last night so any advise is appreciated
