### ISSUE TITLE
Kube-vip depends on `nodename == hostname` for service election, which easily breaks

### ISSUE THREAD

**Issue by d-uzlov** [kube-vip/kube-vip#810]
**Describe the bug**

It seems like kube-vip compares `sh -c hostname` to k8s node name when determining on which node a pod is located.
This works because k8s automatically assigns node name to `sh -c hostname`.
This doesn't work at all in case you alter node name in any way.

Kube-vip shouldn't depend on underlying hostname. Node names should only be compared to other node names.

The solution whould be to use k8s downward API: https://kubernetes.io/docs/concepts/workloads/pods/downward-api/, like suggested in a similar issue: https://github.com/kube-vip/kube-vip/issues/520#issuecomment-1883800048

**To Reproduce**

1. Create single node kubeadm cluster: `sudo kubeadm init --node-name my-custom-node-name`
2. Remove control plane taint: `kl taint node my-custom-node-name node-role.kubernetes.io/control-plane:NoSchedule-`
3. Deploy kube-vip with service election enabled
4. Deploy test service:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver-lb
  namespace: kube-system
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    component: kube-apiserver
  ports:
  - port: 6443
    targetPort: 6443
```

5. Check service external IP: `kubectl -n kube-system get svc apiserver-lb`
6. Check connection: `curl https://10.3.7.3:6443 --insecure`

**Expected behavior**

External IP is assugned.
Curl is able to connect to the service via the loadbalancer external IP.

**Actual behavior**

`apiserver-lb` gets the `kube-vip.io/loadbalancerIPs` annotation but its external IP is forever pending.
`status.loadBalancer.ingress` is never assigned.
curl fails with `Connection timed out`.

**Environment (please complete the following information):**
 - Kubernetes Version: 1.29.3
 - Kube-vip Version: 0.7.2

**`Kube-vip.yaml`:**

<details>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.7.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.7.2
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: dns_mode
          value: first
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: svc_election
          value: "true"
        - name: vip_address
        - name: prometheus_server
          value: :2113
        image: ghcr.io/kube-vip/kube-vip:v0.7.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

</details>

**Additional context**

There are a few issues that are likely related to this one:
- https://github.com/kube-vip/kube-vip/issues/608
- https://github.com/kube-vip/kube-vip/issues/520
