### ISSUE TITLE
Cleanup on VIP/Iptables/IPVS on kube-vip deletion (SIGTERM or SIGINT) fails

### ISSUE THREAD

**Issue by wyike** [kube-vip/kube-vip#824]
**Describe the bug**

When deleting the kube-vip deployment with control plane lb mode enabled, the controlplane VIP, iptables(masquerade mode) and IPVS should be cleaned up by watching the SIGTERM or SIGINT. But they didn't happen during tests.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1804]
 - Kubernetes Version: [e.g. v.1.18]
 - Kube-vip Version: [e.g. 0.2.3]

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)

**Additional context**

**Comment by matthewei** [comment]
what progress for is issue?

**Comment by jfpucheu** [comment]
Hello,

I am experiencing the same issue. When the VIP switches from Master 1 to Master 2 or Master 3 in IPVS mode, the rules are never cleaned up, even when I perform a proper crictl stop. The VIP remains active on the machine, and the IPVS rules are still present.

I don't understand why this doesn't cause more problems to other users

This leads to issues with API calls on the machine where the VIP is no longer present.

I have tested with lb_fwdmethod set to both masquerade and local, but the problem persists.

ipvsadm -Ln | grep -A 3 10.232.240.133:6443
TCP  10.232.240.133:6443 rr
  -> 10.232.240.187:6443          Local   1      2          0
  -> 10.232.240.240:6443          Local   1      0          0
  -> 10.232.240.251:6443          Local   1      7          0


My Setup:
```
Ubuntu 24.04.4 LTS
Kernel: 6.8.0-101-generic
kubernetes: v1.34.5
Calico in vxlan mode
```

kube-proxy: 

```
    ipvs:
      excludeCIDRs: ["10.232.240.128/25"]
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: true
      syncPeriod: 0s
      tcpFinTimeout: 0s
      tcpTimeout: 0s
      udpTimeout: 0s
```

kube-vip.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens3
    - name: vip_subnet
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "false"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "15"
    - name: vip_renewdeadline
      value: "10"
    - name: vip_retryperiod
      value: "2"
    - name: address
      value: 10.232.240.133
    - name: lb_enable
      value: "true"
    - name: lb_fwdmethod
      value: "local"
    image: kube-vip/kube-vip:v1.1.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
        - SYS_ADMIN
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf # https://github.com/kube-vip/kube-vip/issues/684
    name: kubeconfig
```

Jeff
