### ISSUE TITLE
[LoadBalancerClass] Better defaulting for Service objects

### ISSUE THREAD

**Issue by Cellebyte** [kube-vip/kube-vip#851]
**Describe the bug**
When you define a LoadBalancerClass via `env` or cli flag **kube-vip** only reconciles `Service` objects with this `LoadBalancerClass`.
This is expected behaviour and should stay like that.
The problem is when you have **kube-vip** running without a `LoadBalancerClass` defined, it also reconciles `Services` with a `LoadBalancerClass`. This would lead to unexpected behaviour as it could announce IPs which it should not.

e.g.
Ingress controllers without a specific `IngressClass` set, only reconcile Ingresses without a `IngressClass` and ignore all `Ingresses` which have such `IngressClass` defined.

**To Reproduce**
1. Install kube-vip with svc_enable and the mode you like but without LoadBalancerClassName set
2. Create 2 Services

```yaml
# a normal Service without a loadbalancerclass
apiVersion: v1
kind: Service
metadata:
  name: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    nodePort: 31690
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 32093
    port: 443
    protocol: TCP
    targetPort: https
  selector: {}
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.0
```

```yaml
# Service with a loadBalancerClass set
apiVersion: v1
kind: Service
metadata:
  name: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    nodePort: 31690
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 32093
    port: 443
    protocol: TCP
    targetPort: https
  selector: {}
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerClass: kube-vip.io/kube-vip-class
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.1
```

**Expected behavior**
The second service from the example above should not be reconciled by **kube-vip** but rather be skipped.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: v1.27.13
 - Kube-vip Version: v0.8.0
