### ISSUE TITLE
Using TCP/UDP on the same port, same service and IP 

### ISSUE THREAD

**Issue by jurgenweber** [kube-vip/kube-vip#859]
**Describe the bug**
I am basically doing this; https://chriskirby.net/highly-available-pi-hole-setup-in-kubernetes-with-secure-dns-over-https-doh/

(not using DHCP and not using cloudflare DOH, just a home DNS setup)

There are options in the pihole chart, you can run two services where in each service UDP and TCP port 53 are opened respectively, or you can have one service where they are both defined.

I have set the annotation, set loadbalancerIP (same IP) but no matter what the ports are not open. If I make a separate service with just the UDP port open on a different IP, it works. No problem. Other services work, no problem.

The logs look boring, nothing of note, no error.

**To Reproduce**
Steps to reproduce the behaviour:
piHole chart values:
```
serviceDns:
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.1.2
  mixedService: true 
  loadBalancerIP: 192.168.1.2
  type: LoadBalancer
  ```

**Expected behavior**
I expected both the TCP and UDP port to be open as defined in the service.

**Screenshots**
<img width="1369" alt="image" src="https://github.com/kube-vip/kube-vip/assets/3013734/ddab028e-43ac-4313-b2b2-7ed78716f51b">
```
 $ dig @192.168.1.2 +short google.com
;; connection timed out; no servers could be reached
 $ dig @192.168.1.5 +short google.com
142.250.66.238
 $ telnet 192.168.1.2 53
Trying 192.168.1.2...
telnet: connect to address 192.168.1.2: Operation timed out
telnet: Unable to connect to remote host
```

**Environment (please complete the following information):**
 - OS/Distro: 
 ```
 Linux warvm-master01 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux
# cat /etc/debian_version
12.5
```
 - Kubernetes Version: 
 ```
 # k3s --version
k3s version v1.29.3+k3s1 (8aecc26b)
go version go1.21.8
```
 - Kube-vip Version: ghcr.io/kube-vip/kube-vip:v0.8.0

**`Kube-vip.yaml`:**
```
# https://kube-vip.io/docs/usage/k3s/
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list","get","watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata: # generated here ; https://kube-vip.io/docs/installation/daemonset/#generating-a-manifest
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.0
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: ens19
        - name: vip_cidr
          value: "32"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.1.30
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.8.0
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  ```

**Additional context**
There seems to be no mention on how ports are handled at all, what happens if you ahve two loadbalancer services that want the same port?
