### ISSUE TITLE
nodelabel is not applied after a leader change

### ISSUE THREAD

**Issue by cdtzabra** [kube-vip/kube-vip#863]
Hello
**Describe the bug**

In my cluster I have 2 nodes (workers) dedicated for the egress with some taints.

I deploy kube-vip only on the both node with toleration

When the kube-vip leader is elected,  the node has the label: `kube-vip/has-ip=my_vip`
And i track that nodelabel `kube-vip/has-ip=my_vip`  and use it actif egress node for traffic.

But when the kube-vip leader change, the label **is not added** it the new node.
I got the error `no node label change needed`:  https://github.com/kube-vip/kube-vip/blob/c683bb879ec1fee25233b683d6abc65fb555f6a1/pkg/manager/node_labeling.go#L48

This break all the outgoing traffic.

My daemonset

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/egress
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens192
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.xx.yy.ZZ
        - name: vip_loglevel
          value: "5"
        - name: svc_electtion
          value: "false"
        - name: enable_node_labeling
          value: "true"
        image: ghcr.io/kube-vip/kube-vip:v0.8.0
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/egress
      - effect: NoExecute
        operator: Exists
        key: node-role.kubernetes.io/egress
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

```
**To Reproduce**
1.  deploy kube-vip on 2 dedicated node
2. Notice one node has the label
3. Delete the leader pod
4. Notice that the new leader pod doesn,' update its node label

**Expected behavior**

THe nodelabel must always be addded - so it must follow the leader change, no matter if it is worker node or controlplane node

@mjtrangoni
