### ISSUE TITLE
Egress pod startup delay

### ISSUE THREAD

**Issue by QtSYnT** [kube-vip/kube-vip#865]
**Describe the bug**
From testing with kube-vip using the egress feature we've noticed that there is a brief period of time from pod startup where the egress SNAT rules are not applied and outbound traffic is not sent from the KubeVIP egress address. Instead this traffic will originate from the IP of node hosting the pod and will in return be dropped by edge firewalls.

**To Reproduce**
1. Create a pod which runs curl immediately to some server
2. Run tcpdump and see source address is not the KubeVIP address

**Expected behavior**
Egress is active the entire time the pod executes.

**Environment (please complete the following information):**
 - OS/Distro: RHEL 8
 - Kubernetes Version: 1.24.15
 - Kube-vip Version: 0.6.2

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds-<snip>-<snip>
  namespace: <snip>
spec:
  selector:
    matchLabels:
      name: kube-vip-ds-<snip>-<snip>
  template:
    metadata:
      labels:
        name: kube-vip-ds-<snip>-<snip>
    spec:
      containers:
      - args:
        - manager
        - --prometheusHTTPServer
        - ""
        env:
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: <snip>
        - name: vip_cidr
          value: "16"
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: enableServicesElection
          value: "true"
        - name: svc_election
          value: "true"
        - name: egress_withnftables
          value: "true"
        - name: lb_class_name
          value: <snip>
        image: <snip>/kube-vip/kube-vip-iptables:v0.6.2
        imagePullPolicy: IfNotPresent
        name: kube-vip
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
```
