### ISSUE TITLE
[Bug or Feature?] kube-vip drops VIP when kube-apiserver unreachable. 

### ISSUE THREAD

**Issue by Cellebyte** [kube-vip/kube-vip#867]
**Describe the bug**

When the kube-apiserver is not reachable via its external endpoint
e.g.

* k8s.example.com:6443

All advertised LoadBalancer endpoints get withdrawn and the watcher dies.

**To Reproduce**
1. Install kube-vip using the provided yaml manifest
2. Deploy some LoadBalancer services with endpoints
3. Block incoming traffic from the worker nodes on all controller nodes

**Expected behavior**
I don't really know if kube-vip should just do nothing or if the current behaviour is expected.

**Environment (please complete the following information):**
 - OS/Distro: AlmaLinux 8.9
 - Kubernetes Version: v1.29.2
 - Kube-vip Version: 0.7.2

**`Kube-vip.yaml`:**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.7.2
  name: kube-vip-ds
  namespace: lb-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.7.2
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: lo
        - name: vip_cidr
          value: "32"
        - name: vip_loglevel
          value: "5"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "false"
        - name: svc_election
          value: "false"
        - name: vip_routingtable
          value: "true"
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.7.2
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      tolerations: {}
      serviceAccountName: kube-vip
  updateStrategy: {}
```

**Additional context**
