### ISSUE TITLE
CrashLoopBackOff Error in kube-vip Daemonset Due to Missing iptables Executable with --lbForwardingMethod masquerade

### ISSUE THREAD

**Issue by asosso** [kube-vip/kube-vip#874]
**Describe the bug**

I attempted to use kube-vip with the `--lbForwardingMethod masquerade` flag. However, the container goes into a CrashLoopBackOff state with the following error:

```
could not delete virtualIP: could not remove iptables masquerade rules : could not get iptables version: run cmd 'iptables --version' wtith error: exec: \"iptables\": executable file not found in $PATH
```

**To Reproduce**

Create a kube-vip Daemonset manifest with the following flags: `--enableLoadBalancer` and `--lbForwardingMethod masquerade` i.e.

```
kube-vip manifest daemonset \
    --interface $INTERFACE \
    --address $VIP \
    --inCluster \
    --taint \
    --controlplane \
    --services \
    --arp \
    --enableLoadBalancer \
    --enableNodeLabeling \
    --lbForwardingMethod masquerade \
    --leaderElection
```

**Expected behavior**

Since iptables is required in this configuration, kube-vip manifest daemonset command should generate a manifest that uses the `ghcr.io/kube-vip/kube-vip-iptables:v0.8.0` image when `--enableLoadBalancer` and `--lbForwardingMethod masquerade` flags are specified.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 24.04
 - Kubernetes Version: v1.28
 - Kube-vip Version: v0.8.0

**`Kube-vip.yaml`:**

Original output:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.0
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: enable_node_labeling
          value: "true"
        - name: lb_enable
          value: "true"
        - name: lb_port
          value: "6443"
        - name: lb_fwdmethod
          value: masquerade
        - name: address
          value: 10.0.1.0
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.8.0
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          privileged: true
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```
