### ISSUE TITLE
Generated manifest contain "status", leading to errors in ArgoCD

### ISSUE THREAD

**Issue by kastl-ars** [kube-vip/kube-vip#876]
**Describe the bug**
The manifest generated by the kube-vip preparation command (see script below) contains a `status` section:

```
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

This leads to errors in the deployment with ArgoCD, as the manifest inside the cluster is managed/changed by Kubernetes and contains other numbers than `0`.

I see no special flags in my script that could enable/disable this. Having to delete this manually while updating the manifest is one step that should not be necessary... :-)

**To Reproduce**
1. Create the manifest
2. Check into a GitOps repository for ArgoCD
3. Check the ArgoCD status and find, that ArgoCD would like to change back from e.g. `3` to `0`.

```
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 2
  updatedNumberScheduled: 3
```

**Expected behavior**
The status section can be omitted during generation, as it is added and managed by Kubernetes anyway.

**Environment (please complete the following information):**
 - OS/Distro: openSUSE MicroOS
 - Kubernetes Version: `v1.28.6+k3s2`
 - Kube-vip Version: `v0.8.0`

**Additional context**
The script to generate the daemonset manifest:

```
#!/bin/bash

# Set up environment
export VIP=192.2.0.13
export INTERFACE=eno1
export CONTAINER_RUNTIME_ENDPOINT=unix:///run/k3s/containerd/containerd.sock
export CONTAINERD_ADDRESS=/run/k3s/containerd/containerd.sock

KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
echo "KVVERSION is set to $KVVERSION"
export KVVERSION

# pull the image
podman image pull ghcr.io/kube-vip/kube-vip:"$KVVERSION"

# pull the manifests
curl -s https://kube-vip.io/manifests/rbac.yaml > kube-vip-rbac.yaml

# create the actual kube-vip daemonset manifest
podman run --rm --network=host ghcr.io/kube-vip/kube-vip:"$KVVERSION" \
    manifest daemonset \
    --arp \
    --interface $INTERFACE \
    --address $VIP \
    --controlplane \
    --leaderElection \
    --taint \
    --services \
    --inCluster | tee kube-vip-daemonset.yaml
```
