### ISSUE TITLE
Load balancing load balancer when using ARP mode seems to be not working

### ISSUE THREAD

**Issue by swinds24** [kube-vip/kube-vip#877]
**Describe the bug**
We're using kube-vip to assign LoadBalancerIP (VIP) for various services in a 3-node K3s cluster.  As the https://kube-vip.io/docs/usage/kubernetes-services/#load-balancing-load-balancers-when-using-arp-mode-yes-you-read-that-correctly-kube-vip-v050 says, we enable the `svc_election` feature and expect that VIPs can be assigned and bond to different nodes.  However, after creating several services, we find that most of the VIPs are assigned to one of the node which may eventually produce performance bottleneck.

```
[root@jn1 hello]# kubectl logs -n kube-system kube-vip-jn2 | grep "new leader"
time="2024-06-06T01:55:13Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-06T01:55:13Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-06T01:55:44Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-06T02:01:48Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-06T02:02:21Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-07T07:42:22Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-07T09:34:55Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-07T09:44:44Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-07T10:58:12Z" level=info msg="(svc election) new leader elected: jn3"
time="2024-06-11T01:57:46Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-11T02:34:59Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-11T03:02:02Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-11T03:23:58Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-11T03:35:18Z" level=info msg="(svc election) new leader elected: jn1"
time="2024-06-11T03:39:52Z" level=info msg="(svc election) new leader elected: jn1"
```

**Expected behavior**
VIPs can be assigned and bond to different nodes

**Environment (please complete the following information):**
 - OS/Distro: Fedora CoreOS 38
 - Kubernetes Version: v1.29.4+k3s1
 - Kube-vip Version: ghcr.io/kube-vip/kube-vip:v0.6.4

**`Kube-vip.yaml`:**
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: enp1s0f0np0
    - name: vip_servicesinterface
      value: enp1s0f1np1
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: svc_election
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 172.16.10.77
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.6.4
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

Any insight and help are appreciated!
