### ISSUE TITLE
svc_enable=true, having two load balancers with the same IP but different ports will result in the IP appearing on two different servers.

### ISSUE THREAD

**Issue by m198799** [kube-vip/kube-vip#879]
**Describe the bug**

I have a three-node Kubernetes cluster with two load balancers using the same IP but different port numbers. This VIP appears on two nodes simultaneously.

**To Reproduce**
1. Create kube-vip-cloud-provider configmap
```yaml
apiVersion: v1
data:
  cidr-qt-system: 10.106.109.9/32
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kube-vip-cloud-provider
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kubevip
```
2. Create 2 load balancers with the same ip
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 10.106.109.9
  labels:
    implementation: kube-vip
  name: traefik-lb-1
spec:
  ports:
  - name: agent
    port: 8000
    protocol: TCP
    targetPort: agent
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: LoadBalancer
``` 

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 10.106.109.9
  labels:
    implementation: kube-vip
  name: traefik-lb-2
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: LoadBalancer
```
3. To check the creation status of a virtual IP (VIP) on different servers.
```bash
[root@ip-10-106-109-51 ~]# ip addr show ens18
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fe:33:6e:ee:11:43 brd ff:ff:ff:ff:ff:ff
    inet 10.106.109.51/24 brd 10.106.109.255 scope global noprefixroute ens18
       valid_lft forever preferred_lft forever
    inet 10.106.109.9/32 scope global ens18
       valid_lft forever preferred_lft forever
```

```bash
[root@ip-10-106-109-52 ~]# ip addr show ens18
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:e8:74:31:5f:db brd ff:ff:ff:ff:ff:ff
    inet 10.106.109.52/24 brd 10.106.109.255 scope global noprefixroute ens18
       valid_lft forever preferred_lft forever
    inet 10.106.109.9/32 scope global ens18
       valid_lft forever preferred_lft forever
```

**Expected behavior**

The VIP address appears only on one server.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: [e.g. CentOS 8.5.2111]
 - Kubernetes Version: [e.g. v.1.24.17]
 - Kube-vip Version: [e.g. v0.8.0]

**`Kube-vip.yaml`:**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    meta.helm.sh/release-name: kube-vip
    meta.helm.sh/release-namespace: qt-system
  creationTimestamp: "2024-06-13T07:07:36Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/version: 202406061636-db14aabc
    helm.sh/chart: kube-vip-0.1.0
  name: kube-vip
  resourceVersion: "554829"
  uid: a381a14c-1dd3-4077-9aae-e2b1c3ad8b4e
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-vip
      app.kubernetes.io/name: kube-vip
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kube-vip
        app.kubernetes.io/name: kube-vip
    spec:
      affinity: {}
      containers:
      - args:
        - manager
        - --prometheusHTTPServer=
        env:
        - name: vip_arp
          value: "true"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: svc_election
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "60"
        - name: vip_renewdeadline
          value: "20"
        - name: vip_retryperiod
          value: "5"
        image: plndr/kube-vip:v0.8.0
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 16Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      imagePullSecrets:
      - name: qt-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 2
  updatedNumberScheduled: 3
```
**Additional context**
If I delete svc_election, it will work normally.

**Comment by m198799** [comment]
I’m not sure if it’s related to https://github.com/kube-vip/kube-vip/pull/622, but in the v0.6.0 environment, setting svc_election=true ensures that load balancers with the same IP do not appear on different servers.
Is it better for service leases to use the service IP address or to support customization?

**Comment by CrimsonFez** [comment]
> Is it better for service leases to use the service IP address or to support customization?
What do you mean by this?

It would be best for the same LBIP to not appear on multiple nodes. I also have this issue in v0.8.3.

**Comment by Cellebyte** [comment]
@CrimsonFez it depends on the mode kube-vip is configured for.

For the ARP mode I agree.
@m198799 can you still reproduce it with the latest kube-vip version?

**Comment by m198799** [comment]
@Cellebyte 
Sorry for the delayed response.

We conducted the same tests on version 0.8.8, and the results were the same.
I used the latest versions: kube-vip:0.8.8 and kube-vip-cloud-provider:0.0.10.
```yaml
- name: svc_enable
  value: "true"
- name: svc_election
  value: "true"
```

This configuration caused kube-vip to use the service name to acquire leases. Two different leases inevitably resulted in two kube-vip instances obtaining different leases, ultimately leading to one IP address appearing on the nodes corresponding to both kube-vip instances.

Of course, I can ensure that the IP appears on only one node by setting svc_enable=false.

However, when I use different IPs as load balancer addresses, all traffic will be routed through a single node to enter the cluster.

I will dedicate more time to focus on this issue moving forward.

**Comment by m198799** [comment]
@CrimsonFez 
I noticed that kube-vip uses Kubernetes leases for leader election of the service controller.
However, service names must be different, yet kube-vip supports assigning the same IP to two services (using different ports).
This results in the same IP appearing on different nodes due to the use of different Kubernetes leases.

**Comment by Cellebyte** [comment]
Please check #1129 and also maybe try the new `main` build which correctly handles multiple Services with the same IP now.

**Comment by zimmerry** [comment]
@Cellebyte I'm also running into this, even after upgrading to v0.9.1. IPs are still appearing on multiple nodes when they're used by multiple services.

I read through https://github.com/kube-vip/kube-vip/issues/1129, but I don't see an obvious solution. I've tried setting `vip_leaderelection=true,svc_election=true` and `vip_leaderelection=false,svc_election=true` and get the same behavior with both.

This is my daemonset manifest:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.9.1
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.9.1
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_servicesinterface
          value: bond0
        - name: vip_loglevel
          value: "-4"
        - name: dns_mode
          value: first
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: enable_node_labeling
          value: "true"
        - name: svc_election
          value: "true"
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.9.1
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      nodeSelector:
        virtual: 'false'

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
```

**Comment by Kalen89** [comment]
@Cellebyte I’m using plndr/kube-vip:v0.9.1 version, and it can ensure that the same IP does not appear on different nodes.

<img width="1301" alt="Image" src="https://github.com/user-attachments/assets/734c7fe9-491c-4ff3-90c3-03eed1d3e9ce" />

<img width="870" alt="Image" src="https://github.com/user-attachments/assets/bbf9ea7f-1e0c-4f6d-a83a-b0e21527a66a" />

<img width="333" alt="Image" src="https://github.com/user-attachments/assets/a4cf7b54-b20f-4dba-a6a6-25537428e82f" />

However, this results in all IPs being assigned to a single node. Maybe we can allow users to decide the lease name to avoid this situation?
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-lb-2
  annotations:
    kube-vip.io/loadbalancerIPs: 10.106.109.9
    kube-vip.io/lease: traefik-lb-2-leader
```
If kube-vip.io/lease is empty, continue to use kubevip + service name as the lease name.
If you think this is acceptable, I’m happy to help.
