### ISSUE TITLE
Controlplane VIP only lasts 60 seconds

### ISSUE THREAD

**Issue by bcurnow** [kube-vip/kube-vip#886]
**Describe the bug**
I'm using static pods to provide a VIP for the control plane. I've configured kube-vip to use BGP. Everything works exactly as expected except that when adding the VIP address to the link, valid_lft is set to 60 seconds. This means 60 seconds after kube-vip starts up, the VIP address drops from my interface and I can no longer reach it.

This appears to be because the default valid_lft is 60 (defaultValidLft in pkg/vip/address.go) and, for BGP, the address is only added to the interface once (pkg/cluster/service.go).

This was not a problem when using ARP mode as the address is re-added as part of the ARP loop (so every 3 seconds).

**To Reproduce**
1. Setup a static pod with the following manifest:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "false"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: lo
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: bgp_enable
      value: "true"
    - name: bgp_routerid
      value: <k8s node IP>
    - name: bgp_as
      value: "64513"
    - name: bgp_peeraddress
      value: <my firewall ip>
    - name: bgp_peerpass
    - name: bgp_peeras
      value: "64512"
    - name: bgp_sourceip
      value: <k8s node IP>
    - name: address
      value: <vip address>
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.0
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
2. Reboot the node
3. Wait for kube-vip to startup
4. Note the the VIP is working correctly
5. Within the first 60 seconds, login to the control plane node and run `ip addr show dev lo`  - Note that valid_lft is set (and will be counting down)
6. After 60 seconds, run `ip addr show dev lo`  - Note that the VIP address is now gone and the control plane is no longer accessible
7. Check the BGP peer and note that the route is still published
8. Execute `ip addr add <vip> dev lo` - Note that everything is working again (default for ip addr add is to set valid_lft to forever)

**Expected behavior**
I expected the VIP address to stay on the interface forever

**Environment (please complete the following information):**
 - OS/Distro: Debian 12
 - Kubernetes Version: 1.30.1
 - Kube-vip Version: 0.8.0
