### ISSUE TITLE
v0.8.2: dial tcp 10.43.0.1:443: connect: network is unreachable

### ISSUE THREAD

**Issue by akademic** [kube-vip/kube-vip#905]
**Describe the bug**
Updated from k3s-1.25+kube-vip:v0.5.7 (all were working) to k3s-1.28+kube-vip:v0.8.2

Got repeating error 
```
leaderelection. go:332] error retrieving resource lock kube-system/plndr-svcs-lock: Get "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-sucs-lock?timeout=10s":dial tcp 10.43.0.1:443: connect: network is unreachable
```
At first got $IP on interface, but after a while all ip (virtual and not virtual) is removed from $INTERFACE

**To Reproduce**
1. Create server, setup k3s arigap installation
2. wget -O /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml https://kube-vip.io/manifests/rbac.yaml
3. `kube-vip manifest daemonset --interface $INTERFACE --address $VIP --inCluster --taint --controlplane --services --arp --leaderElection`
4.  `INSTALL_K3S_SKIP_DOWNLOAD=true K3S_TOKEN=\"123\" INSTALL_K3S_EXEC=\"server --cluster-init --tls-san $VIP\" sh /root/install.sh`

**Expected behavior**
$VIP is on $INTERFACE, no errors in kube-vip log

**Environment (please complete the following information):**
 - OS/Distro: debian 12  https://cloud.debian.org/images/cloud/bookworm/20240702-1796/debian-12-genericcloud-amd64-20240702-1796.qcow2
 - Kubernetes Version: [v1.28.11+k3s2](https://github.com/k3s-io/k3s/releases/tag/v1.28.11%2Bk3s2)
 - Kube-vip Version: [0.8.2]

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: ens3
        - name: vip_cidr
          value: "32"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: plndr-svcs-lock
        - name: vip_leaderelection
          value: "true"
        - name: vip_leasename
          value: plndr-cp-lock
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.168.1.111
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.8.2
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
```
