### ISSUE TITLE
VIP does not come up on fresh cluster install

### ISSUE THREAD

**Issue by gilgwath** [kube-vip/kube-vip#907]
**Describe the bug**
I've been trying to work out what I'm doing wrong for the past two days, but I seem to be unable to get this right. I suspect I'm hitting some kind of bug.

I'm trying to get a control plane up in Vagra VM on AlmaLinux 9.4 and the VIP will not come online, when running `kubeadm init` with the `--control-plane-endpoint` flag. I think I'm following the instructions from the instal guide properly.

**To Reproduce**
1. Install kublet, kubeadm, kubectl from official repo (tried 1.30 and 1.29)
2. Load required kernel modules: `br_netfilter_overlay`, `ip_vs_rr`, `ip_vs_wrr`, `ip_vs_sh`, `nf_conntrack`
3. Set required sysctl values: `net.bridge.bridge-nf-call-ip6tables`, `net.bridge.bridge-nf-call-iptables`, `net.ipv4.ip_forward`
5. Install containerd from the official repo
6. `kubeadm init --pod-network-cidr=172.18.0.0/16 --control-plane-endpoint=192.168.121.20 --upload-certs`
7. Wait for `init` to finish
8. Timeout because API endpoint doesn't come up for 4 minutes
9. Cluster is borked, also no VIP assigned to specified interface

Now, the very peculiar thing: If I run this without `--control-plane-endpoint`, `init` finishes as expected and the VIP gets assigned to the chosen interface and I can ping it. But of course, that's not really what the point of the whole exercise is.

I managed to get the logs out of the pod, in the semi-alive state the cluster is left in:
```
crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock logs aa8fa2e3f02ae
time="2024-07-29T20:50:53Z" level=info msg="Starting kube-vip.io [v0.5.0]"
time="2024-07-29T20:50:53Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2024-07-29T20:50:53Z" level=info msg="prometheus HTTP server started"
time="2024-07-29T20:50:53Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-07-29T20:50:53Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [test.fam-fa.net]"
I0729 20:50:53.437892       1 leaderelection.go:248] attempting to acquire leader lease kube-system/plndr-cp-lock...
E0729 20:50:53.441091       1 leaderelection.go:330] error retrieving resource lock kube-system/plndr-cp-lock: leases.coordination.k8s.io "plndr-cp-lock" is forbidden: User "kubernetes-admin" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```
The last line just repeats.

**Expected behavior**
`kubeadme init` finishes as normal, VIP gets assigned to specified interface

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: AlmaLinux 9.4 Kernel `5.14.0-427.26.1.el9_4.x86_64`
 - Kubernetes Version: `1.30.3` and `1.29.7`
 - Kube-vip Version: tried `0.8.2`, `0.8.1`, `0.7.2`, and `0.5.0`

**`Kube-vip.yaml`:**
```

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: eth0
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.121.20
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.2
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**
This is running inside a Vagrant virtual machine using the `libvirt` provider. Host OS: Fedora 40, Kernel version: `6.9.11-200.fc40.x86_64 (64-bit)`. I tried running k8s on its own interface, since Vagrant adds a default NAT interface as `eth0`. I guessed this might cause some weirdness, but it did not change anything.

**Comment by ujslxw** [comment]
look this issue [#684 ]
1. 
```shell
sed -i 's#path: /etc/kubernetes/admin.conf#path: /etc/kubernetes/super-admin.conf#' \
          /etc/kubernetes/manifests/kube-vip.yaml
```
2.
kubeadm init
3.
```shell
sed -i 's#path: /etc/kubernetes/super-admin.conf#path: /etc/kubernetes/admin.conf#' \
          /etc/kubernetes/manifests/kube-vip.yaml
```

**Comment by gilgwath** [comment]
Yes, you hit the nail on the head! Thank you very much! 

For people who are doing this with Ansible, like I do:
``` yaml
- name: Kube VIP Issue 684 workaround
  lineinfile:
    regexp: "path: /etc/kubernetes/admin.conf"
    line: "      path: /etc/kubernetes/super-admin.conf" # Spaces are required for indentation
    path: /etc/kubernetes/manifests/kube-vip.yaml
  when: kube_vip_issue_684_workaround | default(false)
  notify: Revert Kube VIP Issue 684 workaround
```

And a handler to revert:
```yaml
- name: Revert Kube VIP Issue 684 workaround
  lineinfile:
    regexp: "path: /etc/kubernetes/super-admin.conf"
    line: "      path: /etc/kubernetes/admin.conf" # Spaces are required for indentation
    path: /etc/kubernetes/manifests/kube-vip.yaml
```
