### ISSUE TITLE
VIP Unreachable on Secondary Control Plane: 'No Route to Host' Despite Correct ARP Responses

### ISSUE THREAD

**Issue by devopsInterviews** [kube-vip/kube-vip#931]
**Describe the bug**

We encountered an issue where the kubeadm join command from the second control plane node to the kubevip-api-server fails, indicating that there is no route to the VIP. Despite this, the VIP is reachable from the first control plane node, and we can successfully perform operations like curl to the VIP and get the cluster health status. This issue appears to be specific to ARP handling and how the VIP is being advertised or resolved in the network.

To Reproduce Steps to reproduce the behavior:

Deploy kube-vip on a Kubernetes cluster with two control plane nodes (Control Plane 1: 192.168.1.1, Control Plane 2: 192.168.1.2) and set the VIP to 192.168.1.3.
Configure /etc/hosts on both control plane nodes to map kubevip-api-server to the VIP (192.168.1.3).
From Control Plane 2, run the following command to join the cluster:

```
kubeadm join kubevip-api-server:6443 --token yy401.k956gtmxs5z4564nj5 \
--discovery-token-ca-cert-hash sha256:6bc06c9bb4b03c2dfgdfhdfndfndfvsdv369cd45d3465fada56bbd5c353d11f9 \
--control-plane --certificate-key 8c74362572b79d6f185d15d761sdbdsfhrtjt576edaa104fc47b4d10cd530c0c

```
Observe the following error:

```
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: failed to get config map: Get "https://kubevip-api-server:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s": dial tcp 192.168.1.3:6443: connect: no route to host
To see the stack trace of this error execute with --v=5 or higher

```

**Expected behavior**
The expectation is that Control Plane 2 should be able to resolve the VIP and join the cluster without any connectivity issues. The ARP request from Control Plane 2 should reach Control Plane 1, which should respond with the correct MAC address associated with the VIP.

Environment (please complete the following information):

OS/Distro: Ubuntu 20.04
Kubernetes Version: v1.26
Kube-vip Version: 0.8.2
Kube-vip.yaml:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: ensp03
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.1.3
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.2
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Additional context**

The issue was first identified when attempting to join Control Plane 2 to the cluster using the VIP (192.168.1.3). We utilized tcpdump on both control plane nodes to monitor the ARP requests and responses.

Scenario 1: ARP Request and Response

From Control Plane 2:

We initiated an ARP request for the VIP (192.168.1.3).
The ARP request was sent out three times, but no valid response was received, leading to a timeout:

```
11:27:53.871197 ARP, Request who-has kubevip-api-server tell 192.168.1.2, length 44
11:27:54.872498 ARP, Request who-has kubevip-api-server tell 192.168.1.2, length 44
11:27:55.873673 ARP, Request who-has kubevip-api-server tell 192.168.1.2, length 44

```

From Control Plane 1:

We observed that Control Plane 1 was receiving the ARP request from Control Plane 2.
Control Plane 1 responded to the ARP request with its MAC address associated with the VIP (192.168.1.3):

```
11:33:43.886064 fa:33:3e:44:82:11 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.1.3 tell 10.200.86.35, length 46
11:33:43.886115 fa:16:2e:b5:cc:bb > fa:33:3e:44:82:11, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Reply 192.168.1.3 is-at fa:16:2e:b5:cc:bb, length 28

```

Despite this, Control Plane 2 did not seem to receive or process the ARP reply, resulting in a connectivity issue.

Scenario 2: Gratuitous ARP

We also observed that when kube-vip sends a Gratuitous ARP on Control Plane 1, it is visible on Control Plane 1 but not on Control Plane 2, even though both are on the same LAN. 

Further Details:

The VIP is not visible on the network interface of Control Plane 1, which might indicate that kube-vip is not correctly binding the VIP to the interface. The VIP should be visible on the control plane's interface (when doing ifconfig)?

This issue persists despite confirming that there are no firewalls or network policies that would block ARP or other traffic between these nodes.

When using arping with the regular node IPs, everything works as expected.

We would like clarification on whether the VIP should be visible in the network interface and any potential causes for the ARP replies not being correctly processed by the second control plane node. Additionally, any insights on why the Gratuitous ARP is not propagating to the second control plane would be appreciated.

Pod Logs: The logs from the kube-vip pod were reviewed, but they contained no significant or relevant information that would help in diagnosing the issue. The logs showed normal operation without any errors or warnings that would indicate a problem with the VIP or ARP handling.

We would love to have your help!!
Thanks in advance!
