### ISSUE TITLE
Loadbalancer IPv6 connection issue and log spam

### ISSUE THREAD

**Issue by cp-fabian-pittroff** [kube-vip/kube-vip#933]
**Describe the bug**
Trying to setup a service loadbalancer (IPv4 & IPv6 / Dualstack). Both IPs getting assigned to a node and are pingable. The IPv4 routing is working fine. But the IPv6 route seems to be dropped. I immediately get `Couldn't connect to server` errors with curl.

Also kube-vip is spamming the logs with this:

```
kube-vip-ds-f2sxp time="2024-08-31T14:01:31Z" level=info msg="Broadcasting NDP update for fd22:fb0b:57be:20::202 (bc:24:11:15:e5:4f) via enp6s18"
kube-vip-ds-f2sxp time="2024-08-31T14:01:31Z" level=info msg="ndp: &{false false true fd22:fb0b:57be:20::202 [0xc0007883a0]}"
kube-vip-ds-f2sxp time="2024-08-31T14:01:34Z" level=info msg="Broadcasting NDP update for fd22:fb0b:57be:20::202 (bc:24:11:15:e5:4f) via enp6s18"
kube-vip-ds-f2sxp time="2024-08-31T14:01:34Z" level=info msg="ndp: &{false false true fd22:fb0b:57be:20::202 [0xc00024e0a0]}"
```

**To Reproduce**
1. setup kube-vip daemon with `svc_enable: true`
2. create service with kube-vip annotation
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ipv6-service
  annotations:
    kube-vip.io/loadbalancerIPs: <ipv4>,<ipv6>
    # e.g. kube-vip.io/loadbalancerIPs: 10.0.0.200,fd80::200
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
```
3. Both IPs should be pingable ping 10.0.0.200 & ping6 fd80::200
4. Check through browser or curl
```bash
curl -LI "http://10.0.0.200/"
# works 200 OK

curl -LI "http://[fd80::200]/"
# error: curl: (7) Failed to connect to fd80::200 port 80 after 1 ms: Couldn't connect to server
```

**Expected behavior**
IPv6 loadbalancer route should also be accessible and kube-vip should not spam the logs with `Broadcasting NDP update`

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 24.04
 - Kubernetes Version: v1.30.2+rke2r1
 - Kube-vip Version: v0.8.2

**`Kube-vip.yaml`:**
<details><summary>kube-vip.yaml...</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - args:
            - manager
          env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_nodename
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: vip_interface
              value: enp6s18
            - name: vip_cidr
              value: 32
            - name: dns_mode
              value: first
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: svc_enable
              value: "true"
            - name: svc_leasename
              value: plndr-svcs-lock
            - name: vip_leaderelection
              value: "true"
            - name: vip_leasename
              value: plndr-cp-lock
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
            - name: address
              value: <ipv4>
            - name: prometheus_server
              value: :2112
          image: ghcr.io/kube-vip/kube-vip:v0.8.2
          imagePullPolicy: IfNotPresent
          name: kube-vip
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
  updateStrategy: {}
```
</details> 

**Additional context**
 Using rke2 and setup only ipv4 cluster cidr (default: 10.43.0.0/16). Also tried to update kube-vip to also assign a IPv6 to the control-plane. But I get the same error there. Spamming logs and I can't connect through IPv6.

Also tried updating kube-proxy-args
```yaml
kube-proxy-arg:
  - proxy-mode=ipvs
  - ipvs-strict-arp=true
```

I don't know what I'm doing wrong at this point. Also the `ipvsadm -Ln` command shows only ipv4 rules an not a single ipv6 one. Not sure why, though.

Thanks
