### ISSUE TITLE
VIP address not being automatically removed after Service deletion

### ISSUE THREAD

**Issue by lucs-t** [kube-vip/kube-vip#936]
**Describe the bug**
When using kube-vip to manage LoadBalancer services, the VIP address is not being automatically removed from the network interface after the corresponding Service is deleted. This causes the VIP to remain assigned to the node, leading to potential conflicts when new services are created or re-used.

**To Reproduce**

Create a LoadBalancer type service with a specific VIP.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp
spec:
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxapp
spec:
  selector:
    app: nginxapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  loadBalancerIP: 10.9.0.233
```

kubectl get po,svc
```
NAME                            READY   STATUS    RESTARTS   AGE
pod/nginxapp-67d9758fbf-xk8c6   1/1     Running   0          11s

NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP        13h
service/nginxapp     LoadBalancer   10.103.254.249   10.9.0.233    80:30404/TCP   12s
```

Observe that the VIP is correctly added to the network interface (e.g., ens160):
ip addr show ens160
```
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 10.9.0.201/16 brd 10.9.255.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet 10.9.0.210/32 scope global ens160
       valid_lft forever preferred_lft forever
    inet 10.9.0.233/32 scope global ens160
       valid_lft forever preferred_lft forever
```
Delete the service:
kubectl delete  

Check the network interface again. The VIP 10.9.0.233/32 is still present on the interface ens160.
ip addr show ens160
```
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 10.9.0.201/16 brd 10.9.255.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet 10.9.0.210/32 scope global ens160
       valid_lft forever preferred_lft forever
    inet 10.9.0.233/32 scope global ens160
       valid_lft forever preferred_lft forever
```
log
```
time="2024-09-04T19:42:20Z" level=info msg="Starting kube-vip.io [v0.8.0]"
time="2024-09-04T19:42:20Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2024-09-04T19:42:20Z" level=info msg="prometheus HTTP server started"
time="2024-09-04T19:42:20Z" level=info msg="Using node name [master2]"
time="2024-09-04T19:42:20Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-09-04T19:42:20Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [plndr-svcs-lock], id [master2]"
I0904 19:42:20.750014       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-svcs-lock...
time="2024-09-04T19:42:20Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [master2]"
I0904 19:42:20.753661       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
I0904 19:42:20.797305       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-cp-lock
I0904 19:42:20.797493       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-svcs-lock
time="2024-09-04T19:42:20Z" level=info msg="Node [master2] is assuming leadership of the cluster"
time="2024-09-04T19:42:20Z" level=info msg="(svcs) starting services watcher for all namespaces"
time="2024-09-04T19:42:20Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [10.9.0.210/ens160]"
time="2024-09-04T20:29:02Z" level=info msg="(svcs) [calico-system/calico-kube-controllers-metrics] has been deleted"
time="2024-09-04T20:29:04Z" level=info msg="(svcs) [calico-system/calico-typha] has been deleted"
E0904 21:07:06.573653       1 leaderelection.go:332] error retrieving resource lock kube-system/plndr-cp-lock: etcdserver: leader changed
time="2024-09-04T21:44:34Z" level=info msg="(svcs) [calico-apiserver/calico-api] has been deleted"
time="2024-09-04T21:44:34Z" level=info msg="(svcs) [calico-system/calico-kube-controllers-metrics] has been deleted"
time="2024-09-04T21:47:23Z" level=info msg="(svcs) [calico-system/calico-typha] has been deleted"
time="2024-09-04T16:25:15Z" level=info msg="(svcs) [calico-apiserver/calico-api] has been deleted"
time="2024-09-04T16:38:34Z" level=info msg="(svcs) [calico-system/calico-kube-controllers-metrics] has been deleted"
time="2024-09-04T16:38:39Z" level=info msg="(svcs) [calico-system/calico-typha] has been deleted"
time="2024-09-05T01:25:15Z" level=info msg="(svcs) [metallb-system/metallb-webhook-service] has been deleted"
time="2024-09-05T01:29:15Z" level=info msg="(svcs) adding VIP [10.9.0.233] via ens160 for [default/nginxapp]"
time="2024-09-05T01:29:15Z" level=info msg="[service] synchronised in 50ms"
time="2024-09-05T01:29:15Z" level=warning msg="(svcs) already found existing address [10.9.0.233] on adapter [ens160]"
time="2024-09-05T01:29:18Z" level=warning msg="Re-applying the VIP configuration [10.9.0.233] to the interface [ens160]"
time="2024-09-05T01:33:24Z" level=info msg="(svcs) [default/nginxapp] has been deleted"
E0905 01:48:36.399150       1 leaderelection.go:332] error retrieving resource lock kube-system/plndr-svcs-lock: etcdserver: leader changed
time="2024-09-05T01:50:01Z" level=info msg="(svcs) adding VIP [10.9.0.233] via ens160 for [default/nginxapp]"
time="2024-09-05T01:50:02Z" level=info msg="[service] synchronised in 110ms"
time="2024-09-05T01:50:02Z" level=warning msg="(svcs) already found existing address [10.9.0.233] on adapter [ens160]"
time="2024-09-05T01:50:04Z" level=warning msg="Re-applying the VIP configuration [10.9.0.233] to the interface [ens160]"
time="2024-09-05T01:52:43Z" level=info msg="(svcs) [default/nginxapp] has been deleted"
```
**Expected behavior**
The VIP (10.9.0.233/32) should be automatically removed from the network interface once the corresponding LoadBalancer service is deleted.

**Environment (please complete the following information):**
kube-vip 版本: v0.8.0 (请替换为实际版本)
Kubernetes 版本: v1.28.12 (请替换为实际版本)
calico: 

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: ens160
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 10.9.0.210
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.0
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
**Additional context**
none

Please help me~~~~
