### ISSUE TITLE
Kube-Vip Not Working on Kubernetes from 1.29 to Latest

### ISSUE THREAD

**Issue by devopsInterviews** [kube-vip/kube-vip#938]
Describe the bug
In Kubernetes versions 1.30.4 and 1.29.x, Kube-Vip fails to properly start and manage the VIP, resulting in the kubelet failing to register nodes due to a "no route to host" error when trying to communicate with the API server via the VIP. This behavior works as expected on Kubernetes version 1.28.13 but not on newer versions. The kubelet continues to attempt to connect to the VIP (192.168.1.1), even when localAPIEndpoint is configured with the real control plane node's IP.

Logs from the kubelet show repeated attempts to connect to the VIP with errors like dial tcp: no route to host, and the Kube-Vip container fails to bind the VIP because it cannot access the API server.

Deploy Kubernetes version 1.29.x or 1.30.4 with Kube-Vip configured for the API server VIP.
Specify localAPIEndpoint in the kubeadm configuration with the control plane node’s real IP.
Check the kubelet logs and observe that the kubelet is still trying to connect to the VIP (192.168.1.1) and not the local API endpoint.
Attempt to bring up the Kube-Vip service, which will fail to perform leader election due to API server unavailability.
Expected behavior
The kubelet should connect to the real control plane IP as defined in localAPIEndpoint when the VIP is not available. Kube-Vip should be able to perform leader election and manage the VIP without causing a deadlock between the kubelet and API server.

Logs from Kubelet
Logs showing the kubelet failing to connect to the API server via the VIP:

```
Sep 08 11:15:20 master0 kubelet[86403]: E0908 11:15:20.016412   86403 kubelet_node_status.go:96] "Unable to register node with API server" err="Post \"https://192.168.1.1:6443/api/v1/nodes\": dial tcp 192.168.1.1:6443: connect: no route to host"
Sep 08 11:15:20 master0 kubelet[86403]: E0908 11:15:20.016423   86403 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/master0\": dial tcp 192.168.1.1:6443: connect: no route to host"
Sep 08 11:15:20 master0 kubelet[86403]: E0908 11:15:20.960610   86403 eviction_manager.go:282] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"master0\" not found"

```
Logs from Kube-Vip Container (via crictl)

`E0908 14:27:37.076396       1 leaderelection.go:332] error retrieving resource lock kube-system/plndr-svcs-lock: leases.coordination.k8s.io "plndr-svcs-lock" is forbidden: User "kubernetes-admin" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"`

Environment:
OS/Distro: Ubuntu 24.04
Kubernetes Version: 1.30.4 (and 1.29.x)
Kube-vip Version: v0.8.2

Kubeadm-config.yaml:

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs: {}
localAPIEndpoint:
  advertiseAddress: 192.168.1.2
  bindPort: 6443
---

apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: 10.10.0.0/16
kubeProxyArgs: ["--ipvs-exclude-cidrs=192.168.1.0/24"] ###### cidr of node network #######
controlPlaneEndpoint: 192.168.1.1:6443
apiServer:
  certSANs:
  - "kubevip-api-server"
  - "192.168.1.1"
  - "192.168.1.2"

  extraArgs:
    enable-admission-plugins: DefaultTolerationSeconds
    default-not-ready-toleration-seconds: "120"
    default-unreachable-toleration-seconds: "120"
```

Kube-Vip Configuration:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: eth0
    - name: vip_cidr
      value: "24"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.1.1
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.2
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

Additional context
This issue only occurs in Kubernetes versions 1.29.x and above. In Kubernetes 1.28.13, the kubelet correctly uses the local API endpoint, and Kube-Vip functions as expected. The lack of a fallback to the real control plane IP when the VIP is unavailable seems to cause this circular dependency, leading to a deadlock where Kube-Vip can't function, and the kubelet can't register with the API server.
I believe it won't work on Kubernetes 1.31.0 as well.
