### ISSUE TITLE
UPNP only forwards one port on services with multiple ports.

### ISSUE THREAD

**Issue by l0wl3vel** [kube-vip/kube-vip#951]
**Describe the bug**

When enabling port forwarding on a service with multiple ports exposed only one port gets forwarded.

**To Reproduce**
1. Install kube-vip v.0.8.3 and enable UPNP Forwarding
2. Install ingress-nginx
3. only port 80 gets a port forward

**Expected behavior**
All Ports get forwarded

**Environment (please complete the following information):**
 - OS/Distro: NixOS 24.05
 - Kubernetes Version: 1.30.4+k3s1
 - Kube-vip Version: 0.8.3

**`Kube-vip-values.yaml`:**

```yaml
    config:
      address: "192.168.178.247"
      namespace: kube-vip

    # Check https://kube-vip.io/docs/installation/flags/
    env:
      vip_interface: ""
      vip_arp: "true"
      lb_enable: "true"
      lb_port: "6443"
      vip_cidr: "30"
      cp_enable: "true"
      svc_enable: "true"
      svc_election: "true"
      vip_leaderelection: "true"
      enableUPNP: "true"
```
