### ISSUE TITLE
changes to services are not handled

### ISSUE THREAD

**Issue by CrimsonFez** [kube-vip/kube-vip#953]
**Describe the bug**
When changes are made to the Service, those changes are not processed by kube-vip. This only applies to Services after they have been allocated a LoadBalancer.
For example, if you set the LBIP on a service, then change the annotation, it does not allocate the new LBIP.
Additionally, if you change the servicePorts it does not update status.loadBalancer.

**To Reproduce**
1. deploy v0.8.3 with LoadBalancer ARP mode enabled
2. create service
```
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.101.1"
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
```
3. change annotation or ports on service
4. no logs of change in kube-vip and no reflection of change in service status

**Expected behavior**
I would expect that when changes are made to a service after it has been made a LoadBalancer that they are respected.

**Environment (please complete the following information):**
 - OS/Distro:Debian 12
 - Kubernetes Version: v1.30
 - Kube-vip Version: v0.8.3

**`Kube-vip.yaml`:**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-lb
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip-lb
  template:
    metadata:
      labels:
        app: kube-vip-lb
    spec:
      containers:
      - image: ghcr.io/kube-vip/kube-vip-iptables:v0.8.3
        imagePullPolicy: Always
        name: kube-vip
        args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_cidr
          value: "32"
        - name: vip_servicesinterface
          value: dummy0
        - name: svc_enable
          value: "true"
        - name: svc_leasename
          value: kube-vip-lb
        - name: svc_election
          value: "false"
        - name: lb_class_only
          value: "false"
        - name: lb_class_name
          value: kube-vip
        - name: enable_service_security
          value: "false"
        - name: prometheus_server
          value: :2113
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: ghcr.io/404incorporated/kube-vip-bird2:v1.1.0
        imagePullPolicy: Always
        name: bird
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
            - SYS_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/bird
          name: bird-config
      - name: node-address-labeler
        image: ghcr.io/404incorporated/node-address-labeler:v1.0.1
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: INTERFACE
          value: dummy0
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      dnsPolicy: ClusterFirst
      hostNetwork: true
      imagePullSecrets:
      - name: ghcr-crimsonfez
      initContainers:
      - command:
        - bird-gen-config
        - /bird.conf.tmpl
        - /etc/bird/bird.conf
        env:
        - name: PEERS
          value: 192.168.100.1:64512,192.168.100.11:64512,192.168.100.12:64512
        - name: WATCH_INTERFACE
          value: dummy0
        image: ghcr.io/404incorporated/kube-vip-bird2:v1.1.0
        imagePullPolicy: IfNotPresent
        name: bird-gen-config
        resources: {}
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/bird
          name: bird-config
      restartPolicy: Always
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - emptyDir: {}
        name: bird-config
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
**`rbac.yaml`:**
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","get","watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list","get","watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system
```

**Comment by Cellebyte** [comment]
Do you have any logs of your kube-vip pods, please?

**Comment by CrimsonFez** [comment]
```
time="2024-11-10T19:33:56Z" level=info msg="Starting kube-vip.io [v0.8.5]"
time="2024-11-10T19:33:56Z" level=debug msg="Build kube-vip.io [dd06c3fb82bcc14dd876465e3b2ac4098f9d9ec6]"
time="2024-11-10T19:33:56Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[false], Services:[true]"
time="2024-11-10T19:33:56Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2024-11-10T19:33:56Z" level=info msg="prometheus HTTP server started"
time="2024-11-10T19:33:56Z" level=info msg="kube-vip will bind to interface [eno1]"
time="2024-11-10T19:33:56Z" level=warning msg="the status of the interface dummy0 is unknown. Ensure your interface is ready to accept traffic, if so you can safely ignore this message"
time="2024-11-10T19:33:56Z" level=warning msg="Node name is missing from the config, fall back to hostname"
time="2024-11-10T19:33:56Z" level=info msg="Using node name [ganymede03.ord.xxxxxx.net]"
time="2024-11-10T19:33:56Z" level=debug msg="Using external Kubernetes configuration from incluster config."
time="2024-11-10T19:33:56Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-11-10T19:33:56Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [kube-vip-lb], id [ganymede03.ord.xxxxxx.net]"
time="2024-11-10T19:33:56Z" level=info msg="Starting UPNP Port Refresher"
I1110 19:33:56.624209       1 leaderelection.go:250] attempting to acquire leader lease kube-system/kube-vip-lb...
time="2024-11-10T19:33:56Z" level=info msg="new leader elected: ganymede02.ord.xxxxxx.net"
I1110 19:34:23.476486       1 leaderelection.go:260] successfully acquired lease kube-system/kube-vip-lb
time="2024-11-10T19:34:23Z" level=debug msg="skip starting traffic mirroring since it's not enabled."
time="2024-11-10T19:34:23Z" level=info msg="(svcs) starting services watcher for all namespaces"
time="2024-11-10T19:34:23Z" level=debug msg="(svcs) [mc-6oigg-svc-acie5] has been added/modified with addresses [[xxx.xxx.xxx.53]]"
time="2024-11-10T19:34:23Z" level=debug msg="[STARTING] Service Sync"
time="2024-11-10T19:34:23Z" level=debug msg="init enable service security: true"
time="2024-11-10T19:34:23Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.53] via dummy0 for [404club/mc-6oigg-svc-acie5]"
time="2024-11-10T19:34:23Z" level=debug msg="type: 24, route: {Ifindex: 4 Dst: xxx.xxx.xxx.53/32 Src: xxx.xxx.xxx.53 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:23Z" level=debug msg="add iptables rules, vip: xxx.xxx.xxx.53, ports: [{Name:primary Protocol:TCP AppProtocol:<nil> Port:25565 TargetPort:{Type:1 IntVal:0 StrVal:primary} NodePort:32397} {Name:primary-udp Protocol:UDP AppProtocol:<nil> Port:25565 TargetPort:{Type:1 IntVal:0 StrVal:primary-udp} NodePort:32397}]"
time="2024-11-10T19:34:23Z" level=debug msg="(svcs) will update [404club/mc-6oigg-svc-acie5]"
time="2024-11-10T19:34:23Z" level=debug msg="(svcs) broadcasting ARP update for xxx.xxx.xxx.53 via dummy0, every 3000ms"
time="2024-11-10T19:34:26Z" level=info msg="[service] synchronised in 2690ms"
time="2024-11-10T19:34:26Z" level=debug msg="(svcs) [sf-4uzq2-svc-ga60r] has been added/modified with addresses [[xxx.xxx.xxx.54]]"
time="2024-11-10T19:34:26Z" level=debug msg="[STARTING] Service Sync"
time="2024-11-10T19:34:26Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.54"
time="2024-11-10T19:34:26Z" level=debug msg="init enable service security: true"
time="2024-11-10T19:34:26Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.54] via dummy0 for [404club/sf-4uzq2-svc-ga60r]"
time="2024-11-10T19:34:26Z" level=debug msg="type: 24, route: {Ifindex: 4 Dst: xxx.xxx.xxx.54/32 Src: xxx.xxx.xxx.54 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:26Z" level=debug msg="add iptables rules, vip: xxx.xxx.xxx.54, ports: [{Name:primary Protocol:TCP AppProtocol:<nil> Port:7777 TargetPort:{Type:1 IntVal:0 StrVal:primary} NodePort:30363} {Name:primary-udp Protocol:UDP AppProtocol:<nil> Port:7777 TargetPort:{Type:1 IntVal:0 StrVal:primary} NodePort:30363}]"
time="2024-11-10T19:34:26Z" level=debug msg="(svcs) will update [404club/sf-4uzq2-svc-ga60r]"
time="2024-11-10T19:34:26Z" level=debug msg="(svcs) broadcasting ARP update for xxx.xxx.xxx.54 via dummy0, every 3000ms"
time="2024-11-10T19:34:28Z" level=info msg="[service] synchronised in 1977ms"
time="2024-11-10T19:34:28Z" level=debug msg="(svcs) [iperf3] has been added/modified with addresses [[xxx.xxx.xxx.54]]"
time="2024-11-10T19:34:28Z" level=debug msg="[STARTING] Service Sync"
time="2024-11-10T19:34:28Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.54"
time="2024-11-10T19:34:28Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.54"
time="2024-11-10T19:34:28Z" level=debug msg="init enable service security: true"
time="2024-11-10T19:34:28Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.54] via dummy0 for [default/iperf3]"
time="2024-11-10T19:34:28Z" level=debug msg="type: 25, route: {Ifindex: 4 Dst: xxx.xxx.xxx.54/32 Src: xxx.xxx.xxx.54 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:28Z" level=debug msg="remove iptables rules, vip: xxx.xxx.xxx.54, ports: [{Name: Protocol:TCP AppProtocol:<nil> Port:5201 TargetPort:{Type:0 IntVal:5201 StrVal:} NodePort:32081}]"
time="2024-11-10T19:34:28Z" level=debug msg="type: 24, route: {Ifindex: 4 Dst: xxx.xxx.xxx.54/32 Src: xxx.xxx.xxx.54 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:28Z" level=debug msg="add iptables rules, vip: xxx.xxx.xxx.54, ports: [{Name: Protocol:TCP AppProtocol:<nil> Port:5201 TargetPort:{Type:0 IntVal:5201 StrVal:} NodePort:32081}]"
time="2024-11-10T19:34:28Z" level=debug msg="(svcs) will update [default/iperf3]"
time="2024-11-10T19:34:28Z" level=debug msg="(svcs) broadcasting ARP update for xxx.xxx.xxx.54 via dummy0, every 3000ms"
time="2024-11-10T19:34:30Z" level=info msg="[service] synchronised in 2608ms"
time="2024-11-10T19:34:30Z" level=debug msg="(svcs) [mc-9jjt9-svc-jbtn5] has been added/modified with addresses [[xxx.xxx.xxx.54]]"
time="2024-11-10T19:34:30Z" level=debug msg="[STARTING] Service Sync"
time="2024-11-10T19:34:30Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.54"
time="2024-11-10T19:34:30Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.54"
time="2024-11-10T19:34:30Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.54"
time="2024-11-10T19:34:30Z" level=debug msg="init enable service security: true"
time="2024-11-10T19:34:30Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.54] via dummy0 for [demo2/mc-9jjt9-svc-jbtn5]"
time="2024-11-10T19:34:30Z" level=debug msg="type: 25, route: {Ifindex: 4 Dst: xxx.xxx.xxx.54/32 Src: xxx.xxx.xxx.54 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:30Z" level=debug msg="remove iptables rules, vip: xxx.xxx.xxx.54, ports: [{Name:primary Protocol:TCP AppProtocol:<nil> Port:25565 TargetPort:{Type:1 IntVal:0 StrVal:primary} NodePort:30669} {Name:primary-udp Protocol:UDP AppProtocol:<nil> Port:25565 TargetPort:{Type:1 IntVal:0 StrVal:primary-udp} NodePort:30669}]"
time="2024-11-10T19:34:30Z" level=debug msg="type: 24, route: {Ifindex: 4 Dst: xxx.xxx.xxx.54/32 Src: xxx.xxx.xxx.54 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:30Z" level=debug msg="add iptables rules, vip: xxx.xxx.xxx.54, ports: [{Name:primary Protocol:TCP AppProtocol:<nil> Port:25565 TargetPort:{Type:1 IntVal:0 StrVal:primary} NodePort:30669} {Name:primary-udp Protocol:UDP AppProtocol:<nil> Port:25565 TargetPort:{Type:1 IntVal:0 StrVal:primary-udp} NodePort:30669}]"
time="2024-11-10T19:34:30Z" level=debug msg="(svcs) will update [demo2/mc-9jjt9-svc-jbtn5]"
time="2024-11-10T19:34:30Z" level=debug msg="(svcs) broadcasting ARP update for xxx.xxx.xxx.54 via dummy0, every 3000ms"
time="2024-11-10T19:34:32Z" level=info msg="[service] synchronised in 2195ms"
time="2024-11-10T19:34:32Z" level=debug msg="(svcs) [gitea-ssh] has been added/modified with addresses [[xxx.xxx.xxx.52]]"
time="2024-11-10T19:34:32Z" level=debug msg="[STARTING] Service Sync"
time="2024-11-10T19:34:32Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:32Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:32Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:32Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:32Z" level=debug msg="init enable service security: true"
time="2024-11-10T19:34:32Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.52] via dummy0 for [gitea-prod/gitea-ssh]"
time="2024-11-10T19:34:32Z" level=debug msg="type: 24, route: {Ifindex: 4 Dst: xxx.xxx.xxx.52/32 Src: xxx.xxx.xxx.52 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:32Z" level=debug msg="add iptables rules, vip: xxx.xxx.xxx.52, ports: [{Name:ssh Protocol:TCP AppProtocol:<nil> Port:22 TargetPort:{Type:0 IntVal:2222 StrVal:} NodePort:31466}]"
time="2024-11-10T19:34:32Z" level=debug msg="(svcs) will update [gitea-prod/gitea-ssh]"
time="2024-11-10T19:34:32Z" level=debug msg="(svcs) broadcasting ARP update for xxx.xxx.xxx.52 via dummy0, every 3000ms"
time="2024-11-10T19:34:35Z" level=info msg="[service] synchronised in 2307ms"
time="2024-11-10T19:34:35Z" level=debug msg="(svcs) [ingress-nginx-internal-controller] has been added/modified with addresses [[xxx.xxx.xxx.10]]"
time="2024-11-10T19:34:35Z" level=debug msg="[STARTING] Service Sync"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.10"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.10"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.10"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.10"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.10"
time="2024-11-10T19:34:35Z" level=debug msg="init enable service security: true"
time="2024-11-10T19:34:35Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.10] via dummy0 for [ingress-nginx-internal/ingress-nginx-internal-controller]"
time="2024-11-10T19:34:35Z" level=debug msg="type: 24, route: {Ifindex: 4 Dst: xxx.xxx.xxx.10/32 Src: xxx.xxx.xxx.10 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:35Z" level=debug msg="add iptables rules, vip: xxx.xxx.xxx.10, ports: [{Name:http Protocol:TCP AppProtocol:0xc0006d5cd0 Port:80 TargetPort:{Type:1 IntVal:0 StrVal:http} NodePort:31809} {Name:https Protocol:TCP AppProtocol:0xc0006d5ce0 Port:443 TargetPort:{Type:1 IntVal:0 StrVal:https} NodePort:31846}]"
time="2024-11-10T19:34:35Z" level=debug msg="(svcs) will update [ingress-nginx-internal/ingress-nginx-internal-controller]"
time="2024-11-10T19:34:35Z" level=debug msg="(svcs) broadcasting ARP update for xxx.xxx.xxx.10 via dummy0, every 3000ms"
time="2024-11-10T19:34:35Z" level=info msg="[service] synchronised in 207ms"
time="2024-11-10T19:34:35Z" level=debug msg="(svcs) [ingress-nginx-controller] has been added/modified with addresses [[xxx.xxx.xxx.52]]"
time="2024-11-10T19:34:35Z" level=debug msg="[STARTING] Service Sync"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:35Z" level=debug msg="isDHCP: false, newServiceAddress: xxx.xxx.xxx.52"
time="2024-11-10T19:34:35Z" level=debug msg="init enable service security: true"
time="2024-11-10T19:34:35Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.52] via dummy0 for [ingress-nginx/ingress-nginx-controller]"
time="2024-11-10T19:34:35Z" level=debug msg="type: 25, route: {Ifindex: 4 Dst: xxx.xxx.xxx.52/32 Src: xxx.xxx.xxx.52 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:35Z" level=debug msg="remove iptables rules, vip: xxx.xxx.xxx.52, ports: [{Name:http Protocol:TCP AppProtocol:0xc0003413f0 Port:80 TargetPort:{Type:1 IntVal:0 StrVal:http} NodePort:31901} {Name:https Protocol:TCP AppProtocol:0xc0003415a0 Port:443 TargetPort:{Type:1 IntVal:0 StrVal:https} NodePort:32761}]"
time="2024-11-10T19:34:35Z" level=debug msg="type: 24, route: {Ifindex: 4 Dst: xxx.xxx.xxx.52/32 Src: xxx.xxx.xxx.52 Gw: <nil> Flags: [] Table: 255 Realm: 0}"
time="2024-11-10T19:34:35Z" level=debug msg="add iptables rules, vip: xxx.xxx.xxx.52, ports: [{Name:http Protocol:TCP AppProtocol:0xc0003413f0 Port:80 TargetPort:{Type:1 IntVal:0 StrVal:http} NodePort:31901} {Name:https Protocol:TCP AppProtocol:0xc0003415a0 Port:443 TargetPort:{Type:1 IntVal:0 StrVal:https} NodePort:32761}]"
time="2024-11-10T19:34:35Z" level=debug msg="(svcs) will update [ingress-nginx/ingress-nginx-controller]"
time="2024-11-10T19:34:35Z" level=debug msg="(svcs) broadcasting ARP update for xxx.xxx.xxx.52 via dummy0, every 3000ms"
time="2024-11-10T19:34:37Z" level=info msg="[service] synchronised in 1724ms"
time="2024-11-10T19:38:56Z" level=info msg="[UPNP] Refreshing 7 Instances"
```

Here are my logs. I used log level 5. I attempted to change a service external IP address, but it is not visible in the logs. If it were visible it would be at the end.

**Comment by Cellebyte** [comment]
@CrimsonFez could you exactly describe what you changed. This make reproducing easier.

**Comment by CrimsonFez** [comment]
I am sending a post request to the kubernetes API to update the kube-vip annotation from the existing IP address to a new one.

**Comment by Cellebyte** [comment]
did you also tried updating the `.status.ingress.loadBalancer` field in the ressource?

**Comment by CrimsonFez** [comment]
it has no affect

**Comment by Cellebyte** [comment]
@CrimsonFez seems to be an issue.
@p-strusiewiczsurmacki-mobica maybe can you investigate this?

**Comment by p-strusiewiczsurmacki-mobica** [comment]
@Cellebyte I've looked quickly into this. I think that there are few issues here. First of all, we're getting the IP from `status.ingress.loadbalancer` (which takes precedence before `loadBalancerIP` field), which is not being updated. Then this update is not propagated into internal cluster instances and then the old IP address is reassigned to the interface when ARP broadcast is called.

If no one will fix this then I'll try to do so, but I won't be available before third week of January, sadly. :(

**Comment by thebsdbox** [comment]
I can try and have a look into this :)

**Comment by thebsdbox** [comment]
@CrimsonFez / @thebsdbox Can you have a look at the PR and say if it is what was expected?

**Comment by Cellebyte** [comment]
@thebsdbox I think so. Just need to test it out.

**Comment by CrimsonFez** [comment]
It looks like the svc is brought down, but not re-added with the new ip. It was created with .53 and changed to .54
```
time="2025-01-17T04:17:36Z" level=info msg="(svcs) [demo/mc-sriv7-svc-lz7z1] has been deleted"
time="2025-01-17T04:17:45Z" level=info msg="(svcs) adding VIP [xxx.xxx.xxx.53] via dummy0 for [demo/mc-sriv7-svc-k5r3w]"
time="2025-01-17T04:17:48Z" level=info msg="[service] synchronised in 2568ms"
time="2025-01-17T04:18:17Z" level=warning msg="(svcs) The load balancer has changed, cancelling original load balancer"
time="2025-01-17T04:18:17Z" level=warning msg="(svcs) waiting for load balancer to finish"
time="2025-01-17T04:18:17Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2025-01-17T04:18:17Z" level=info msg="[VIP] Releasing the Virtual IP [xxx.xxx.xxx.53]"
time="2025-01-17T04:18:17Z" level=info msg="Removed [62e49780-bb32-4052-b278-2cdff614b3d6] from manager, [9] advertised services remain"

```

I'm also seeing that when ports on the svc change they aren't updated in the status. Although it looks like kube-vip is updating other things, since I'm able to connect on the new port. I have port security enabled.
```
spec:
  ports:
    - name: primary
      protocol: TCP
      port: 25567
      targetPort: primary
      nodePort: 32085
    - name: primary-udp
      protocol: UDP
      port: 25567
      targetPort: primary-udp
      nodePort: 32085
status:
  loadBalancer:
    ingress:
      - ip: xxx.xxx.xxx.54
        ipMode: VIP
        ports:
          - port: 25568
            protocol: TCP
          - port: 25568
            protocol: UDP
```
