### ISSUE TITLE
Iptables rules are persisting after service deletion

### ISSUE THREAD

**Issue by thebsdbox** [kube-vip/kube-vip#966]
**Describe the bug**

When egress rules are deleted some rules persist in nftables/iptables.

**To Reproduce**

**Expected behavior**
Egress Rules should be cleaned if leader changes or pod is dismantled.

**Screenshots**
```
-A KUBE-VIP-EGRESS -d 10.0.0.0/16 -m comment --comment "a3ViZS12aXAK=kube-vip-e2e-test" -j RETURN
-A KUBE-VIP-EGRESS -d 10.96.0.0/12 -m comment --comment "a3ViZS12aXAK=kube-vip-e2e-test" -j RETURN
-A KUBE-VIP-EGRESS -s 172.30.3.22/32 -m comment --comment "a3ViZS12aXAK=kube-vip-e2e-test" -j MARK --set-xmark 0x40/0x40
```

first node with leader
```
time="2024-10-10T15:47:47Z" level=debug msg="[endpoints] processing endpoint [172.30.0.125]"
time="2024-10-10T15:47:47Z" level=debug msg="[endpoints] found local endpoint - address: 172.30.0.125, hostname: , node: cbnutsch-1-default-n22jh-5dqbs"
time="2024-10-10T15:47:47Z" level=debug msg="[endpoints watcher] service e2e-test/hpeocsnf: local endpoint(s) [1], known good [172.30.0.125], active election [false]"
time="2024-10-10T15:47:47Z" level=info msg="(svc election) service [hpeocsnf], namespace [e2e-test], lock name [kubevip-hpeocsnf], host id [cbnutsch-1-default-n22jh-5dqbs]"
I1010 15:47:47.429167       1 leaderelection.go:250] attempting to acquire leader lease e2e-test/kubevip-hpeocsnf...
time="2024-10-10T15:47:47Z" level=info msg="(svc election) new leader elected: cbnutsch-1-default-n22jh-65p2h"
I1010 15:47:49.394077       1 leaderelection.go:260] successfully acquired lease e2e-test/kubevip-hpeocsnf
time="2024-10-10T15:47:49Z" level=debug msg="[STARTING] Service Sync"
time="2024-10-10T15:47:49Z" level=debug msg="init enable service security: false"
time="2024-10-10T15:47:49Z" level=info msg="(svcs) adding VIP [10.100.76.132] via lo for [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="(svcs) will update [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Flushing conntrack rules for service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Enabling egress for the service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=warning msg="pods is forbidden: User \"system:serviceaccount:e2e-test:kube-vip-serviceaccount\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\""
time="2024-10-10T15:47:49Z" level=info msg="[Egress] pod CIDR [10.0.0.0/16], service CIDR [10.96.0.0/12] for vip [10.100.76.132] / pod [172.30.0.125]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Creating an iptables client, nftables mode [false]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Checking for Chain [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.0.0.0/16] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.96.0.0/12] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Marking packets on network [172.30.0.125/32]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump from mangle prerouting to [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding source nat from [172.30.0.125] => [10.100.76.132]"
time="2024-10-10T15:47:49Z" level=info msg="[service] synchronised in 172ms"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints] processing endpoint [172.30.0.125]"
```

second node with standby.
```
time="2024-10-10T15:47:49Z" level=debug msg="[STARTING] Service Sync"
time="2024-10-10T15:47:49Z" level=debug msg="init enable service security: false"
time="2024-10-10T15:47:49Z" level=info msg="(svcs) adding VIP [10.100.76.132] via lo for [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="(svcs) will update [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Flushing conntrack rules for service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Enabling egress for the service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=warning msg="pods is forbidden: User \"system:serviceaccount:e2e-test:kube-vip-serviceaccount\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\""
time="2024-10-10T15:47:49Z" level=info msg="[Egress] pod CIDR [10.0.0.0/16], service CIDR [10.96.0.0/12] for vip [10.100.76.132] / pod [172.30.0.125]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Creating an iptables client, nftables mode [false]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Checking for Chain [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.0.0.0/16] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.96.0.0/12] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Marking packets on network [172.30.0.125/32]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump from mangle prerouting to [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding source nat from [172.30.0.125] => [10.100.76.132]"
time="2024-10-10T15:47:49Z" level=info msg="[service] synchronised in 172ms"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints] processing endpoint [172.30.0.125]"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints] found local endpoint - address: 172.30.0.125, hostname: , node: cbnutsch-1-default-n22jh-5dqbs"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints watcher] service e2e-test/hpeocsnf: local endpoint(s) [1], known good [172.30.0.125], active election [true]"
time="2024-10-10T15:47:54Z" level=info msg="(svcs) [nginx-plus-wsg-nginx-ingress-controller] specified no loadBalancer class, expected [kubeviplb], ignoring"
time="2024-10-10T15:47:59Z" level=debug msg="[endpoints] processing endpoint [172.30.3.22]"
time="2024-10-10T15:47:59Z" level=warning msg="[endpoints] existing [172.30.0.125] has been removed, no remaining endpoints for leaderElection"
time="2024-10-10T15:47:59Z" level=debug msg="[endpoints watcher] service e2e-test/hpeocsnf: local endpoint(s) [0], known good [], active election [false]"
time="2024-10-10T15:47:59Z" level=info msg="(svc election) service [hpeocsnf] leader lost: [cbnutsch-1-default-n22jh-5dqbs]"
time="2024-10-10T15:47:59Z" level=debug msg="Looking for [5002134b-4e1f-4f01-8083-eb70026df473], found [5002134b-4e1f-4f01-8083-eb70026df473]"
time="2024-10-10T15:47:59Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2024-10-10T15:47:59Z" level=info msg="[VIP] Deleting Route for Virtual IP [10.100.76.132]"
time="2024-10-10T15:47:59Z" level=info msg="service [hpeocsnf] has an egress re-write enabled"
time="2024-10-10T15:47:59Z" level=info msg="[egress] Creating an iptables client, nftables mode [false]"
time="2024-10-10T15:47:59Z" level=info msg="[egress] Stopping marking packets on network [172.30.0.125]"
time="2024-10-10T15:47:59Z" level=info msg="[egress] Removing source nat from [172.30.0.125] => [10.100.76.132]"
time="2024-10-10T15:47:59Z" level=info msg="Removed [5002134b-4e1f-4f01-8083-eb70026df473] from manager, [0] advertised services remain"
time="2024-10-10T15:47:59Z" level=info msg="(svc election) for service [hpeocsnf] stopping"
time="2024-10-10T15:48:01Z" level=debug msg="(svcs) [hpeocsnf] has been added/modified with addresses [[10.100.76.132]]"
```
**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: 1.29.x
 - Kube-vip Version: 0.8.4

**`Kube-vip.yaml`:**
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-vip-role
  namespace: test
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/status
  - nodes
  - endpoints
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - get
  - watch
  - update
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-serviceaccount
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-vip-rolebinding
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip-serviceaccount
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: kube-vip
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip
        app.kubernetes.io/version: v0.8.4
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
            weight: 1
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: test
                operator: In
                values:
                - "true"
            namespaceSelector: {}
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - kube-vip
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - manager
        - --prometheusHTTPServer
        - ""
        env:
        - name: svc_namespace
          value: test
        - name: lb_class_legacy_handling
          value: "false"
        - name: lb_class_name
          value: kubeviplb
        - name: vip_routingtableid
          value: "2864285557"
        - name: vip_routingtable
          value: "true"
        - name: vip_cleanroutingtable
          value: "true"
        - name: svc_election
          value: "true"
        - name: vip_interface
          value: lo
        - name: vip_cidr
          value: "32"
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: svc_enable
          value: "true"
        - name: vip_startleader
          value: "true"
        - name: vip_addpeerstolb
          value: "true"
        - name: vip_leaseduration
          value: "3"
        - name: vip_renewdeadline
          value: "2"
        - name: vip_retryperiod
          value: "1"
        - name: egress_podcidr
          value: 172.30.0.0/18
        - name: egress_servicecidr
          value: 172.30.64.0/18
        - name: vip_loglevel
          value: "5"
        - name: egress_withnftables
          value: "true"
        - name: EGRESS_CLEAN
          value: "true"
        - name: dnsMode
          value: ipv4
        image: artifactory.devops.telekom.de/dtt-cb-cbnutsch-dev-docker/kube-vip-iptables:v0.8.4
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip-serviceaccount
      serviceAccountName: kube-vip-serviceaccount
      terminationGracePeriodSeconds: 30
```
**Additional context**

This could be somehow related to egress IPv6 and the auto detect of the pod/service code ranges.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @thebsdbox do you need someone to work on this? If so, I can take a look.

**Comment by thebsdbox** [comment]
Hey @p-strusiewiczsurmacki-mobica im currently working on the e2e testing, so if you've time to move this quicker then please do.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
@thebsdbox Are you able to share the yaml for the service you're using by any chance?

**Comment by thebsdbox** [comment]
Other than the yaml snippet above everything else has come from @Cellebyte. The e2e changes are in progress on my laptop, but I'm currently travelling.

**Comment by Cellebyte** [comment]
@thebsdbox I gave @p-strusiewiczsurmacki-mobica everything he needs for now

**Comment by thebsdbox** [comment]
Thanks, the Rbac.yaml appears to be missing the required perms for listing pods. Additionally this failure means that the podcidr and servicecidr ranges are dropping to defaults and ignoring the environment variables.

**Comment by Cellebyte** [comment]
@thebsdbox they deploy it namespaced and not cluster wide. That is why their deployment has no access to the `kube-system` namespace.

**Comment by thebsdbox** [comment]
👋 @p-strusiewiczsurmacki-mobica is there anything I can do to assist?

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @thebsdbox , I've just created draft PR for that.

It turned out that there were a few issues.

1. The auto CIDR discovery was not working as RBAC was missing the access to the `kube-system namespace`. If kube-vip is not running in `kube-system` something appropriate role and binfings have to be added to the rbac:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-vip-role
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
 ---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-vip-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip-serviceaccount
  namespace: test
```

I am wondering if this should be added somewhere in the docs?

2. It seems that even with proper CIDR, egress rules were only created during leader election and were not updated in other cases (e.g. leader was not changed, but  endpoint was deleted so the `lastKnownGoodEndpoint` changed, etc). There were also some context issues I think, as if kube-vip pod was terminated, endpoint watching was not terminated by context, so egress was not removed. I think that should be fixed now.

As for the e2e-tests, I've encountered the issues this time, but I just wanted to run those to check if my changes did not affect at least any ARP functionality, so I've investigated a little and for me it seems that the kind clusters are not coming up so the kube-vip's image cannot be loaded into kind.

In my setup the issue for kind misbehavior were the `ulimits` reached while 6 clusters are running in parallel. These are the logs from k8s apiserver on one of my nodes:

```
022 12:07:15.393199       1 dynamic_cafile_content.go:166] "Failed to watch CA file, will retry later" err="error creating fsnotify watcher: too many open files"
E1022 12:07:15.393364       1 dynamic_cafile_content.go:166] "Failed to watch CA file, will retry later" err="error creating fsnotify watcher: too many open files"
E1022 12:07:15.393494       1 dynamic_serving_content.go:141] "Failed to watch cert and key file, will retry later" err="error creating fsnotify watcher: too many open files"
E1022 12:07:15.419863       1 dynamic_serving_content.go:141] "Failed to watch cert and key file, will retry later" err="error creating fsnotify watcher: too many open files"
E1022 12:07:15.461648       1 dynamic_cafile_content.go:166] "Failed to watch CA file, will retry later" err="error creating fsnotify watcher: too many open files"
E1022 12:07:15.461648       1 dynamic_cafile_content.go:166] "Failed to watch CA file, will retry later" err="error creating fsnotify watcher: too many open files"
```

I've changed e2e tests to load image only when cluster is up, and changed  limits on my host system to:
```
fs.file-max=500000
fs.inotify.max_user_watches = 2147483647
fs.inotify.max_user_instances = 8192
```

And the tests seems to work mostly fine, I think.

However if you have better approach for this then I can remove commit with E2E changes from the PR.
